// apps/user-app/src/app/features/portfolio/portfolio.component.ts
import { Component, OnInit, inject, signal, computed, DestroyRef } from '@angular/core';
import { DecimalPipe, LowerCasePipe } from '@angular/common';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ChartModule } from 'primeng/chart';
import { ButtonModule } from 'primeng/button';
import { SkeletonModule } from 'primeng/skeleton';
import { ToastModule } from 'primeng/toast';
import { TooltipModule } from 'primeng/tooltip';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { MessageService, ConfirmationService } from 'primeng/api';

import {
  PortfolioApiService,
  PortfolioResponse,
  PnlResponse,
  PaperSummary,
  Position,
} from '../../core/services/portfolio-api.service';
import { WebSocketService } from '../../core/services/websocket.service';

type Tab    = 'live' | 'paper';
type Period = '7d' | '30d' | '90d' | 'allTime';

@Component({
  selector: 'app-portfolio',
  standalone: true,
  imports: [DecimalPipe, LowerCasePipe, ChartModule, ButtonModule, SkeletonModule, ToastModule, TooltipModule, ConfirmDialogModule],
  providers: [MessageService, ConfirmationService],
  templateUrl: './portfolio.component.html',
})
export class PortfolioComponent implements OnInit {
  private readonly api        = inject(PortfolioApiService);
  private readonly ws         = inject(WebSocketService);
  private readonly toast      = inject(MessageService);
  private readonly confirm    = inject(ConfirmationService);
  private readonly destroyRef = inject(DestroyRef);

  tab    = signal<Tab>('live');
  period = signal<Period>('7d');

  portfolio     = signal<PortfolioResponse | null>(null);
  pnl           = signal<PnlResponse | null>(null);
  paper         = signal<PaperSummary | null>(null);
  chartData     = signal<object | null>(null);
  chartOptions  = signal<object | null>(null);

  loadingPortfolio = signal(true);
  loadingChart     = signal(true);
  loadingPaper     = signal(false);
  closingPosition  = signal<Record<string, boolean>>({});
  resettingPaper   = signal(false);

  readonly periods: { label: string; value: Period }[] = [
    { label: '7d',    value: '7d' },
    { label: '30d',   value: '30d' },
    { label: '90d',   value: '90d' },
    { label: 'All',   value: 'allTime' },
  ];

  readonly totalPnl = computed(() => parseFloat(this.pnl()?.totalPnl ?? '0'));
  readonly isProfitable = computed(() => this.totalPnl() >= 0);

  ngOnInit(): void {
    this.ws.connect();
    this.loadPortfolio();
    this.loadChart();
  }

  loadPortfolio(): void {
    this.loadingPortfolio.set(true);
    this.api.portfolio().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  res => { this.portfolio.set(res); this.loadingPortfolio.set(false); },
      error: ()  => this.loadingPortfolio.set(false),
    });
  }

  loadChart(): void {
    this.loadingChart.set(true);
    this.api.pnl(this.period()).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  res => { this.pnl.set(res); this.buildChart(res); this.loadingChart.set(false); },
      error: ()  => this.loadingChart.set(false),
    });
  }

  loadPaper(): void {
    this.loadingPaper.set(true);
    this.api.paperSummary().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  res => { this.paper.set(res); this.loadingPaper.set(false); },
      error: ()  => this.loadingPaper.set(false),
    });
  }

  setTab(t: Tab): void {
    this.tab.set(t);
    if (t === 'paper' && !this.paper()) this.loadPaper();
  }

  setPeriod(p: Period): void {
    this.period.set(p);
    this.loadChart();
  }

  closePosition(pos: Position): void {
    this.closingPosition.update(m => ({ ...m, [pos.id]: true }));
    this.api.closePosition({ tokenId: pos.tokenId }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: () => {
        this.closingPosition.update(m => ({ ...m, [pos.id]: false }));
        this.toast.add({ severity: 'success', summary: 'Close order submitted', detail: 'FOK sell order queued.', life: 3000 });
        this.loadPortfolio();
      },
      error: (err) => {
        this.closingPosition.update(m => ({ ...m, [pos.id]: false }));
        this.toast.add({ severity: 'error', summary: 'Close failed', detail: err?.error?.message ?? 'Unknown error', life: 4000 });
      },
    });
  }

  resetPaper(): void {
    this.confirm.confirm({
      message: 'This will delete all paper positions and orders. This cannot be undone.',
      header: 'Reset Paper Account?',
      icon: 'pi pi-exclamation-triangle',
      acceptButtonStyleClass: 'p-button-danger',
      accept: () => {
        this.resettingPaper.set(true);
        this.api.paperReset().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
          next: () => {
            this.resettingPaper.set(false);
            this.paper.set({ pnl: '0', positions: [], orderCount: 0 });
            this.toast.add({ severity: 'success', summary: 'Paper account reset', life: 3000 });
          },
          error: () => this.resettingPaper.set(false),
        });
      },
    });
  }

  private buildChart(data: PnlResponse): void {
    const isProfitable = parseFloat(data.totalPnl) >= 0;
    const lineColor    = isProfitable ? '#10B981' : '#EF4444';
    const fillColor    = isProfitable ? 'rgba(16,185,129,0.08)' : 'rgba(239,68,68,0.08)';

    const labels = data.snapshots.map(s => {
      const dt = new Date(s.time);
      return this.period() === '90d' || this.period() === 'allTime'
        ? dt.toLocaleDateString([], { month: 'short', day: 'numeric' })
        : dt.toLocaleDateString([], { month: 'short', day: 'numeric' });
    });

    this.chartData.set({
      labels,
      datasets: [{
        label:            'P&L',
        data:             data.snapshots.map(s => parseFloat(s.pnl)),
        borderColor:      lineColor,
        backgroundColor:  fillColor,
        fill:             true,
        tension:          0.3,
        borderWidth:      1.5,
        pointRadius:      0,
        pointHoverRadius: 4,
      }],
    });

    const style = getComputedStyle(document.documentElement);
    const gridColor = style.getPropertyValue('--pf-border-subtle').trim() || '#1A2840';
    const tickColor = style.getPropertyValue('--pf-text-muted').trim() || '#445E7A';
    const tooltipBg = style.getPropertyValue('--pf-bg-elevated').trim() || '#111D2E';
    const tooltipTitle = style.getPropertyValue('--pf-text-primary').trim() || '#E8EDF5';
    const tooltipBody = style.getPropertyValue('--pf-text-secondary').trim() || '#7A94B4';
    const tooltipBorder = style.getPropertyValue('--pf-border-default').trim() || '#1E3350';

    this.chartOptions.set({
      responsive:          true,
      maintainAspectRatio: false,
      animation:           false,
      interaction:         { mode: 'index', intersect: false },
      plugins: {
        legend: { display: false },
        tooltip: {
          backgroundColor: tooltipBg,
          titleColor:      tooltipTitle,
          bodyColor:       tooltipBody,
          borderColor:     tooltipBorder,
          borderWidth:     1,
          padding:         12,
          cornerRadius:    6,
          titleFont:       { family: "'JetBrains Mono', monospace", size: 11 },
          bodyFont:        { family: "'JetBrains Mono', monospace", size: 12 },
          callbacks: {
            label: (ctx: { parsed: { y: number } }) =>
              `  ${ctx.parsed.y >= 0 ? '+' : ''}$${ctx.parsed.y.toFixed(2)}`,
          },
        },
      },
      scales: {
        x: {
          grid:  { color: gridColor },
          ticks: { color: tickColor, font: { family: "'JetBrains Mono', monospace", size: 10 }, maxTicksLimit: 8 },
        },
        y: {
          grid:  { color: gridColor },
          ticks: {
            color: tickColor,
            font:  { family: "'JetBrains Mono', monospace", size: 10 },
            callback: (v: number) => `$${v.toFixed(0)}`,
          },
        },
      },
    });
  }

  pnlColor(val: string): string {
    const n = parseFloat(val);
    if (n > 0) return 'var(--pf-pnl-positive)';
    if (n < 0) return 'var(--pf-pnl-negative)';
    return 'var(--pf-pnl-neutral)';
  }

  formatPnl(val: string): string {
    const n = parseFloat(val);
    return `${n >= 0 ? '+' : ''}$${Math.abs(n).toFixed(2)}`;
  }

  winRatePct(val: string): string {
    return `${(parseFloat(val) * 100).toFixed(1)}%`;
  }
}

<p-toast position="top-right" />
<p-confirmDialog />

<div class="pf-page">

  <!-- ─── Header ──────────────────────────────────────────────────────── -->
  <div class="page-header">
    <h1>Portfolio</h1>
    <div class="portfolio-tabs">
      <button class="filter-tab" [class.active]="tab() === 'live'"  (click)="setTab('live')">Live</button>
      <button class="filter-tab" [class.active]="tab() === 'paper'" (click)="setTab('paper')">Paper</button>
    </div>
  </div>

  <!-- ════════════════════ LIVE TAB ════════════════════ -->
  @if (tab() === 'live') {

    <!-- ─── Summary cards ──────────────────────────────────────────────── -->
    <div class="portfolio-summary-row">
      @if (loadingPortfolio()) {
        @for (s of [1,2,3]; track s) { <div class="summary-card"><p-skeleton height="40px" /></div> }
      } @else if (portfolio(); as p) {
        <div class="summary-card" pTooltip="Based on current market prices" tooltipPosition="bottom"
             [style.border-left]="'3px solid ' + pnlColor(p.totalUnrealizedPnl)">
          <span class="summary-label">Unrealized P&L</span>
          <span class="summary-value pf-mono" [style.color]="pnlColor(p.totalUnrealizedPnl)">
            {{ formatPnl(p.totalUnrealizedPnl) }}
          </span>
        </div>
        <div class="summary-card" pTooltip="Profit and loss from closed positions" tooltipPosition="bottom"
             [style.border-left]="'3px solid ' + pnlColor(p.totalRealizedPnl)">
          <span class="summary-label">Realized P&L</span>
          <span class="summary-value pf-mono" [style.color]="pnlColor(p.totalRealizedPnl)">
            {{ formatPnl(p.totalRealizedPnl) }}
          </span>
        </div>
        <div class="summary-card" pTooltip="Percentage of profitable closed positions" tooltipPosition="bottom"
             style="border-left:3px solid var(--pf-cyan-500)">
          <span class="summary-label">Win Rate</span>
          <span class="summary-value pf-mono" style="color:var(--pf-cyan-500)">
            {{ winRatePct(pnl()?.winRate ?? '0') }}
          </span>
        </div>
        <div class="summary-card" pTooltip="Number of currently active positions" tooltipPosition="bottom"
             style="border-left:3px solid var(--pf-text-primary)">
          <span class="summary-label">Open Positions</span>
          <span class="summary-value pf-mono" style="color:var(--pf-text-primary)">
            {{ p.positions.length }}
          </span>
        </div>
      }
    </div>

    <!-- ─── P&L Chart ────────────────────────────────────────────────────── -->
    <div class="portfolio-chart-panel">
      <div class="panel-header">
        <span class="panel-title">P&L Over Time</span>
        <div style="display:flex;gap:4px">
          @for (p of periods; track p.value) {
            <button class="res-btn" [class.active]="period() === p.value" (click)="setPeriod(p.value)">
              {{ p.label }}
            </button>
          }
        </div>
      </div>
      @if (loadingChart()) {
        <div class="chart-wrap" style="height:260px">
          <p-skeleton height="100%" />
        </div>
      } @else if (chartData()) {
        <div class="chart-wrap" style="height:260px">
          <p-chart type="line" [data]="chartData()" [options]="chartOptions()" height="260px" />
        </div>
      } @else {
        <div class="pf-empty-state" style="max-height:150px;padding:32px">
          <i class="pi pi-chart-line pf-empty-icon"></i>
          <p class="pf-empty-title">No P&L data yet</p>
          <p class="pf-empty-desc">P&L data will appear once your strategies generate trades.</p>
        </div>
      }
    </div>

    <!-- ─── Positions table ──────────────────────────────────────────────── -->
    <div class="portfolio-table-panel">
      <div class="panel-header">
        <span class="panel-title">Open Positions</span>
      </div>

      @if (loadingPortfolio()) {
        <div style="padding:16px">
          @for (s of [1,2,3]; track s) { <p-skeleton height="40px" styleClass="mb-2" /> }
        </div>
      } @else if ((portfolio()?.positions ?? []).length === 0) {
        <div class="pf-empty-state">
          <i class="pi pi-wallet pf-empty-icon"></i>
          <p class="pf-empty-title">No open positions</p>
          <p class="pf-empty-desc">Start a strategy to build positions.</p>
        </div>
      } @else {
        <div class="table-scroll">
          <table class="data-table">
            <thead>
              <tr>
                <th class="pf-col-label">Market</th>
                <th class="pf-col-label">Side</th>
                <th class="pf-col-label" style="text-align:right">Size</th>
                <th class="pf-col-label" style="text-align:right">Avg Entry</th>
                <th class="pf-col-label" style="text-align:right">Current</th>
                <th class="pf-col-label" style="text-align:right">Unreal. P&L</th>
                <th class="pf-col-label" style="text-align:right">Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              @for (pos of portfolio()!.positions; track pos.id) {
                <tr class="table-row">
                  <td class="market-title-cell">
                    <span class="market-title" [title]="pos.marketTitle">{{ pos.marketTitle }}</span>
                  </td>
                  <td>
                    <span class="outcome-badge" [class]="pos.side | lowercase">{{ pos.side }}</span>
                  </td>
                  <td style="text-align:right">
                    <span class="pf-mono">{{ pos.size | number:'1.0-0' }}</span>
                  </td>
                  <td style="text-align:right">
                    <span class="pf-mono">{{ pos.avgEntryPrice | number:'1.3-3' }}</span>
                  </td>
                  <td style="text-align:right">
                    <span class="pf-mono" style="color:var(--pf-cyan-500)">
                      @if (+pos.currentPrice === 0) {
                        —
                      } @else {
                        {{ pos.currentPrice | number:'1.3-3' }}
                      }
                    </span>
                  </td>
                  <td style="text-align:right">
                    <span class="pf-mono" [style.color]="pnlColor(pos.unrealizedPnl)">
                      {{ formatPnl(pos.unrealizedPnl) }}
                    </span>
                  </td>
                  <td style="text-align:right">
                    <span class="resolution-badge {{ pos.resolutionStatus | lowercase }}">
                      {{ pos.resolutionStatus }}
                    </span>
                  </td>
                  <td style="text-align:right">
                    @if (pos.resolutionStatus === 'UNRESOLVED') {
                      <p-button
                        label="Close"
                        size="small"
                        severity="danger"
                        [text]="true"
                        [loading]="!!closingPosition()[pos.id]"
                        pTooltip="Close full position"
                        (onClick)="closePosition(pos)" />
                    }
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
    </div>

  }<!-- /live tab -->

  <!-- ════════════════════ PAPER TAB ════════════════════ -->
  @if (tab() === 'paper') {

    @if (loadingPaper()) {
      <div style="padding:48px;text-align:center"><p-skeleton height="200px" /></div>
    } @else if (paper(); as p) {

      <!-- Summary -->
      <div class="portfolio-summary-row" style="margin-bottom:24px">
        <div class="summary-card">
          <span class="summary-label">Paper P&L</span>
          <span class="summary-value pf-mono" [style.color]="pnlColor(p.pnl)">{{ formatPnl(p.pnl) }}</span>
        </div>
        <div class="summary-card">
          <span class="summary-label">Positions</span>
          <span class="summary-value pf-mono">{{ p.positions.length }}</span>
        </div>
        <div class="summary-card">
          <span class="summary-label">Total Orders</span>
          <span class="summary-value pf-mono">{{ p.orderCount }}</span>
        </div>
        <div class="summary-card" style="justify-content:flex-end">
          <p-button
            label="Reset Paper Account"
            icon="pi pi-refresh"
            severity="danger"
            [text]="true"
            size="small"
            [loading]="resettingPaper()"
            (onClick)="resetPaper()" />
        </div>
      </div>

      <!-- Paper positions -->
      @if (p.positions.length === 0) {
        <div class="pf-empty-state">
          <i class="pi pi-file pf-empty-icon"></i>
          <p class="pf-empty-title">No paper positions</p>
          <p class="pf-empty-desc">Start a strategy in Paper mode to simulate trades.</p>
        </div>
      } @else {
        <div class="portfolio-table-panel">
          <div class="panel-header"><span class="panel-title">Paper Positions</span></div>
          <div class="table-scroll">
            <table class="data-table">
              <thead>
                <tr>
                  <th class="pf-col-label">Token</th>
                  <th class="pf-col-label">Side</th>
                  <th class="pf-col-label" style="text-align:right">Size</th>
                  <th class="pf-col-label" style="text-align:right">Unreal. P&L</th>
                </tr>
              </thead>
              <tbody>
                @for (pos of p.positions; track pos.tokenId) {
                  <tr class="table-row">
                    <td><span class="pf-mono" style="font-size:12px;color:var(--pf-text-secondary)">{{ pos.tokenId }}</span></td>
                    <td><span class="outcome-badge {{ pos.side | lowercase }}">{{ pos.side }}</span></td>
                    <td style="text-align:right"><span class="pf-mono">{{ pos.size | number:'1.0-0' }}</span></td>
                    <td style="text-align:right">
                      <span class="pf-mono" [style.color]="pnlColor(pos.unrealizedPnl)">
                        {{ formatPnl(pos.unrealizedPnl) }}
                      </span>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        </div>
      }
    }

  }<!-- /paper tab -->

</div>

// apps/user-app/src/pages/portfolio/portfolio.tsx
import { useState, useEffect, useCallback } from 'react';
import {
  AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer,
} from 'recharts';
import {
  Wallet, BarChart3,
  RefreshCw, Loader2, AlertTriangle, Fuel,
} from 'lucide-react';
import { toast } from 'sonner';

/* ─── Types ──────────────────────────────────────────────────────────── */

interface Position {
  id: string;
  tokenId: string;
  marketTitle: string;
  side: string;
  size: string;
  avgEntryPrice: string;
  currentPrice: string;
  unrealizedPnl: string;
  resolutionStatus: string;
}

interface PortfolioResponse {
  totalUnrealizedPnl: string;
  totalRealizedPnl: string;
  positions: Position[];
}

interface PnlSnapshot {
  time: string;
  pnl: string;
}

interface PnlResponse {
  totalPnl: string;
  winRate: string;
  snapshots: PnlSnapshot[];
}

interface PaperPosition {
  tokenId: string;
  side: string;
  size: string;
  unrealizedPnl: string;
}

interface PaperSummary {
  pnl: string;
  positions: PaperPosition[];
  orderCount: number;
}

type Tab = 'live' | 'paper';
type Period = '7d' | '30d' | '90d' | 'allTime';

/* ─── Helpers ────────────────────────────────────────────────────────── */

const PERIODS: { label: string; value: Period }[] = [
  { label: '7d', value: '7d' },
  { label: '30d', value: '30d' },
  { label: '90d', value: '90d' },
  { label: 'All', value: 'allTime' },
];

function pnlColor(val: string): string {
  const n = parseFloat(val);
  if (n > 0) return 'text-pf-success';
  if (n < 0) return 'text-pf-danger';
  return 'text-pf-text-muted';
}

function pnlBorderColor(val: string): string {
  const n = parseFloat(val);
  if (n > 0) return 'border-l-pf-success';
  if (n < 0) return 'border-l-pf-danger';
  return 'border-l-pf-text-muted';
}

function formatPnl(val: string): string {
  const n = parseFloat(val);
  return `${n >= 0 ? '+' : ''}$${Math.abs(n).toFixed(2)}`;
}

function winRatePct(val: string): string {
  return `${(parseFloat(val) * 100).toFixed(1)}%`;
}

/* ─── Skeleton ───────────────────────────────────────────────────────── */

function CardSkeleton() {
  return <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4 animate-pulse h-20" />;
}

function TableSkeleton() {
  return (
    <div className="space-y-2 p-4">
      {[1, 2, 3].map(i => (
        <div key={i} className="h-10 bg-pf-overlay rounded animate-pulse" />
      ))}
    </div>
  );
}

/* ─── Component ──────────────────────────────────────────────────────── */

export function Component() {
  // Read CSS variables for Recharts (which needs raw color strings)
  const styles = typeof window !== 'undefined' ? getComputedStyle(document.documentElement) : null;
  const textMuted = styles?.getPropertyValue('--color-pf-text-muted').trim() || '#445E7A';
  const bgElevated = styles?.getPropertyValue('--color-pf-elevated').trim() || '#111D2E';
  const borderColor = styles?.getPropertyValue('--color-pf-border').trim() || '#1E3350';
  const textPrimary = styles?.getPropertyValue('--color-pf-text').trim() || '#E8EDF5';

  const [tab, setTab] = useState<Tab>('live');
  const [period, setPeriodState] = useState<Period>('7d');

  const [portfolio, setPortfolio] = useState<PortfolioResponse | null>(null);
  const [pnl, setPnl] = useState<PnlResponse | null>(null);
  const [paper, setPaper] = useState<PaperSummary | null>(null);

  const [loadingPortfolio, setLoadingPortfolio] = useState(true);
  const [loadingChart, setLoadingChart] = useState(true);
  const [loadingPaper, setLoadingPaper] = useState(false);
  const [closingPosition, setClosingPosition] = useState<Record<string, boolean>>({});
  const [resettingPaper, setResettingPaper] = useState(false);

  const loadPortfolio = useCallback(async () => {
    setLoadingPortfolio(true);
    try {
      const res = await fetch('/api/v1/portfolio', { credentials: 'include' });
      if (res.ok) setPortfolio(await res.json());
    } catch { toast.error('Failed to load data'); }
    setLoadingPortfolio(false);
  }, []);

  const loadChart = useCallback(async (p: Period) => {
    setLoadingChart(true);
    try {
      const res = await fetch(`/api/v1/portfolio/pnl?period=${p}`, { credentials: 'include' });
      if (res.ok) setPnl(await res.json());
    } catch { toast.error('Failed to load data'); }
    setLoadingChart(false);
  }, []);

  const loadPaper = useCallback(async () => {
    setLoadingPaper(true);
    try {
      const res = await fetch('/api/v1/paper/summary', { credentials: 'include' });
      if (res.ok) setPaper(await res.json());
    } catch { toast.error('Failed to load data'); }
    setLoadingPaper(false);
  }, []);

  useEffect(() => {
    let cancelled = false;
    if (!cancelled) {
      loadPortfolio();
      loadChart(period);
    }
    return () => { cancelled = true; };
  }, [loadPortfolio, loadChart, period]);

  function setPeriod(p: Period) {
    setPeriodState(p);
    loadChart(p);
  }

  function handleTabChange(t: Tab) {
    setTab(t);
    if (t === 'paper' && !paper) loadPaper();
  }

  async function closePosition(pos: Position) {
    setClosingPosition(prev => ({ ...prev, [pos.id]: true }));
    try {
      const res = await fetch('/api/v1/orders/close-position', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ tokenId: pos.tokenId }),
      });
      if (res.ok) loadPortfolio();
    } catch { toast.error('Failed to close position'); }
    setClosingPosition(prev => ({ ...prev, [pos.id]: false }));
  }

  async function resetPaper() {
    if (!confirm('This will delete all paper positions and orders. This cannot be undone.')) return;
    setResettingPaper(true);
    try {
      const res = await fetch('/api/v1/paper/reset', { method: 'POST', credentials: 'include' });
      if (res.ok) setPaper({ pnl: '0', positions: [], orderCount: 0 });
    } catch { toast.error('Failed to reset paper account'); }
    setResettingPaper(false);
  }

  // Chart data
  const chartData = (pnl?.snapshots ?? []).map(s => ({
    time: new Date(s.time).toLocaleDateString([], { month: 'short', day: 'numeric' }),
    pnl: parseFloat(s.pnl),
  }));
  const isProfitable = parseFloat(pnl?.totalPnl ?? '0') >= 0;
  const chartColorResolved = isProfitable
    ? (styles?.getPropertyValue('--color-pf-success').trim() || '#10B981')
    : (styles?.getPropertyValue('--color-pf-danger').trim() || '#EF4444');
  const chartColor = chartColorResolved;

  return (
    <div className="animate-fade-in p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-semibold text-pf-text">Portfolio</h1>
          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-pf-success/10 text-pf-success text-xs font-medium border border-pf-success/20">
            <Fuel className="size-3" />
            Gasless
          </span>
        </div>
        <div className="flex bg-pf-surface rounded-pf border border-pf-border-subtle">
          <button
            onClick={() => handleTabChange('live')}
            className={`px-4 py-1.5 text-sm font-medium rounded-pf transition-colors ${
              tab === 'live' ? 'bg-pf-elevated text-pf-text' : 'text-pf-text-secondary hover:text-pf-text'
            }`}
          >
            Live
          </button>
          <button
            onClick={() => handleTabChange('paper')}
            className={`px-4 py-1.5 text-sm font-medium rounded-pf transition-colors ${
              tab === 'paper' ? 'bg-pf-elevated text-pf-text' : 'text-pf-text-secondary hover:text-pf-text'
            }`}
          >
            Paper
          </button>
        </div>
      </div>

      {/* ═══ LIVE TAB ═══ */}
      {tab === 'live' && (
        <>
          {/* Summary cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {loadingPortfolio ? (
              [1, 2, 3, 4].map(i => <CardSkeleton key={i} />)
            ) : portfolio ? (
              <>
                <div className={`bg-pf-elevated border border-pf-border rounded-pf-lg p-4 border-l-4 ${pnlBorderColor(portfolio.totalUnrealizedPnl)}`}>
                  <span className="text-xs text-pf-text-secondary uppercase tracking-wider">Unrealized P&L</span>
                  <span className={`block mt-1 text-xl font-mono font-semibold ${pnlColor(portfolio.totalUnrealizedPnl)}`}>
                    {formatPnl(portfolio.totalUnrealizedPnl)}
                  </span>
                </div>
                <div className={`bg-pf-elevated border border-pf-border rounded-pf-lg p-4 border-l-4 ${pnlBorderColor(portfolio.totalRealizedPnl)}`}>
                  <span className="text-xs text-pf-text-secondary uppercase tracking-wider">Realized P&L</span>
                  <span className={`block mt-1 text-xl font-mono font-semibold ${pnlColor(portfolio.totalRealizedPnl)}`}>
                    {formatPnl(portfolio.totalRealizedPnl)}
                  </span>
                </div>
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4 border-l-4 border-l-cyan-500">
                  <span className="text-xs text-pf-text-secondary uppercase tracking-wider">Win Rate</span>
                  <span className="block mt-1 text-xl font-mono font-semibold text-pf-cyan-400">
                    {winRatePct(pnl?.winRate ?? '0')}
                  </span>
                </div>
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4 border-l-4 border-l-pf-text">
                  <span className="text-xs text-pf-text-secondary uppercase tracking-wider">Open Positions</span>
                  <span className="block mt-1 text-xl font-mono font-semibold text-pf-text">
                    {portfolio.positions.length}
                  </span>
                </div>
              </>
            ) : (
              <div className="col-span-full bg-pf-elevated border border-pf-danger/20 rounded-pf-lg p-6 text-center">
                <AlertTriangle className="mx-auto mb-3 text-pf-danger opacity-60" size={32} />
                <p className="text-sm font-medium text-pf-text mb-1">Failed to load portfolio</p>
                <p className="text-xs text-pf-text-muted mb-4">Something went wrong while fetching your data.</p>
                <button
                  onClick={loadPortfolio}
                  className="px-4 py-2 rounded-pf bg-pf-cyan-500 text-black text-sm font-medium hover:bg-pf-cyan-400 transition-colors"
                >
                  Retry
                </button>
              </div>
            )}
          </div>

          {/* P&L Chart */}
          <div className="bg-pf-elevated border border-pf-border rounded-pf-lg">
            <div className="flex items-center justify-between px-4 py-3 border-b border-pf-border-subtle">
              <span className="text-sm font-medium text-pf-text">P&L Over Time</span>
              <div className="flex gap-1">
                {PERIODS.map(p => (
                  <button
                    key={p.value}
                    onClick={() => setPeriod(p.value)}
                    className={`px-2.5 py-1 text-xs font-medium rounded-pf transition-colors ${
                      period === p.value
                        ? 'bg-pf-cyan-500/15 text-pf-cyan-400'
                        : 'text-pf-text-secondary hover:text-pf-text'
                    }`}
                  >
                    {p.label}
                  </button>
                ))}
              </div>
            </div>
            {loadingChart ? (
              <div className="h-64 animate-pulse bg-pf-overlay m-4 rounded" />
            ) : chartData.length > 0 ? (
              <div className="h-64 px-2 py-4">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={chartData}>
                    <defs>
                      <linearGradient id="pnlGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor={chartColor} stopOpacity={0.15} />
                        <stop offset="100%" stopColor={chartColor} stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <XAxis
                      dataKey="time" tick={{ fill: textMuted, fontSize: 10, fontFamily: "'JetBrains Mono', monospace" }}
                      axisLine={false} tickLine={false}
                    />
                    <YAxis
                      tick={{ fill: textMuted, fontSize: 10, fontFamily: "'JetBrains Mono', monospace" }}
                      axisLine={false} tickLine={false} tickFormatter={v => `$${v}`}
                    />
                    <Tooltip
                      contentStyle={{
                        background: bgElevated, border: `1px solid ${borderColor}`, borderRadius: 6,
                        fontFamily: "'JetBrains Mono', monospace", fontSize: 12,
                      }}
                      labelStyle={{ color: textPrimary }}
                      formatter={(value: number) => [`${value >= 0 ? '+' : ''}$${value.toFixed(2)}`, 'P&L']}
                    />
                    <Area
                      type="monotone" dataKey="pnl" stroke={chartColor} strokeWidth={1.5}
                      fill="url(#pnlGradient)" dot={false}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <BarChart3 className="size-10 text-pf-text-muted mb-3" />
                <p className="text-sm font-medium text-pf-text">No P&L data yet</p>
                <p className="text-xs text-pf-text-muted mt-1">P&L data will appear once your strategies generate trades.</p>
              </div>
            )}
          </div>

          {/* Positions table */}
          <div className="bg-pf-elevated border border-pf-border rounded-pf-lg">
            <div className="px-4 py-3 border-b border-pf-border-subtle">
              <span className="text-sm font-medium text-pf-text">Open Positions</span>
            </div>
            {loadingPortfolio ? (
              <TableSkeleton />
            ) : (portfolio?.positions ?? []).length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <Wallet className="size-10 text-pf-text-muted mb-3" />
                <p className="text-sm font-medium text-pf-text">No open positions</p>
                <p className="text-xs text-pf-text-muted mt-1">Start a strategy to build positions.</p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-pf-surface text-left text-xs text-pf-text-secondary uppercase tracking-wider">
                      <th className="px-4 py-3 font-medium">Market</th>
                      <th className="px-4 py-3 font-medium">Side</th>
                      <th className="px-4 py-3 font-medium text-right">Size</th>
                      <th className="px-4 py-3 font-medium text-right">Avg Entry</th>
                      <th className="px-4 py-3 font-medium text-right">Current</th>
                      <th className="px-4 py-3 font-medium text-right">Unreal. P&L</th>
                      <th className="px-4 py-3 font-medium text-right">Status</th>
                      <th className="px-4 py-3 font-medium" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-pf-border-subtle">
                    {portfolio!.positions.map(pos => (
                      <tr key={pos.id} className="hover:bg-pf-surface/50 transition-colors">
                        <td className="px-4 py-3 max-w-[200px]">
                          <span className="text-pf-text line-clamp-1" title={pos.marketTitle}>{pos.marketTitle}</span>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${
                            pos.side === 'BUY' ? 'bg-pf-success/10 text-pf-success' : 'bg-pf-danger/10 text-pf-danger'
                          }`}>
                            {pos.side}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-pf-text">
                          {parseFloat(pos.size).toLocaleString()}
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-pf-text">
                          {parseFloat(pos.avgEntryPrice).toFixed(3)}
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-pf-cyan-400">
                          {pos.currentPrice && pos.currentPrice !== '0' ? `$${parseFloat(pos.currentPrice).toFixed(3)}` : <span className="text-pf-text-muted">N/A</span>}
                        </td>
                        <td className={`px-4 py-3 text-right font-mono ${pnlColor(pos.unrealizedPnl)}`}>
                          {formatPnl(pos.unrealizedPnl)}
                        </td>
                        <td className="px-4 py-3 text-right">
                          <span className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${
                            pos.resolutionStatus === 'UNRESOLVED'
                              ? 'bg-pf-cyan-500/10 text-pf-cyan-400'
                              : 'bg-pf-overlay text-pf-text-muted'
                          }`}>
                            {pos.resolutionStatus}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-right">
                          {pos.resolutionStatus === 'UNRESOLVED' && (
                            <button
                              onClick={() => closePosition(pos)}
                              disabled={closingPosition[pos.id]}
                              className="text-xs text-pf-danger hover:text-pf-danger disabled:opacity-50 transition-colors"
                            >
                              {closingPosition[pos.id] ? <Loader2 className="size-3 animate-spin" /> : 'Close'}
                            </button>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </>
      )}

      {/* ═══ PAPER TAB ═══ */}
      {tab === 'paper' && (
        <>
          {loadingPaper ? (
            <div className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                {[1, 2, 3].map(i => <CardSkeleton key={i} />)}
              </div>
              <TableSkeleton />
            </div>
          ) : paper ? (
            <>
              {/* Paper summary */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4">
                  <span className="text-xs text-pf-text-secondary uppercase tracking-wider">Paper P&L</span>
                  <span className={`block mt-1 text-xl font-mono font-semibold ${pnlColor(paper.pnl)}`}>
                    {formatPnl(paper.pnl)}
                  </span>
                </div>
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4">
                  <span className="text-xs text-pf-text-secondary uppercase tracking-wider">Positions</span>
                  <span className="block mt-1 text-xl font-mono font-semibold text-pf-text">{paper.positions.length}</span>
                </div>
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4">
                  <span className="text-xs text-pf-text-secondary uppercase tracking-wider">Total Orders</span>
                  <span className="block mt-1 text-xl font-mono font-semibold text-pf-text">{paper.orderCount}</span>
                </div>
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4 flex items-end justify-end">
                  <button
                    onClick={resetPaper}
                    disabled={resettingPaper}
                    className="flex items-center gap-1.5 text-xs text-pf-danger hover:text-pf-danger disabled:opacity-50 transition-colors"
                  >
                    <RefreshCw className={`size-3.5 ${resettingPaper ? 'animate-spin' : ''}`} />
                    Reset Paper Account
                  </button>
                </div>
              </div>

              {/* Paper positions */}
              {paper.positions.length === 0 ? (
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg">
                  <div className="flex flex-col items-center justify-center py-16 text-center">
                    <Wallet className="size-10 text-pf-text-muted mb-3" />
                    <p className="text-sm font-medium text-pf-text">No paper positions</p>
                    <p className="text-xs text-pf-text-muted mt-1">Start a strategy in Paper mode to simulate trades.</p>
                  </div>
                </div>
              ) : (
                <div className="bg-pf-elevated border border-pf-border rounded-pf-lg">
                  <div className="px-4 py-3 border-b border-pf-border-subtle">
                    <span className="text-sm font-medium text-pf-text">Paper Positions</span>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="bg-pf-surface text-left text-xs text-pf-text-secondary uppercase tracking-wider">
                          <th className="px-4 py-3 font-medium">Token</th>
                          <th className="px-4 py-3 font-medium">Side</th>
                          <th className="px-4 py-3 font-medium text-right">Size</th>
                          <th className="px-4 py-3 font-medium text-right">Unreal. P&L</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-pf-border-subtle">
                        {paper.positions.map(pos => (
                          <tr key={pos.tokenId} className="hover:bg-pf-surface/50 transition-colors">
                            <td className="px-4 py-3">
                              <span className="font-mono text-xs text-pf-text-secondary">{pos.tokenId}</span>
                            </td>
                            <td className="px-4 py-3">
                              <span className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${
                                pos.side === 'BUY' ? 'bg-pf-success/10 text-pf-success' : 'bg-pf-danger/10 text-pf-danger'
                              }`}>
                                {pos.side}
                              </span>
                            </td>
                            <td className="px-4 py-3 text-right font-mono text-pf-text">
                              {parseFloat(pos.size).toLocaleString()}
                            </td>
                            <td className={`px-4 py-3 text-right font-mono ${pnlColor(pos.unrealizedPnl)}`}>
                              {formatPnl(pos.unrealizedPnl)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </>
          ) : null}
        </>
      )}
    </div>
  );
}
