// apps/admin-app/src/app/features/backtests/backtests.component.ts
import { Component, OnInit, inject, signal, DestroyRef } from '@angular/core';
import { DatePipe, DecimalPipe } from '@angular/common';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ButtonModule } from 'primeng/button';
import { SkeletonModule } from 'primeng/skeleton';
import { ProgressBarModule } from 'primeng/progressbar';
import { AdminApiService } from '../../core/services/admin-api.service';
import { AdminBacktestView, BacktestStatus } from '../../core/models/admin.model';

@Component({
  selector: 'app-backtests',
  standalone: true,
  imports: [DatePipe, DecimalPipe, ButtonModule, SkeletonModule, ProgressBarModule],
  templateUrl: './backtests.component.html',
})
export class BacktestsComponent implements OnInit {
  private readonly api        = inject(AdminApiService);
  private readonly destroyRef = inject(DestroyRef);

  runs       = signal<AdminBacktestView[]>([]);
  loading    = signal(true);
  total      = signal(0);
  totalPages = signal(0);
  page       = signal(1);

  readonly skeletons = Array(10);

  ngOnInit(): void { this.load(); }

  load(): void {
    this.loading.set(true);
    this.api.backtests({ page: this.page(), limit: 20 })
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: res => { this.runs.set(res.data); this.total.set(res.total); this.totalPages.set(res.totalPages); this.loading.set(false); },
        error: () => this.loading.set(false),
      });
  }

  prevPage(): void { if (this.page() > 1) { this.page.update(p => p - 1); this.load(); } }
  nextPage(): void { if (this.page() < this.totalPages()) { this.page.update(p => p + 1); this.load(); } }

  statusColor(s: BacktestStatus): string {
    const m: Record<BacktestStatus, string> = { QUEUED: 'var(--pf-text-muted)', RUNNING: 'var(--pf-cyan-400)', COMPLETED: 'var(--pf-success)', FAILED: 'var(--pf-danger)', CANCELLED: 'var(--pf-text-muted)' };
    return m[s] ?? 'var(--pf-text-muted)';
  }

  statusBg(s: BacktestStatus): string {
    const m: Record<BacktestStatus, string> = { QUEUED: 'rgba(122,148,180,0.08)', RUNNING: 'rgba(6,182,212,0.1)', COMPLETED: 'rgba(16,185,129,0.1)', FAILED: 'rgba(239,68,68,0.1)', CANCELLED: 'rgba(122,148,180,0.08)' };
    return m[s] ?? 'transparent';
  }

  pnlColor(v: string | null): string {
    if (!v) return 'var(--pf-text-muted)';
    return parseFloat(v) >= 0 ? 'var(--pf-success)' : 'var(--pf-danger)';
  }
}

<div class="pf-page">
  <div class="page-header">
    <h1>Backtests</h1>
    @if (!loading()) { <span class="pf-mono" style="font-size:12px;color:var(--pf-text-muted)">{{ total() }} total</span> }
  </div>

  <div class="admin-table-panel">
    <div class="table-scroll">
      <table class="data-table">
        <thead>
          <tr>
            <th class="pf-col-label">User</th>
            <th class="pf-col-label">Strategy</th>
            <th class="pf-col-label">Status</th>
            <th class="pf-col-label" style="min-width:120px">Progress</th>
            <th class="pf-col-label" style="text-align:right">P&L</th>
            <th class="pf-col-label" style="text-align:right">Win Rate</th>
            <th class="pf-col-label" style="text-align:right">Created</th>
          </tr>
        </thead>
        <tbody>
          @if (loading()) {
            @for (s of skeletons; track $index) { <tr class="table-row">@for (c of [1,2,3,4,5,6,7]; track c) { <td><p-skeleton height="12px" /></td> }</tr> }
          } @else if (runs().length === 0) {
            <tr><td colspan="7"><div class="pf-empty-state" style="padding:40px"><i class="pi pi-history pf-empty-icon"></i><p class="pf-empty-title">No backtest runs</p></div></td></tr>
          } @else {
            @for (r of runs(); track r.id) {
              <tr class="table-row admin-table-row">
                <td><span class="pf-mono" style="font-size:12px">{{ r.username }}</span></td>
                <td><span style="font-size:12px;color:var(--pf-text-secondary)">{{ r.strategyName ?? '—' }}</span></td>
                <td><span class="order-status-badge" [style.color]="statusColor(r.status)" [style.background]="statusBg(r.status)">{{ r.status }}</span></td>
                <td>
                  @if (r.status === 'RUNNING') {
                    <div style="display:flex;align-items:center;gap:8px">
                      <p-progressbar [value]="r.progress" [showValue]="false" styleClass="backtest-row-progress" />
                      <span class="pf-mono" style="font-size:11px;color:var(--pf-cyan-400)">{{ r.progress }}%</span>
                    </div>
                  } @else if (r.status === 'COMPLETED') {
                    <span class="pf-mono" style="font-size:11px;color:var(--pf-success)">100%</span>
                  } @else { <span style="color:var(--pf-text-muted)">—</span> }
                </td>
                <td style="text-align:right"><span class="pf-mono" [style.color]="pnlColor(r.totalPnl)">{{ r.totalPnl ?? '—' }}</span></td>
                <td style="text-align:right"><span class="pf-mono" style="color:var(--pf-text-secondary)">{{ r.winRate ? (r.winRate | number:'1.0-1') + '%' : '—' }}</span></td>
                <td style="text-align:right"><span class="pf-mono" style="font-size:11px;color:var(--pf-text-muted)">{{ r.createdAt | date:'MMM d, HH:mm' }}</span></td>
              </tr>
            }
          }
        </tbody>
      </table>
    </div>
  </div>

  @if (totalPages() > 1) {
    <div class="markets-pagination">
      <p-button icon="pi pi-chevron-left"  severity="secondary" [text]="true" size="small" [disabled]="page() === 1"            (onClick)="prevPage()" />
      <span class="pf-mono" style="font-size:13px;color:var(--pf-text-secondary)">{{ page() }} / {{ totalPages() }}</span>
      <p-button icon="pi pi-chevron-right" severity="secondary" [text]="true" size="small" [disabled]="page() === totalPages()" (onClick)="nextPage()" />
    </div>
  }
</div>

// apps/admin-app/src/pages/backtests/backtests.tsx
import { useState, useEffect, useCallback } from 'react';
import { toast } from 'sonner';
import { ChevronLeft, ChevronRight, FlaskConical, XCircle, Loader2 } from 'lucide-react';
import { adminApi } from '@/lib/api';
import { statusColor, formatDateTime } from '@/lib/utils';

export function Component() {
  const [backtests, setBacktests] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [loading, setLoading] = useState(true);

  const [cancelling, setCancelling] = useState<Record<string, boolean>>({});

  const limit = 20;

  async function cancelBacktest(id: string) {
    setCancelling(prev => ({ ...prev, [id]: true }));
    try {
      await adminApi.cancelBacktest(id);
      toast.success('Backtest cancelled');
      load();
    } catch {
      toast.error('Failed to cancel backtest');
    }
    setCancelling(prev => ({ ...prev, [id]: false }));
  }

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await adminApi.backtests({ page, limit });
      setBacktests(res.data ?? []);
      setTotal(res.total ?? 0);
      setTotalPages(res.totalPages ?? 1);
    } catch {
      toast.error('Failed to load backtests');
    } finally {
      setLoading(false);
    }
  }, [page]);

  useEffect(() => {
    load();
  }, [load]);

  function getDuration(bt: any): string {
    if (!bt.createdAt) return '-';
    const start = new Date(bt.createdAt).getTime();
    const end = bt.completedAt ? new Date(bt.completedAt).getTime() : Date.now();
    const diffSec = Math.floor((end - start) / 1000);
    if (diffSec < 60) return `${diffSec}s`;
    const mins = Math.floor(diffSec / 60);
    const secs = diffSec % 60;
    return `${mins}m ${secs}s`;
  }

  return (
    <div className="animate-fade-in space-y-6">
      <h2 className="text-lg font-semibold text-[var(--color-pf-text)]">
        Backtests <span className="text-sm font-normal text-[var(--color-pf-text-tertiary)]">({total})</span>
      </h2>

      <div className="bg-[var(--color-pf-elevated)] border border-[var(--color-pf-border)] rounded-pf-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-[var(--color-pf-border)]">
                <th className="text-left px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">ID</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">User</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">Strategy</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">Status</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">Duration</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">P&L</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">Win Rate</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">Created</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                Array.from({ length: 3 }).map((_, i) => (
                  <tr key={i}>
                    {Array.from({ length: 9 }).map((_, j) => (
                      <td key={j} className="px-4 py-3">
                        <div className="h-4 bg-pf-surface rounded animate-pulse" />
                      </td>
                    ))}
                  </tr>
                ))
              ) : backtests.length === 0 ? (
                <tr>
                  <td colSpan={9} className="text-center py-12">
                    <FlaskConical className="mx-auto mb-3 text-[var(--color-pf-text-tertiary)] opacity-40" size={40} />
                    <p className="text-[var(--color-pf-text-secondary)] font-medium">No backtests found</p>
                    <p className="text-[var(--color-pf-text-tertiary)] text-xs mt-1">Backtest runs will appear here</p>
                  </td>
                </tr>
              ) : (
                backtests.map((bt) => (
                  <tr key={bt.id} className="border-b border-[var(--color-pf-border)] last:border-0 hover:bg-[var(--color-pf-bg)] transition-colors">
                    <td className="px-4 py-3 font-mono text-xs text-[var(--color-pf-text-secondary)]">{bt.id.slice(0, 8)}</td>
                    <td className="px-4 py-3 text-[var(--color-pf-text)]">{bt.username}</td>
                    <td className="px-4 py-3 text-[var(--color-pf-text-secondary)]">{bt.strategyName ?? '-'}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusColor(bt.status ?? 'UNKNOWN')}`}>
                        {bt.status ?? 'UNKNOWN'}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-[var(--color-pf-text-secondary)]">{getDuration(bt)}</td>
                    <td className="px-4 py-3 text-right">
                      {bt.totalPnl != null ? (
                        <span className={parseFloat(bt.totalPnl) >= 0 ? 'text-pf-success' : 'text-pf-danger'}>
                          {parseFloat(bt.totalPnl) >= 0 ? '+' : ''}{bt.totalPnl}
                        </span>
                      ) : (
                        <span className="text-[var(--color-pf-text-tertiary)]">-</span>
                      )}
                    </td>
                    <td className="px-4 py-3 text-right text-[var(--color-pf-text-secondary)]">
                      {bt.winRate != null ? `${bt.winRate}%` : '-'}
                    </td>
                    <td className="px-4 py-3 text-[var(--color-pf-text-tertiary)]">{formatDateTime(bt.createdAt)}</td>
                    <td className="px-4 py-3 text-right">
                      {(bt.status === 'RUNNING' || bt.status === 'PENDING' || bt.status === 'QUEUED') && (
                        <button
                          onClick={() => cancelBacktest(bt.id)}
                          disabled={cancelling[bt.id]}
                          aria-label={`Cancel backtest ${bt.id.slice(0, 8)}`}
                          className="inline-flex items-center gap-1 text-xs text-pf-danger hover:text-pf-danger disabled:opacity-50 cursor-pointer transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-pf-danger)] rounded"
                        >
                          {cancelling[bt.id] ? <Loader2 size={12} className="animate-spin" /> : <XCircle size={12} />}
                          Cancel
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-[var(--color-pf-border)]">
            <span className="text-xs text-[var(--color-pf-text-tertiary)]">Page {page} of {totalPages}</span>
            <div className="flex items-center gap-2">
              <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1} aria-label="Previous page" className="p-1.5 rounded hover:bg-[var(--color-pf-bg)] text-[var(--color-pf-text-secondary)] disabled:opacity-30 disabled:cursor-not-allowed focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-pf-cyan-500)]">
                <ChevronLeft size={16} />
              </button>
              <button onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page === totalPages} aria-label="Next page" className="p-1.5 rounded hover:bg-[var(--color-pf-bg)] text-[var(--color-pf-text-secondary)] disabled:opacity-30 disabled:cursor-not-allowed focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-pf-cyan-500)]">
                <ChevronRight size={16} />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
