// apps/user-app/src/app/features/auth/forgot-password/forgot-password.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { MessageModule } from 'primeng/message';
import { CardModule } from 'primeng/card';
import { AuthApiService } from '../../../core/services/auth-api.service';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, ButtonModule, InputTextModule, MessageModule, CardModule],
  template: `
    <div class="auth-page">
      <div class="auth-card">
        <div class="auth-logo">
          <i class="pi pi-bolt logo-icon"></i>
          <span class="logo-text">Polyforge</span>
        </div>

        <p-card>
          @if (!sent()) {
            <h2>Reset password</h2>
            <p class="auth-subtitle">We'll send you a reset link.</p>

            <form [formGroup]="form" (ngSubmit)="submit()">
              <div class="form-field">
                <label class="field-label" for="email">Email</label>
                <input pInputText id="email" type="email" formControlName="email"
                       placeholder="you@example.com" class="w-full" />
                @if (form.get('email')?.invalid && form.get('email')?.touched) {
                  <small class="field-error">Enter a valid email address</small>
                }
              </div>

              <p-button type="submit" label="Send reset link" styleClass="w-full"
                        [loading]="loading()" [disabled]="loading()" />
            </form>
          } @else {
            <div style="text-align:center">
              <i class="pi pi-send" style="font-size:3rem;color:var(--p-primary-400);margin-bottom:1rem;display:block"></i>
              <h2>Check your inbox</h2>
              <p class="text-muted">
                If an account with that email exists, we've sent a reset link.
              </p>
            </div>
          }

          <div class="auth-footer" style="margin-top:1rem">
            <a [routerLink]="'/login'">Back to login</a>
          </div>
        </p-card>
      </div>
    </div>
  `,
})
export class ForgotPasswordComponent {
  private readonly fb      = inject(FormBuilder);
  private readonly authApi = inject(AuthApiService);

  readonly loading = signal(false);
  readonly sent    = signal(false);

  readonly form = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
  });

  submit(): void {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true);
    this.authApi.forgotPassword(this.form.value.email!).subscribe({
      next: () => { this.loading.set(false); this.sent.set(true); },
      error: () => { this.loading.set(false); this.sent.set(true); }, // always 200 per spec
    });
  }
}

// apps/user-app-react/src/pages/auth/forgot-password.tsx
import { useState, type FormEvent } from 'react';
import { Link } from 'react-router';
import { Mail, ArrowLeft, Check } from 'lucide-react';

export function Component() {
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);
  const [touched, setTouched] = useState(false);

  const emailError = touched && !email ? 'Email is required'
    : touched && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? 'Enter a valid email address'
    : '';

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setTouched(true);
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return;

    setLoading(true);
    try {
      await fetch('/auth/v1/forgot-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ email }),
      });
    } catch {
      // always show success per spec
    } finally {
      setLoading(false);
      setSent(true);
    }
  }

  return (
    <div className="flex items-center justify-center min-h-screen bg-pf-base">
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-pf-cyan-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="relative w-full max-w-md px-4">
        {/* Logo */}
        <div className="flex items-center justify-center gap-2 mb-8">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path d="M12 2L20.66 7V17L12 22L3.34 17V7L12 2Z" stroke="#06b6d4" strokeWidth="1.2" fill="none" opacity="0.4"/>
            <path d="M13 5L7.5 13H11L10 19L16.5 11H13L13 5Z" fill="#06b6d4"/>
          </svg>
          <span className="text-xl font-semibold text-pf-text">Polyforge</span>
        </div>

        {/* Card */}
        <div className="bg-pf-elevated border border-pf-border rounded-xl p-8">
          {!sent ? (
            <>
              <h2 className="text-xl font-semibold text-pf-text mb-1">Reset password</h2>
              <p className="text-sm text-pf-text-muted mb-6">We&apos;ll send you a reset link.</p>

              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-pf-text mb-1.5">Email</label>
                  <div className="relative">
                    <Mail className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-pf-text-muted" />
                    <input
                      id="email"
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      onBlur={() => setTouched(true)}
                      placeholder="you@example.com"
                      className="w-full pl-10 pr-4 py-2.5 bg-pf-base border border-pf-border rounded-lg text-pf-text placeholder:text-pf-text-muted/50 focus:outline-none focus:ring-2 focus:ring-pf-cyan-500/40 focus:border-pf-cyan-500 transition-colors"
                    />
                  </div>
                  {emailError && <p className="mt-1 text-xs text-red-400">{emailError}</p>}
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full py-2.5 bg-pf-cyan-500 text-pf-base font-semibold rounded-lg hover:bg-pf-cyan-400 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  {loading ? 'Sending...' : 'Send reset link'}
                </button>
              </form>
            </>
          ) : (
            <div className="text-center">
              <div className="size-16 rounded-full bg-pf-cyan-500/10 flex items-center justify-center mx-auto mb-4">
                <Check className="size-8 text-pf-cyan-500" />
              </div>
              <h2 className="text-xl font-semibold text-pf-text mb-2">Check your inbox</h2>
              <p className="text-sm text-pf-text-muted">
                If an account with that email exists, we&apos;ve sent a reset link.
              </p>
            </div>
          )}

          <div className="border-t border-pf-border mt-6 pt-4 text-center text-sm">
            <Link to="/login" className="inline-flex items-center gap-1.5 text-pf-cyan-500 hover:text-pf-cyan-400 transition-colors">
              <ArrowLeft className="size-4" />
              Back to login
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
