// apps/admin-app/src/pages/users/user-detail.tsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router';
import { toast } from 'sonner';
import { ArrowLeft, Ban, CheckCircle, Key, Trash2 } from 'lucide-react';
import { adminApi } from '@/lib/api';
import { statusColor, formatDate, formatDateTime } from '@/lib/utils';

export function Component() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [user, setUser] = useState<any>(null);
  const [apiKeys, setApiKeys] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showSuspendDialog, setShowSuspendDialog] = useState(false);
  const [suspendReason, setSuspendReason] = useState('');
  const [actionLoading, setActionLoading] = useState(false);

  useEffect(() => {
    if (!id) return;
    async function load() {
      try {
        const [userRes, keysRes] = await Promise.all([
          adminApi.user(id!),
          adminApi.userApiKeys(id!),
        ]);
        setUser(userRes);
        setApiKeys(keysRes?.data ?? []);
      } catch {
        toast.error('Failed to load user');
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [id]);

  async function handleSuspend() {
    if (!id || !suspendReason.trim()) return;
    setActionLoading(true);
    try {
      await adminApi.suspendUser(id, suspendReason);
      setUser((u: any) => ({ ...u, suspended: true, suspendReason }));
      setShowSuspendDialog(false);
      setSuspendReason('');
      toast.success('User suspended');
    } catch {
      toast.error('Failed to suspend user');
    } finally {
      setActionLoading(false);
    }
  }

  async function handleUnsuspend() {
    if (!id) return;
    setActionLoading(true);
    try {
      await adminApi.unsuspendUser(id);
      setUser((u: any) => ({ ...u, suspended: false, suspendReason: null }));
      toast.success('User unsuspended');
    } catch {
      toast.error('Failed to unsuspend user');
    } finally {
      setActionLoading(false);
    }
  }

  const [confirmRevokeKeyId, setConfirmRevokeKeyId] = useState<string | null>(null);

  async function revokeKey(keyId: string) {
    if (!id) return;
    setConfirmRevokeKeyId(null);
    try {
      await adminApi.revokeUserApiKey(id, keyId);
      setApiKeys((keys) => keys.map((k) => (k.id === keyId ? { ...k, revoked: true } : k)));
      toast.success('API key revoked');
    } catch {
      toast.error('Failed to revoke key');
    }
  }

  if (loading) {
    return (
      <div className="animate-pulse space-y-6">
        <div className="h-4 bg-[var(--color-pf-elevated)] rounded w-32" />
        <div className="bg-[var(--color-pf-elevated)] border border-[var(--color-pf-border)] rounded-pf-lg p-6 space-y-4">
          <div className="h-5 bg-[var(--color-pf-bg)] rounded w-48" />
          <div className="h-4 bg-[var(--color-pf-bg)] rounded w-64" />
          <div className="grid grid-cols-4 gap-4">
            {[1, 2, 3, 4].map(i => <div key={i} className="h-12 bg-[var(--color-pf-bg)] rounded" />)}
          </div>
        </div>
      </div>
    );
  }

  if (!user) {
    return (
      <div className="text-center py-12">
        <p className="text-[var(--color-pf-text-secondary)]">User not found</p>
        <button
          type="button"
          onClick={() => navigate('/users')}
          className="mt-4 text-sm text-[var(--color-pf-cyan-500)] hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-pf-cyan-500)] rounded"
        >
          Back to users
        </button>
      </div>
    );
  }

  return (
    <div className="animate-fade-in space-y-6">
      {/* Back */}
      <button
        type="button"
        onClick={() => navigate('/users')}
        className="flex items-center gap-1.5 text-sm text-[var(--color-pf-text-secondary)] hover:text-[var(--color-pf-text)] transition-colors cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-pf-cyan-500)] rounded-pf-sm"
      >
        <ArrowLeft size={16} aria-hidden="true" />
        Back to users
      </button>

      {/* User Info */}
      <div className="bg-[var(--color-pf-elevated)] border border-[var(--color-pf-border)] rounded-pf-lg p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-lg font-semibold text-[var(--color-pf-text)]">
              {user.username}
              {user.suspended && (
                <span className="ml-2 px-2 py-0.5 rounded text-xs font-medium text-pf-danger bg-pf-danger/10">
                  SUSPENDED
                </span>
              )}
            </h2>
            <p className="text-sm text-[var(--color-pf-text-secondary)] mt-0.5">{user.email}</p>
          </div>
          <span className={`px-2.5 py-1 rounded-full text-xs font-medium ${statusColor(user.status)}`}>
            {user.status}
          </span>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
          <div>
            <div className="text-[var(--color-pf-text-tertiary)] text-xs mb-0.5">Created</div>
            <div className="text-[var(--color-pf-text)]">{formatDate(user.createdAt)}</div>
          </div>
          <div>
            <div className="text-[var(--color-pf-text-tertiary)] text-xs mb-0.5">Last Seen</div>
            <div className="text-[var(--color-pf-text)]">{formatDateTime(user.lastSeen)}</div>
          </div>
          <div>
            <div className="text-[var(--color-pf-text-tertiary)] text-xs mb-0.5">Strategies</div>
            <div className="text-[var(--color-pf-text)]">{user.strategyCount}</div>
          </div>
          <div>
            <div className="text-[var(--color-pf-text-tertiary)] text-xs mb-0.5">Orders</div>
            <div className="text-[var(--color-pf-text)]">{user.orderCount}</div>
          </div>
        </div>

        {user.limits && (
          <div className="mt-4 pt-4 border-t border-[var(--color-pf-border)]">
            <h3 className="text-xs font-semibold text-[var(--color-pf-text-tertiary)] uppercase tracking-wider mb-2">
              Limits
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
              <div>
                <div className="text-[var(--color-pf-text-tertiary)] text-xs">Max Strategies</div>
                <div className="text-[var(--color-pf-text)] font-medium">{user.limits.maxStrategies}</div>
              </div>
              <div>
                <div className="text-[var(--color-pf-text-tertiary)] text-xs">Orders/min</div>
                <div className="text-[var(--color-pf-text)] font-medium">{user.limits.maxOrdersPerMinute}</div>
              </div>
              <div>
                <div className="text-[var(--color-pf-text-tertiary)] text-xs">Max Position</div>
                <div className="text-[var(--color-pf-text)] font-medium">${user.limits.maxPositionSizeUsdc}</div>
              </div>
              <div>
                <div className="text-[var(--color-pf-text-tertiary)] text-xs">Daily Loss Limit</div>
                <div className="text-[var(--color-pf-text)] font-medium">${user.limits.maxDailyLossUsdc}</div>
              </div>
            </div>
          </div>
        )}

        {/* Actions */}
        <div className="mt-4 pt-4 border-t border-[var(--color-pf-border)] flex gap-3">
          {user.suspended ? (
            <button
             type="button"
              onClick={handleUnsuspend}
              disabled={actionLoading}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-pf-sm bg-pf-success/10 text-pf-success hover:bg-pf-success/20 disabled:opacity-50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pf-success"
            >
              <CheckCircle size={14} />
              Unsuspend
            </button>
          ) : (
            <button
             type="button"
              onClick={() => setShowSuspendDialog(true)}
              disabled={actionLoading}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-pf-sm bg-pf-danger/10 text-pf-danger hover:bg-pf-danger/20 disabled:opacity-50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pf-danger"
            >
              <Ban size={14} />
              Suspend
            </button>
          )}
        </div>

        {/* Suspend Dialog */}
        {showSuspendDialog && (
          <div className="mt-4 p-4 rounded-pf-sm border border-pf-danger/20 bg-pf-danger/5">
            <h4 className="text-sm font-medium text-pf-danger mb-2">Suspend User</h4>
            <label htmlFor="suspend-reason" className="sr-only">Reason for suspension</label>
            <textarea
              id="suspend-reason"
              value={suspendReason}
              onChange={(e) => setSuspendReason(e.target.value)}
              placeholder="Reason for suspension..."
              rows={3}
              className="w-full px-3 py-2 text-sm rounded-pf-sm border border-[var(--color-pf-border)] bg-[var(--color-pf-bg)] text-[var(--color-pf-text)] placeholder:text-[var(--color-pf-text-tertiary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-pf-danger)] mb-3"
            />
            <div className="flex gap-2">
              <button
               type="button"
                onClick={handleSuspend}
                disabled={actionLoading || !suspendReason.trim()}
                className="px-3 py-1.5 text-sm rounded-pf-sm bg-pf-danger text-white hover:bg-pf-danger/80 disabled:opacity-50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pf-danger"
              >
                Confirm Suspend
              </button>
              <button
               type="button"
                onClick={() => setShowSuspendDialog(false)}
                className="px-3 py-1.5 text-sm rounded-pf-sm border border-[var(--color-pf-border)] text-[var(--color-pf-text-secondary)] hover:bg-[var(--color-pf-bg)] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-pf-cyan-500)]"
              >
                Cancel
              </button>
            </div>
          </div>
        )}
      </div>

      {/* API Keys */}
      <div className="bg-[var(--color-pf-elevated)] border border-[var(--color-pf-border)] rounded-pf-lg p-5">
        <div className="flex items-center gap-2 mb-4">
          <Key size={16} className="text-[var(--color-pf-cyan-500)]" />
          <h3 className="text-sm font-semibold text-[var(--color-pf-text)]">API Keys</h3>
        </div>
        {apiKeys.length === 0 ? (
          <p className="text-sm text-[var(--color-pf-text-tertiary)]">No API keys</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <caption className="sr-only">User API keys</caption>
              <thead>
                <tr className="border-b border-[var(--color-pf-border)]">
                  <th scope="col" className="text-left px-3 py-2 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase">Name</th>
                  <th scope="col" className="text-left px-3 py-2 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase">Prefix</th>
                  <th scope="col" className="text-left px-3 py-2 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase">Scopes</th>
                  <th scope="col" className="text-left px-3 py-2 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase">Created</th>
                  <th scope="col" className="text-left px-3 py-2 text-xs font-medium text-[var(--color-pf-text-tertiary)] uppercase">Status</th>
                  <th scope="col" className="text-right px-3 py-2"><span className="sr-only">Actions</span></th>
                </tr>
              </thead>
              <tbody>
                {apiKeys.map((key) => (
                  <tr key={key.id} className="border-b border-[var(--color-pf-border)] last:border-0">
                    <td className="px-3 py-2.5 text-[var(--color-pf-text)]">{key.name}</td>
                    <td className="px-3 py-2.5 font-mono text-xs text-[var(--color-pf-text-secondary)]">
                      {key.prefix}...
                    </td>
                    <td className="px-3 py-2.5 text-[var(--color-pf-text-secondary)]">
                      {key.scopes.join(', ')}
                    </td>
                    <td className="px-3 py-2.5 text-[var(--color-pf-text-tertiary)]">
                      {formatDate(key.createdAt)}
                    </td>
                    <td className="px-3 py-2.5">
                      {key.revoked ? (
                        <span className="text-xs text-pf-danger">Revoked</span>
                      ) : (
                        <span className="text-xs text-pf-success">Active</span>
                      )}
                    </td>
                    <td className="px-3 py-2.5 text-right">
                      {!key.revoked && (
                        confirmRevokeKeyId === key.id ? (
                          <div className="flex items-center justify-end gap-1.5 text-xs">
                            <button type="button" onClick={() => revokeKey(key.id)} className="px-2 py-0.5 rounded bg-pf-danger/10 text-pf-danger hover:bg-pf-danger/20 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pf-danger">Revoke</button>
                            <button type="button" onClick={() => setConfirmRevokeKeyId(null)} className="px-2 py-0.5 rounded bg-[var(--color-pf-elevated)] text-[var(--color-pf-text-secondary)] hover:bg-[var(--color-pf-bg)] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-pf-cyan-500)]">Cancel</button>
                          </div>
                        ) : (
                          <button
                            type="button"
                            onClick={() => setConfirmRevokeKeyId(key.id)}
                            className="p-1 rounded hover:bg-pf-danger/10 text-[var(--color-pf-text-tertiary)] hover:text-pf-danger cursor-pointer transition-colors"
                            aria-label="Revoke key"
                            title="Revoke key"
                          >
                            <Trash2 size={14} />
                          </button>
                        )
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

// apps/admin-app/src/app/features/users/user-detail/user-detail.component.ts
import { Component, OnInit, inject, signal, DestroyRef } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { InputNumberModule } from 'primeng/inputnumber';
import { DialogModule } from 'primeng/dialog';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { SkeletonModule } from 'primeng/skeleton';
import { MessageService, ConfirmationService } from 'primeng/api';
import { ToastModule } from 'primeng/toast';
import { AdminApiService } from '../../../core/services/admin-api.service';
import { AdminUserDetail, AdminApiKey } from '../../../core/models/admin.model';
import { AdminAuthStore } from '../../../core/store/admin-auth.store';

@Component({
  selector: 'app-user-detail',
  standalone: true,
  imports: [RouterLink, FormsModule, DatePipe, ButtonModule, InputTextModule, InputNumberModule, DialogModule, ConfirmDialogModule, SkeletonModule, ToastModule],
  providers: [MessageService, ConfirmationService],
  templateUrl: './user-detail.component.html',
})
export class UserDetailComponent implements OnInit {
  private readonly api        = inject(AdminApiService);
  private readonly route      = inject(ActivatedRoute);
  private readonly toast      = inject(MessageService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly confirmSvc = inject(ConfirmationService);
  readonly auth               = inject(AdminAuthStore);

  user    = signal<AdminUserDetail | null>(null);
  loading = signal(true);

  showSuspendDialog = signal(false);
  suspendReason     = '';
  suspending        = signal(false);

  showLimitsDialog  = signal(false);
  limitsForm = {
    maxStrategies:       0,
    maxOrdersPerMinute:  0,
    maxPositionSizeUsdc: 0,
    maxDailyLossUsdc:    0,
  };
  limitsSaving = signal(false);

  // ─── API Keys ────────────────────────────────────────────────────────────────
  userApiKeys       = signal<AdminApiKey[]>([]);
  apiKeysLoading    = signal(false);

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id')!;
    this.api.user(id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: u => { this.user.set(u); this.limitsForm = { ...u.limits }; this.loading.set(false); this.loadApiKeys(u.id); },
        error: () => this.loading.set(false),
      });
  }

  loadApiKeys(userId: string): void {
    this.apiKeysLoading.set(true);
    this.api.userApiKeys(userId)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: keys => { this.userApiKeys.set(keys); this.apiKeysLoading.set(false); },
        error: () => this.apiKeysLoading.set(false),
      });
  }

  revokeUserApiKey(keyId: string): void {
    const u = this.user();
    if (!u) return;
    this.confirmSvc.confirm({
      message: 'Are you sure you want to revoke this API key?',
      header: 'Revoke API Key?',
      icon: 'pi pi-exclamation-triangle',
      acceptButtonStyleClass: 'p-button-danger',
      accept: () => {
        this.api.revokeUserApiKey(u.id, keyId)
          .pipe(takeUntilDestroyed(this.destroyRef))
          .subscribe({
            next: () => {
              this.userApiKeys.update(keys => keys.map(k => k.id === keyId ? { ...k, revoked: true } : k));
              this.toast.add({ severity: 'warn', summary: 'Revoked', detail: 'API key has been revoked.' });
            },
            error: () => this.toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to revoke API key.' }),
          });
      },
    });
  }

  confirmSuspend(): void {
    this.confirmSvc.confirm({
      message: 'Are you sure you want to suspend this user? They will lose access immediately.',
      header: 'Suspend User?',
      icon: 'pi pi-exclamation-triangle',
      acceptButtonStyleClass: 'p-button-danger',
      accept: () => this.showSuspendDialog.set(true),
    });
  }

  suspend(): void {
    const u = this.user();
    if (!u || this.suspending() || !this.suspendReason.trim()) return;
    this.suspending.set(true);
    this.api.suspendUser(u.id, this.suspendReason)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: res => {
          this.user.update(prev => prev ? { ...prev, suspended: res.suspended, suspendedAt: res.suspendedAt, suspendReason: res.reason } : prev);
          this.showSuspendDialog.set(false);
          this.suspendReason = '';
          this.toast.add({ severity: 'warn', summary: 'User suspended', detail: res.reason });
          this.suspending.set(false);
        },
        error: () => { this.toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to suspend user.' }); this.suspending.set(false); },
      });
  }

  unsuspend(): void {
    const u = this.user();
    if (!u) return;
    this.api.unsuspendUser(u.id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.user.update(prev => prev ? { ...prev, suspended: false, suspendedAt: null, suspendReason: null } : prev);
          this.toast.add({ severity: 'success', summary: 'User unsuspended' });
        },
        error: () => this.toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to unsuspend user.' }),
      });
  }

  saveLimits(): void {
    const u = this.user();
    if (!u || this.limitsSaving()) return;
    this.limitsSaving.set(true);
    this.api.updateLimits(u.id, this.limitsForm)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: limits => {
          this.user.update(prev => prev ? { ...prev, limits } : prev);
          this.showLimitsDialog.set(false);
          this.toast.add({ severity: 'success', summary: 'Limits updated' });
          this.limitsSaving.set(false);
        },
        error: () => { this.toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to update limits.' }); this.limitsSaving.set(false); },
      });
  }

  openLimitsDialog(): void {
    const u = this.user();
    if (u) { this.limitsForm = { ...u.limits }; this.showLimitsDialog.set(true); }
  }
}

<p-toast />
<p-confirmDialog />

<!-- ─── Suspend dialog ──────────────────────────────────────────────────── -->
<p-dialog header="Suspend User" [(visible)]="showSuspendDialog" [modal]="true" [style]="{width:'400px'}">
  <div class="admin-form-field">
    <label class="admin-form-label">Reason for suspension</label>
    <input pInputText [(ngModel)]="suspendReason" placeholder="e.g. ToS violation — spam" class="w-full" />
  </div>
  <ng-template pTemplate="footer">
    <p-button label="Cancel" severity="secondary" (onClick)="showSuspendDialog.set(false)" />
    <p-button label="Suspend" severity="danger" icon="pi pi-ban"
      [loading]="suspending()" [disabled]="!suspendReason.trim()" (onClick)="suspend()" />
  </ng-template>
</p-dialog>

<!-- ─── Limits dialog ─────────────────────────────────────────────────────── -->
<p-dialog header="Edit Limits" [(visible)]="showLimitsDialog" [modal]="true" [style]="{width:'420px'}">
  <div class="admin-limits-form">
    <div class="admin-form-field">
      <label class="admin-form-label">Max Strategies</label>
      <p-inputnumber [(ngModel)]="limitsForm.maxStrategies" [min]="0" [max]="100" class="w-full" />
    </div>
    <div class="admin-form-field">
      <label class="admin-form-label">Max Orders / Min</label>
      <p-inputnumber [(ngModel)]="limitsForm.maxOrdersPerMinute" [min]="0" [max]="1000" class="w-full" />
    </div>
    <div class="admin-form-field">
      <label class="admin-form-label">Max Position Size (USDC)</label>
      <p-inputnumber [(ngModel)]="limitsForm.maxPositionSizeUsdc" [min]="0" mode="decimal" class="w-full" />
    </div>
    <div class="admin-form-field">
      <label class="admin-form-label">Max Daily Loss (USDC)</label>
      <p-inputnumber [(ngModel)]="limitsForm.maxDailyLossUsdc" [min]="0" mode="decimal" class="w-full" />
    </div>
  </div>
  <ng-template pTemplate="footer">
    <p-button label="Cancel" severity="secondary" (onClick)="showLimitsDialog.set(false)" />
    <p-button label="Save Limits" icon="pi pi-check" [loading]="limitsSaving()" (onClick)="saveLimits()" />
  </ng-template>
</p-dialog>

<div class="pf-page">

  <div class="page-header">
    <div style="display:flex;align-items:center;gap:8px">
      <a routerLink="/users">
        <p-button icon="pi pi-arrow-left" severity="secondary" [text]="true" size="small" />
      </a>
      @if (user()) {
        <h1>{{ user()!.displayName ?? user()!.username }}</h1>
        @if (user()!.suspended) {
          <span class="admin-badge danger">SUSPENDED</span>
        }
      } @else {
        <h1>User Detail</h1>
      }
    </div>
    @if (user()) {
      <div style="display:flex;gap:8px">
        <p-button label="Edit Limits" icon="pi pi-sliders-h" severity="secondary" size="small" (onClick)="openLimitsDialog()" />
        @if (!user()!.suspended) {
          <p-button label="Suspend" icon="pi pi-ban" severity="danger" size="small" (onClick)="confirmSuspend()" />
        } @else {
          <p-button label="Unsuspend" icon="pi pi-check" severity="success" size="small" (onClick)="unsuspend()" />
        }
      </div>
    }
  </div>

  @if (loading()) {
    <p-skeleton height="200px" />
  } @else if (user()) {
    <div class="user-detail-grid">

      <!-- Identity card -->
      <div class="admin-card">
        <div class="admin-card-title">Identity</div>
        <div class="admin-detail-rows">
          <div class="admin-detail-row"><span class="admin-detail-label">Email</span><span class="pf-mono">{{ user()!.email }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Username</span><span class="pf-mono">{{ user()!.username }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Display Name</span><span>{{ user()!.displayName ?? '—' }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Bio</span><span style="color:var(--pf-text-muted)">{{ user()!.bio ?? '—' }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Twitter</span><span>{{ user()!.twitterHandle ?? '—' }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Status</span>
            <span class="admin-badge" [class.success]="user()!.status === 'CONNECTED'" [class.info]="user()!.status === 'VERIFIED'" [class.muted]="user()!.status === 'UNVERIFIED'">
              {{ user()!.status }}
            </span>
          </div>
          <div class="admin-detail-row"><span class="admin-detail-label">Joined</span><span class="pf-mono">{{ user()!.createdAt | date:'MMM d, yyyy HH:mm' }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Last Seen</span><span class="pf-mono">{{ user()!.lastSeen | date:'MMM d, yyyy HH:mm' }}</span></div>
        </div>
      </div>

      <!-- Security card -->
      <div class="admin-card">
        <div class="admin-card-title">Security</div>
        <div class="admin-detail-rows">
          <div class="admin-detail-row">
            <span class="admin-detail-label">Email Verified</span>
            <i class="pi" [class.pi-check-circle]="user()!.emailVerified" [class.pi-times-circle]="!user()!.emailVerified"
               [style.color]="user()!.emailVerified ? 'var(--pf-success)' : 'var(--pf-danger)'"></i>
          </div>
          <div class="admin-detail-row">
            <span class="admin-detail-label">2FA Enabled</span>
            <i class="pi" [class.pi-shield]="user()!.totpEnabled" [class.pi-shield]="!user()!.totpEnabled"
               [style.color]="user()!.totpEnabled ? 'var(--pf-success)' : 'var(--pf-text-muted)'"></i>
          </div>
          <div class="admin-detail-row">
            <span class="admin-detail-label">Polymarket</span>
            <i class="pi" [class.pi-link]="user()!.polymarketConnected" [class.pi-times]="!user()!.polymarketConnected"
               [style.color]="user()!.polymarketConnected ? 'var(--pf-cyan-400)' : 'var(--pf-text-muted)'"></i>
          </div>
          @if (user()!.suspended) {
            <div class="admin-detail-row"><span class="admin-detail-label">Suspended At</span><span class="pf-mono">{{ user()!.suspendedAt | date:'MMM d, yyyy HH:mm' }}</span></div>
            <div class="admin-detail-row"><span class="admin-detail-label">Reason</span><span style="color:var(--pf-danger)">{{ user()!.suspendReason }}</span></div>
          }
        </div>
      </div>

      <!-- Limits card -->
      <div class="admin-card">
        <div class="admin-card-title">Limits</div>
        <div class="admin-detail-rows">
          <div class="admin-detail-row"><span class="admin-detail-label">Max Strategies</span><span class="pf-mono">{{ user()!.limits.maxStrategies }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Max Orders/Min</span><span class="pf-mono">{{ user()!.limits.maxOrdersPerMinute }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Max Position (USDC)</span><span class="pf-mono">{{ user()!.limits.maxPositionSizeUsdc }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Max Daily Loss (USDC)</span><span class="pf-mono">{{ user()!.limits.maxDailyLossUsdc }}</span></div>
        </div>
      </div>

      <!-- Stats card -->
      <div class="admin-card">
        <div class="admin-card-title">Activity</div>
        <div class="admin-detail-rows">
          <div class="admin-detail-row"><span class="admin-detail-label">Strategies</span><span class="pf-mono">{{ user()!.strategyCount }}</span></div>
          <div class="admin-detail-row"><span class="admin-detail-label">Orders</span><span class="pf-mono">{{ user()!.orderCount }}</span></div>
        </div>
      </div>

      <!-- API Keys card -->
      <div class="admin-card" style="grid-column:1/-1">
        <div class="admin-card-title">API Keys ({{ userApiKeys().length }})</div>
        @if (apiKeysLoading()) {
          <p style="color:var(--pf-text-muted);padding:12px 0">Loading...</p>
        } @else if (userApiKeys().length === 0) {
          <p style="color:var(--pf-text-muted);padding:12px 0">No API keys.</p>
        } @else {
          <div style="overflow-x:auto">
            <table class="admin-table" style="width:100%;margin-top:8px">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Prefix</th>
                  <th>Scopes</th>
                  <th>Created</th>
                  <th>Last Used</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @for (key of userApiKeys(); track key.id) {
                  <tr>
                    <td>{{ key.name }}</td>
                    <td><span class="pf-mono">{{ key.prefix }}...</span></td>
                    <td>
                      @for (scope of key.scopes; track scope) {
                        <span class="admin-badge" [class.info]="scope === 'READ'" [class.warning]="scope === 'WRITE'" [class.success]="scope === 'TRADE'" style="font-size:10px;margin-right:4px">{{ scope }}</span>
                      }
                    </td>
                    <td class="pf-mono">{{ key.createdAt | date:'MMM d, yyyy' }}</td>
                    <td class="pf-mono">{{ key.lastUsedAt ? (key.lastUsedAt | date:'MMM d, yyyy') : '—' }}</td>
                    <td>
                      @if (key.revoked) {
                        <span class="admin-badge danger">Revoked</span>
                      } @else {
                        <span class="admin-badge success">Active</span>
                      }
                    </td>
                    <td>
                      <p-button label="Revoke" icon="pi pi-ban" severity="danger" size="small" [text]="true"
                        [disabled]="key.revoked" (onClick)="revokeUserApiKey(key.id)" />
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      </div>

    </div>
  }

</div>
