// apps/user-app/src/app/features/profile/my-profile/my-profile.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';
import { ButtonModule } from 'primeng/button';
import { AvatarModule } from 'primeng/avatar';
import { AuthStore } from '../../../core/store/auth.store';

@Component({
  selector: 'app-my-profile',
  standalone: true,
  imports: [RouterLink, DatePipe, ButtonModule, AvatarModule],
  templateUrl: './my-profile.component.html',
})
export class MyProfileComponent {
  readonly auth = inject(AuthStore);

  get user() { return this.auth.user(); }

  get initials(): string {
    const u = this.user;
    if (!u) return '?';
    return (u.displayName ?? u.username).slice(0, 2).toUpperCase();
  }
}

<div class="pf-page">

  <div class="page-header">
    <h1>My Profile</h1>
    <a routerLink="/settings">
      <p-button label="Edit Profile" icon="pi pi-pencil" severity="secondary" size="small" />
    </a>
  </div>

  @if (user) {
    <div class="profile-card">

      <!-- Avatar + identity -->
      <div class="profile-identity">
        @if (user.avatarUrl) {
          <p-avatar [image]="user.avatarUrl" shape="circle" size="xlarge" />
        } @else {
          <p-avatar [label]="initials" shape="circle" size="xlarge"
            [style]="{'background':'var(--pf-bg-raised)','color':'var(--pf-cyan-400)','font-size':'24px','width':'80px','height':'80px'}" />
        }
        <div class="profile-name-block">
          <div class="profile-display-name">{{ user.displayName ?? user.username }}</div>
          @if (user.displayName) {
            <div class="profile-username">&#64;{{ user.username }}</div>
          }
          <div class="profile-joined pf-mono">Member since {{ user.createdAt | date:'MMMM yyyy' }}</div>
        </div>
      </div>

      <!-- Bio -->
      @if (user.bio) {
        <p class="profile-bio">{{ user.bio }}</p>
      }

      <!-- Status chips -->
      <div class="profile-chips">
        <span class="profile-chip" [class.active]="user.emailVerified">
          <i class="pi pi-envelope"></i> {{ user.emailVerified ? 'Email Verified' : 'Email Unverified' }}
        </span>
        <span class="profile-chip" [class.active]="user.polymarketConnected">
          <i class="pi pi-link"></i> {{ user.polymarketConnected ? 'Polymarket Connected' : 'Not Connected' }}
        </span>
        <span class="profile-chip" [class.active]="user.totpEnabled">
          <i class="pi pi-shield"></i> {{ user.totpEnabled ? '2FA Enabled' : '2FA Disabled' }}
        </span>
      </div>

    </div>

    <!-- Quick links -->
    <div class="profile-links">
      <a routerLink="/settings" class="profile-link-card">
        <i class="pi pi-wrench"></i>
        <span>Settings</span>
        <i class="pi pi-chevron-right" style="margin-left:auto;color:var(--pf-text-muted)"></i>
      </a>
      <a routerLink="/settings/trading-account" class="profile-link-card">
        <i class="pi pi-wallet"></i>
        <span>Trading Account</span>
        <i class="pi pi-chevron-right" style="margin-left:auto;color:var(--pf-text-muted)"></i>
      </a>
      <a routerLink="/strategies" class="profile-link-card">
        <i class="pi pi-code"></i>
        <span>My Strategies</span>
        <i class="pi pi-chevron-right" style="margin-left:auto;color:var(--pf-text-muted)"></i>
      </a>
    </div>
  }

</div>

// apps/user-app-react/src/pages/profile/my-profile.tsx
import { Link } from 'react-router';
import {
  Settings, Wallet, Code, ChevronRight, Mail, Link2, Shield,
} from 'lucide-react';
import { useAuthStore } from '../../stores/auth-store';

/* ─── Component ──────────────────────────────────────────────────────── */

export function Component() {
  const { user } = useAuthStore();

  if (!user) return null;

  const initials = (user.displayName ?? user.username).slice(0, 2).toUpperCase();
  const memberSince = new Date(user.createdAt).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  return (
    <div className="p-6 max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-pf-text">My Profile</h1>
        <Link
          to="/settings"
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-pf bg-pf-elevated border border-pf-border text-xs font-medium text-pf-text-secondary hover:border-pf-border-strong transition-colors"
        >
          <Settings className="size-3.5" />
          Edit Profile
        </Link>
      </div>

      {/* Profile card */}
      <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-6">
        {/* Identity */}
        <div className="flex items-center gap-4 mb-4">
          {user.avatarUrl ? (
            <img src={user.avatarUrl} alt="" className="size-20 rounded-full object-cover" />
          ) : (
            <div className="size-20 rounded-full bg-pf-surface flex items-center justify-center text-2xl font-bold text-cyan-400">
              {initials}
            </div>
          )}
          <div>
            <div className="text-lg font-semibold text-pf-text">{user.displayName ?? user.username}</div>
            {user.displayName && (
              <div className="text-sm text-pf-text-muted">@{user.username}</div>
            )}
            <div className="text-xs font-mono text-pf-text-muted mt-1">Member since {memberSince}</div>
          </div>
        </div>

        {/* Bio */}
        {user.bio && (
          <p className="text-sm text-pf-text-secondary mb-4 leading-relaxed">{user.bio}</p>
        )}

        {/* Status chips */}
        <div className="flex flex-wrap gap-2">
          <span className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border ${
            user.emailVerified
              ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
              : 'bg-pf-overlay text-pf-text-muted border-pf-border'
          }`}>
            <Mail className="size-3" />
            {user.emailVerified ? 'Email Verified' : 'Email Unverified'}
          </span>
          <span className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border ${
            user.polymarketConnected
              ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
              : 'bg-pf-overlay text-pf-text-muted border-pf-border'
          }`}>
            <Link2 className="size-3" />
            {user.polymarketConnected ? 'Polymarket Connected' : 'Not Connected'}
          </span>
          <span className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border ${
            user.totpEnabled
              ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
              : 'bg-pf-overlay text-pf-text-muted border-pf-border'
          }`}>
            <Shield className="size-3" />
            {user.totpEnabled ? '2FA Enabled' : '2FA Disabled'}
          </span>
        </div>
      </div>

      {/* Quick links */}
      <div className="space-y-2">
        {[
          { to: '/settings', icon: <Settings className="size-4" />, label: 'Settings' },
          { to: '/settings/trading-account', icon: <Wallet className="size-4" />, label: 'Trading Account' },
          { to: '/strategies', icon: <Code className="size-4" />, label: 'My Strategies' },
        ].map(link => (
          <Link
            key={link.to}
            to={link.to}
            className="flex items-center gap-3 px-4 py-3 bg-pf-elevated border border-pf-border rounded-pf-lg hover:border-pf-border-strong transition-colors"
          >
            <span className="text-pf-text-muted">{link.icon}</span>
            <span className="text-sm font-medium text-pf-text flex-1">{link.label}</span>
            <ChevronRight className="size-4 text-pf-text-muted" />
          </Link>
        ))}
      </div>
    </div>
  );
}
