// apps/user-app/src/pages/support/create-ticket.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router';
import { ArrowLeft, Send, Loader2 } from 'lucide-react';

/* ─── Constants ──────────────────────────────────────────────────────── */

const CATEGORIES = [
  { label: 'General', value: 'GENERAL' },
  { label: 'Billing', value: 'BILLING' },
  { label: 'Technical', value: 'TECHNICAL' },
  { label: 'Account', value: 'ACCOUNT' },
  { label: 'Bug Report', value: 'BUG' },
  { label: 'Feature Request', value: 'FEATURE_REQUEST' },
];

const PRIORITIES = [
  { label: 'Low', value: 'LOW' },
  { label: 'Medium', value: 'MEDIUM' },
  { label: 'High', value: 'HIGH' },
  { label: 'Urgent', value: 'URGENT' },
];

/* ─── Component ──────────────────────────────────────────────────────── */

export function Component() {
  const navigate = useNavigate();
  const [subject, setSubject] = useState('');
  const [category, setCategory] = useState('GENERAL');
  const [priority, setPriority] = useState('MEDIUM');
  const [body, setBody] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const canSubmit = subject.trim() && body.trim() && !submitting;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!canSubmit) return;
    setSubmitting(true);
    setError('');
    try {
      const res = await fetch('/api/v1/tickets', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ subject: subject.trim(), category, priority, body: body.trim() }),
      });
      if (res.ok) {
        const data = await res.json();
        navigate(`/support/${data.id}`);
      } else {
        const err = await res.json().catch(() => null);
        setError(err?.message ?? 'Failed to create ticket.');
      }
    } catch {
      setError('Network error. Please try again.');
    }
    setSubmitting(false);
  }

  return (
    <div className="p-6 max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <button
          onClick={() => navigate('/support')}
          className="p-1.5 rounded-pf text-pf-text-muted hover:text-pf-text hover:bg-pf-elevated transition-colors"
        >
          <ArrowLeft className="size-4" />
        </button>
        <h1 className="text-2xl font-semibold text-pf-text">New Support Ticket</h1>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="bg-pf-elevated border border-pf-border rounded-pf-lg p-6 space-y-5">
        <div>
          <label className="text-xs text-pf-text-secondary uppercase tracking-wider mb-1.5 block">Subject</label>
          <input
            type="text"
            value={subject}
            onChange={e => setSubject(e.target.value)}
            placeholder="Brief description of your issue"
            className="w-full h-10 px-3 rounded-pf bg-pf-surface border border-pf-border text-sm text-pf-text placeholder:text-pf-text-muted focus:outline-none focus:border-pf-cyan-500/50 focus:ring-1 focus:ring-pf-cyan-500/20 transition-colors"
          />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="text-xs text-pf-text-secondary uppercase tracking-wider mb-1.5 block">Category</label>
            <select
              value={category}
              onChange={e => setCategory(e.target.value)}
              className="w-full h-10 px-3 rounded-pf bg-pf-surface border border-pf-border text-sm text-pf-text focus:outline-none focus:border-pf-cyan-500/50"
            >
              {CATEGORIES.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}
            </select>
          </div>
          <div>
            <label className="text-xs text-pf-text-secondary uppercase tracking-wider mb-1.5 block">Priority</label>
            <select
              value={priority}
              onChange={e => setPriority(e.target.value)}
              className="w-full h-10 px-3 rounded-pf bg-pf-surface border border-pf-border text-sm text-pf-text focus:outline-none focus:border-pf-cyan-500/50"
            >
              {PRIORITIES.map(p => <option key={p.value} value={p.value}>{p.label}</option>)}
            </select>
          </div>
        </div>

        <div>
          <label className="text-xs text-pf-text-secondary uppercase tracking-wider mb-1.5 block">Description</label>
          <textarea
            value={body}
            onChange={e => setBody(e.target.value)}
            placeholder="Describe your issue in detail..."
            rows={6}
            className="w-full px-3 py-2.5 rounded-pf bg-pf-surface border border-pf-border text-sm text-pf-text placeholder:text-pf-text-muted focus:outline-none focus:border-pf-cyan-500/50 focus:ring-1 focus:ring-pf-cyan-500/20 transition-colors resize-y"
          />
        </div>

        {error && (
          <div className="text-sm text-red-400 bg-red-500/10 px-3 py-2 rounded-pf">{error}</div>
        )}

        <div className="flex justify-end">
          <button
            type="submit"
            disabled={!canSubmit}
            className="flex items-center gap-2 px-5 py-2.5 rounded-pf bg-pf-cyan-500 text-black text-sm font-medium hover:bg-pf-cyan-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {submitting ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}
            Submit Ticket
          </button>
        </div>
      </form>
    </div>
  );
}

// apps/user-app/src/app/features/support/create-ticket.component.ts
import { Component, inject, signal, DestroyRef } from '@angular/core';
import { Router } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { TextareaModule } from 'primeng/textarea';
import { SelectModule } from 'primeng/select';
import { MessageService } from 'primeng/api';
import { ToastModule } from 'primeng/toast';

import { TicketsApiService, TicketCategory } from '../../core/services/tickets-api.service';

@Component({
  selector: 'app-create-ticket',
  standalone: true,
  imports: [FormsModule, ButtonModule, InputTextModule, TextareaModule, SelectModule, ToastModule],
  providers: [MessageService],
  template: `
    <p-toast />
    <div class="pf-page">

      <div class="page-header">
        <h1>New Support Ticket</h1>
      </div>

      <div class="portfolio-table-panel" style="padding:24px">

        <div class="form-group">
          <label class="pf-col-label">Subject</label>
          <input type="text" pInputText [(ngModel)]="subject" placeholder="Brief description of your issue"
                 style="width:100%" maxlength="255" />
        </div>

        <div class="form-group" style="margin-top:16px">
          <label class="pf-col-label">Category</label>
          <p-select [options]="categories" [(ngModel)]="category" optionLabel="label" optionValue="value"
                    placeholder="Select category" style="width:100%" />
        </div>

        <div class="form-group" style="margin-top:16px">
          <label class="pf-col-label">Description</label>
          <textarea pTextarea [(ngModel)]="body" rows="6" placeholder="Describe your issue in detail..."
                    style="width:100%;resize:vertical" maxlength="5000"></textarea>
        </div>

        <div style="margin-top:24px;display:flex;gap:12px">
          <p-button label="Submit Ticket" icon="pi pi-send" [loading]="saving()"
                    (onClick)="submit()" [disabled]="!subject.trim() || !body.trim()" />
          <p-button label="Cancel" severity="secondary" [text]="true" routerLink="/support" />
        </div>

      </div>
    </div>
  `,
})
export class CreateTicketComponent {
  private readonly api = inject(TicketsApiService);
  private readonly router = inject(Router);
  private readonly toast = inject(MessageService);
  private readonly destroyRef = inject(DestroyRef);

  subject = '';
  category: TicketCategory = 'GENERAL';
  body = '';
  saving = signal(false);

  readonly categories = [
    { label: 'General',         value: 'GENERAL' },
    { label: 'Billing',         value: 'BILLING' },
    { label: 'Technical',       value: 'TECHNICAL' },
    { label: 'Account',         value: 'ACCOUNT' },
    { label: 'Bug Report',      value: 'BUG' },
    { label: 'Feature Request', value: 'FEATURE_REQUEST' },
  ];

  submit(): void {
    if (this.saving() || !this.subject.trim() || !this.body.trim()) return;
    this.saving.set(true);
    this.api.create({ subject: this.subject.trim(), category: this.category, body: this.body.trim() })
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (ticket: any) => {
          this.toast.add({ severity: 'success', summary: 'Ticket created', detail: 'We\'ll get back to you soon.' });
          this.saving.set(false);
          this.router.navigate(['/support', ticket.id]);
        },
        error: () => {
          this.toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to create ticket. Please try again.' });
          this.saving.set(false);
        },
      });
  }
}
