// apps/user-app/src/app/features/leaderboard/leaderboard.component.ts
import { Component, OnInit, inject, signal, DestroyRef } from '@angular/core';
import { RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ButtonModule } from 'primeng/button';
import { SkeletonModule } from 'primeng/skeleton';
import { AvatarModule } from 'primeng/avatar';

import { SocialApiService, LeaderboardEntry } from '../../core/services/social-api.service';

type Period = '7d' | '30d' | 'allTime';

@Component({
  selector: 'app-leaderboard',
  standalone: true,
  imports: [RouterLink, ButtonModule, SkeletonModule, AvatarModule],
  templateUrl: './leaderboard.component.html',
})
export class LeaderboardComponent implements OnInit {
  private readonly api        = inject(SocialApiService);
  private readonly destroyRef = inject(DestroyRef);

  entries    = signal<LeaderboardEntry[]>([]);
  loading    = signal(true);
  total      = signal(0);
  totalPages = signal(0);
  page       = signal(1);
  period     = signal<Period>('7d');

  readonly periods: { label: string; value: Period }[] = [
    { label: '7 Days',   value: '7d' },
    { label: '30 Days',  value: '30d' },
    { label: 'All Time', value: 'allTime' },
  ];

  readonly skeletons = Array(10);

  ngOnInit(): void { this.load(); }

  load(): void {
    this.loading.set(true);
    this.api.leaderboard(this.period(), this.page())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next:  res => {
          this.entries.set(res.data);
          this.total.set(res.total);
          this.totalPages.set(res.totalPages);
          this.loading.set(false);
        },
        error: () => this.loading.set(false),
      });
  }

  setPeriod(p: Period): void { this.period.set(p); this.page.set(1); this.load(); }
  prevPage(): void { if (this.page() > 1) { this.page.update(p => p - 1); this.load(); } }
  nextPage(): void { if (this.page() < this.totalPages()) { this.page.update(p => p + 1); this.load(); } }

  pnlColor(pnl: string): string {
    const v = parseFloat(pnl);
    if (isNaN(v)) return 'var(--pf-text-secondary)';
    return v >= 0 ? 'var(--pf-success)' : 'var(--pf-danger)';
  }

  pnlSign(pnl: string): string {
    const v = parseFloat(pnl);
    if (isNaN(v) || v === 0) return pnl;
    return v > 0 ? `+${pnl}` : pnl;
  }

  rankMedal(rank: number): string {
    if (rank === 1) return '\u{1F947}';
    if (rank === 2) return '\u{1F948}';
    if (rank === 3) return '\u{1F949}';
    return '';
  }

  rankIcon(rank: number): string {
    if (rank === 1) return 'pi-trophy';
    if (rank === 2) return 'pi-star-fill';
    if (rank === 3) return 'pi-star';
    return '';
  }

  rankColor(rank: number): string {
    if (rank === 1) return '#F59E0B';
    if (rank === 2) return '#9CA3AF';
    if (rank === 3) return '#B45309';
    return 'var(--pf-text-muted)';
  }

  userInitials(e: LeaderboardEntry): string {
    return (e.displayName ?? e.username).slice(0, 2).toUpperCase();
  }
}

<div class="pf-page">

  <!-- ─── Header ──────────────────────────────────────────────────────── -->
  <div class="page-header">
    <h1>Leaderboard</h1>
    @if (!loading()) {
      <span class="page-count">{{ total() }} traders</span>
    }
  </div>

  <!-- ─── Period tabs ──────────────────────────────────────────────────── -->
  <div class="strategy-filter-tabs">
    @for (p of periods; track p.value) {
      <button class="filter-tab" [class.active]="period() === p.value" (click)="setPeriod(p.value)">
        {{ p.label }}
      </button>
    }
  </div>

  <!-- ─── Table ────────────────────────────────────────────────────────── -->
  <div class="portfolio-table-panel">
    <div class="table-scroll">
      <table class="data-table">
        <thead>
          <tr>
            <th class="pf-col-label" style="min-width:50px">Rank</th>
            <th class="pf-col-label" style="min-width:180px">Trader</th>
            <th class="pf-col-label" style="min-width:120px;text-align:right">P&L</th>
            <th class="pf-col-label" style="min-width:100px;text-align:right">Win Rate</th>
            <th class="pf-col-label" style="min-width:100px;text-align:right">Trades</th>
          </tr>
        </thead>
        <tbody>
          @if (loading()) {
            @for (s of skeletons; track $index) {
              <tr class="table-row">
                @for (c of [1,2,3,4,5]; track c) {
                  <td><p-skeleton height="12px" /></td>
                }
              </tr>
            }
          } @else if (entries().length === 0) {
            <tr>
              <td colspan="5">
                <div class="pf-empty-state" style="padding:48px">
                  <i class="pi pi-trophy pf-empty-icon"></i>
                  <p class="pf-empty-title">No data yet</p>
                  <p class="pf-empty-desc">Start trading to appear on the leaderboard.</p>
                </div>
              </td>
            </tr>
          } @else {
            @for (entry of entries(); track entry.userId) {
              <tr class="table-row leaderboard-row">
                <!-- Rank -->
                <td>
                  <div class="leaderboard-rank" [style.color]="rankColor(entry.rank)">
                    @if (rankMedal(entry.rank)) {
                      <span style="font-size:18px">{{ rankMedal(entry.rank) }}</span>
                    } @else {
                      <span class="pf-mono" style="font-size:12px">{{ entry.rank }}</span>
                    }
                  </div>
                </td>
                <!-- Trader -->
                <td>
                  <a [routerLink]="['/profile', entry.username]" class="leaderboard-user">
                    <p-avatar [label]="userInitials(entry)" shape="circle" size="normal"
                      [style]="{'background':'var(--pf-bg-raised)','color':'var(--pf-cyan-400)','font-size':'11px'}" />
                    <div class="leaderboard-user-info">
                      <span class="leaderboard-display-name">{{ entry.displayName ?? entry.username }}</span>
                      @if (entry.displayName) {
                        <span class="leaderboard-username">&#64;{{ entry.username }}</span>
                      }
                    </div>
                  </a>
                </td>
                <!-- P&L -->
                <td style="text-align:right">
                  <span class="pf-mono" [style.color]="pnlColor(entry.pnl)">
                    {{ pnlSign(entry.pnl) }}
                  </span>
                </td>
                <!-- Win Rate -->
                <td style="text-align:right">
                  <span class="pf-mono" style="color:var(--pf-text-secondary)">{{ entry.winRate }}%</span>
                </td>
                <!-- Trades -->
                <td style="text-align:right">
                  <span class="pf-mono" style="color:var(--pf-text-secondary)">{{ entry.tradeCount }}</span>
                </td>
              </tr>
            }
          }
        </tbody>
      </table>
    </div>
  </div>

  <!-- ─── Pagination ──────────────────────────────────────────────────── -->
  @if (totalPages() > 1) {
    <div class="markets-pagination">
      <p-button icon="pi pi-chevron-left"  severity="secondary" [text]="true" size="small" [disabled]="page() === 1"            (onClick)="prevPage()" />
      <span class="pf-mono" style="font-size:13px;color:var(--pf-text-secondary)">{{ page() }} / {{ totalPages() }}</span>
      <p-button icon="pi pi-chevron-right" severity="secondary" [text]="true" size="small" [disabled]="page() === totalPages()" (onClick)="nextPage()" />
    </div>
  }

</div>

// apps/user-app/src/pages/leaderboard/leaderboard.tsx
import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router';
import { toast } from 'sonner';
import { ChevronLeft, ChevronRight, Trophy } from 'lucide-react';

/* ─── Types ──────────────────────────────────────────────────────────── */

type Period = '7d' | '30d' | 'allTime';

interface LeaderboardEntry {
  userId: string;
  username: string;
  displayName?: string;
  avatarUrl?: string;
  rank: number;
  pnl: string;
  winRate: string;
  tradeCount: number;
}

interface LeaderboardResponse {
  data: LeaderboardEntry[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/* ─── Helpers ────────────────────────────────────────────────────────── */

const PERIODS: { label: string; value: Period }[] = [
  { label: '7 Days', value: '7d' },
  { label: '30 Days', value: '30d' },
  { label: 'All Time', value: 'allTime' },
];

function pnlColor(pnl: string): string {
  const v = parseFloat(pnl);
  if (isNaN(v)) return 'text-pf-text-secondary';
  return v >= 0 ? 'text-pf-success' : 'text-pf-danger';
}

function pnlSign(pnl: string): string {
  const v = parseFloat(pnl);
  if (isNaN(v) || v === 0) return pnl;
  return v > 0 ? `+${pnl}` : pnl;
}

function rankMedal(rank: number): string {
  if (rank === 1) return '\u{1F947}';
  if (rank === 2) return '\u{1F948}';
  if (rank === 3) return '\u{1F949}';
  return '';
}

function rankColor(rank: number): string {
  if (rank === 1) return 'text-amber-400';
  if (rank === 2) return 'text-gray-400';
  if (rank === 3) return 'text-amber-700';
  return 'text-pf-text-muted';
}

function userInitials(e: LeaderboardEntry): string {
  return (e.displayName ?? e.username).slice(0, 2).toUpperCase();
}

/* ─── Component ──────────────────────────────────────────────────────── */

export function Component() {
  const [entries, setEntries] = useState<LeaderboardEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [total, setTotal] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [page, setPage] = useState(1);
  const [period, setPeriod] = useState<Period>('7d');

  const load = useCallback(async (p: number, per: Period) => {
    setLoading(true);
    try {
      const res = await fetch(`/api/v1/leaderboard?period=${per}&page=${p}`, { credentials: 'include' });
      if (res.ok) {
        const data: LeaderboardResponse = await res.json();
        setEntries(data.data);
        setTotal(data.total);
        setTotalPages(data.totalPages);
      }
    } catch { toast.error('Failed to load data'); }
    setLoading(false);
  }, []);

  useEffect(() => { load(page, period); }, [page, period, load]);

  function changePeriod(p: Period) {
    setPeriod(p);
    setPage(1);
  }

  return (
    <div className="animate-fade-in p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-pf-text">Leaderboard</h1>
        {!loading && <span className="text-sm text-pf-text-muted">{total} traders</span>}
      </div>

      {/* Period tabs */}
      <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-none">
        {PERIODS.map(p => (
          <button
            key={p.value}
            onClick={() => changePeriod(p.value)}
            className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap border transition-colors ${
              period === p.value
                ? 'bg-pf-cyan-500/15 text-pf-cyan-400 border-pf-cyan-500/30'
                : 'bg-pf-elevated text-pf-text-secondary border-pf-border hover:border-pf-border-strong'
            }`}
          >
            {p.label}
          </button>
        ))}
      </div>

      {/* Table */}
      <div className="bg-pf-elevated border border-pf-border rounded-pf-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-pf-surface text-left text-xs text-pf-text-secondary uppercase tracking-wider">
                <th className="px-4 py-3 font-medium text-right w-16">Rank</th>
                <th className="px-4 py-3 font-medium">Trader</th>
                <th className="px-4 py-3 font-medium text-right">P&L</th>
                <th className="px-4 py-3 font-medium text-right">Win Rate</th>
                <th className="px-4 py-3 font-medium text-right">Trades</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-pf-border-subtle">
              {loading ? (
                Array.from({ length: 10 }, (_, i) => (
                  <tr key={i}>
                    {Array.from({ length: 5 }, (_, j) => (
                      <td key={j} className="px-4 py-3"><div className="h-3 bg-pf-overlay rounded animate-pulse" /></td>
                    ))}
                  </tr>
                ))
              ) : entries.length === 0 ? (
                <tr>
                  <td colSpan={5}>
                    <div className="flex flex-col items-center justify-center py-16 text-center">
                      <Trophy className="size-10 text-pf-text-muted mb-3" />
                      <p className="text-sm font-medium text-pf-text">No data yet</p>
                      <p className="text-xs text-pf-text-muted mt-1">Start trading to appear on the leaderboard.</p>
                    </div>
                  </td>
                </tr>
              ) : (
                entries.map(entry => (
                  <tr key={entry.userId} className="hover:bg-pf-surface/50 transition-colors">
                    <td className="px-4 py-3 text-right">
                      <div className={`${rankColor(entry.rank)}`}>
                        {rankMedal(entry.rank) ? (
                          <span className="text-lg">{rankMedal(entry.rank)}</span>
                        ) : (
                          <span className="font-mono text-xs">{entry.rank}</span>
                        )}
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <Link to={`/profile/${entry.username}`} className="flex items-center gap-3 hover:text-pf-cyan-400 transition-colors">
                        {entry.avatarUrl ? (
                          <img src={entry.avatarUrl} alt={`${entry.displayName ?? entry.username} avatar`} className="size-8 rounded-full object-cover" />
                        ) : (
                          <div className="size-8 rounded-full bg-pf-surface flex items-center justify-center text-[11px] font-semibold text-cyan-400">
                            {userInitials(entry)}
                          </div>
                        )}
                        <div>
                          <div className="text-sm font-medium text-pf-text">{entry.displayName ?? entry.username}</div>
                          {entry.displayName && (
                            <div className="text-xs text-pf-text-muted">@{entry.username}</div>
                          )}
                        </div>
                      </Link>
                    </td>
                    <td className={`px-4 py-3 text-right font-mono ${pnlColor(entry.pnl)}`}>
                      {pnlSign(entry.pnl)}
                    </td>
                    <td className="px-4 py-3 text-right font-mono text-pf-text-secondary">
                      {entry.winRate}%
                    </td>
                    <td className="px-4 py-3 text-right font-mono text-pf-text-secondary">
                      {entry.tradeCount}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-4 pt-2">
          <button
            onClick={() => setPage(p => Math.max(1, p - 1))}
            disabled={page === 1}
            className="p-2 rounded-pf text-pf-text-secondary hover:text-pf-text hover:bg-pf-elevated disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
          >
            <ChevronLeft className="size-4" />
          </button>
          <span className="text-sm font-mono text-pf-text-secondary">{page} / {totalPages}</span>
          <button
            onClick={() => setPage(p => Math.min(totalPages, p + 1))}
            disabled={page === totalPages}
            className="p-2 rounded-pf text-pf-text-secondary hover:text-pf-text hover:bg-pf-elevated disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
          >
            <ChevronRight className="size-4" />
          </button>
        </div>
      )}
    </div>
  );
}
