// apps/user-app/src/app/features/auth/forgot-password/forgot-password.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { MessageModule } from 'primeng/message';
import { CardModule } from 'primeng/card';
import { AuthApiService } from '../../../core/services/auth-api.service';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, ButtonModule, InputTextModule, MessageModule, CardModule],
  template: `
    <div class="auth-page">
      <div class="auth-card">
        <div class="auth-logo">
          <i class="pi pi-bolt logo-icon"></i>
          <span class="logo-text">Polyforge</span>
        </div>

        <p-card>
          @if (!sent()) {
            <h2>Reset password</h2>
            <p class="auth-subtitle">We'll send you a reset link.</p>

            <form [formGroup]="form" (ngSubmit)="submit()">
              <div class="form-field">
                <label class="field-label" for="email">Email</label>
                <input pInputText id="email" type="email" formControlName="email"
                       placeholder="you@example.com" class="w-full" />
                @if (form.get('email')?.invalid && form.get('email')?.touched) {
                  <small class="field-error">Enter a valid email address</small>
                }
              </div>

              <p-button type="submit" label="Send reset link" styleClass="w-full"
                        [loading]="loading()" [disabled]="loading()" />
            </form>
          } @else {
            <div style="text-align:center">
              <i class="pi pi-send" style="font-size:3rem;color:var(--p-primary-400);margin-bottom:1rem;display:block"></i>
              <h2>Check your inbox</h2>
              <p class="text-muted">
                If an account with that email exists, we've sent a reset link.
              </p>
            </div>
          }

          <div class="auth-footer" style="margin-top:1rem">
            <a [routerLink]="'/login'">Back to login</a>
          </div>
        </p-card>
      </div>
    </div>
  `,
})
export class ForgotPasswordComponent {
  private readonly fb      = inject(FormBuilder);
  private readonly authApi = inject(AuthApiService);

  readonly loading = signal(false);
  readonly sent    = signal(false);

  readonly form = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
  });

  submit(): void {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true);
    this.authApi.forgotPassword(this.form.value.email!).subscribe({
      next: () => { this.loading.set(false); this.sent.set(true); },
      error: () => { this.loading.set(false); this.sent.set(true); }, // always 200 per spec
    });
  }
}

// apps/user-app/src/pages/auth/forgot-password.tsx
import { useState, type FormEvent } from 'react';
import { Link } from 'react-router';
import { Mail, ArrowLeft, Check } from 'lucide-react';
import { AuthBackground } from '@/components/auth-background';
import { Button, Input } from '@polyforge/ui';

export function Component() {
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);
  const [touched, setTouched] = useState(false);

  const emailError = touched && !email ? 'Email is required'
    : touched && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? 'Enter a valid email address'
    : '';

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setTouched(true);
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return;

    setLoading(true);
    try {
      await fetch('/auth/v1/forgot-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ email }),
      });
    } catch {
      // always show success per spec
    } finally {
      setLoading(false);
      setSent(true);
    }
  }

  return (
    <main
      className="min-h-screen flex items-center justify-center p-4 relative bg-app"
    >
      <AuthBackground />
      <div className="w-full max-w-md relative z-10">
        {/* Logo */}
        <div className="text-center mb-8">
          <div className="text-accent inline-block">
            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path d="M12 2L20.66 7V17L12 22L3.34 17V7L12 2Z" stroke="currentColor" strokeWidth="1.2" fill="none" opacity="0.4"/>
              <path d="M13 5L7.5 13H11L10 19L16.5 11H13L13 5Z" fill="currentColor"/>
            </svg>
          </div>
        </div>

        {/* Card */}
        <div className="bg-elevated border border-default rounded-pf-lg p-8 shadow-pf-lg">
          {!sent ? (
            <>
              <h1 className="text-xl font-semibold text-primary mb-1">Reset password</h1>
              <p className="text-sm text-tertiary mb-6">We&apos;ll send you a reset link.</p>

              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-primary mb-2">Email</label>
                  <div className="relative">
                    <Mail className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-tertiary" />
                    <Input
                      id="email"
                      type="email"
                      autoComplete="email"
                      autoFocus
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      onBlur={() => setTouched(true)}
                      placeholder="you@example.com"
                      aria-invalid={!!emailError}
                      aria-describedby={emailError ? 'forgot-email-error' : undefined}
                      className="w-full pl-10 pr-4 py-3 bg-app border border-default rounded-pf text-primary placeholder:text-tertiary/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/40 focus-visible:border-accent transition-colors"
                    />
                  </div>
                  {emailError && <p id="forgot-email-error" role="alert" className="mt-1 text-xs text-loss">{emailError}</p>}
                </div>

                <Button
                  type="submit"
                  disabled={loading}
                  className="w-full py-3 bg-accent text-inverse font-semibold rounded-pf hover:bg-accent-text disabled:opacity-50 disabled:cursor-not-allowed transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/40 focus-visible:ring-offset-2 focus-visible:ring-offset-pf-elevated"
                >
                  {loading ? 'Sending...' : 'Send reset link'}
                </Button>
              </form>
            </>
          ) : (
            <div className="text-center">
              <div className="size-16 rounded-pf-full bg-accent/10 flex items-center justify-center mx-auto mb-4">
                <Check className="size-8 text-accent" />
              </div>
              <h1 className="text-xl font-semibold text-primary mb-2">Check your inbox</h1>
              <p className="text-sm text-tertiary">
                If an account with that email exists, we&apos;ve sent a reset link.
              </p>
            </div>
          )}

          <div className="border-t border-default mt-6 pt-4 text-center text-sm">
            <Link to="/login" className="inline-flex items-center gap-2 text-accent hover:text-accent-text transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/50 rounded-pf-sm">
              <ArrowLeft className="size-4" />
              Back to login
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
