// apps/user-app/src/app/features/auth/register/register.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators, AbstractControl, ValidationErrors } from '@angular/forms';
import { Router, RouterLink, ActivatedRoute } from '@angular/router';
import { HttpErrorResponse } from '@angular/common/http';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { PasswordModule } from 'primeng/password';
import { CheckboxModule } from 'primeng/checkbox';
import { MessageModule } from 'primeng/message';
import { CardModule } from 'primeng/card';
import { DividerModule } from 'primeng/divider';
import { AuthStore } from '../../../core/store/auth.store';
import { ApiError } from '../../../core/models/user.model';

function passwordValidator(control: AbstractControl): ValidationErrors | null {
  const v = control.value as string;
  if (!v) return null;
  if (!/[A-Z]/.test(v)) return { password: 'Must contain at least one uppercase letter' };
  if (!/[a-z]/.test(v)) return { password: 'Must contain at least one lowercase letter' };
  if (!/[0-9]/.test(v)) return { password: 'Must contain at least one number' };
  return null;
}

function usernameValidator(control: AbstractControl): ValidationErrors | null {
  const v = control.value as string;
  if (!v) return null;
  if (!/^[a-zA-Z0-9_]+$/.test(v)) return { username: 'Only letters, numbers, and underscores' };
  if (/^_/.test(v) || /_$/.test(v)) return { username: 'Cannot start or end with underscore' };
  return null;
}

function confirmPasswordValidator(group: AbstractControl): ValidationErrors | null {
  const pw  = group.get('password')?.value;
  const cpw = group.get('confirmPassword')?.value;
  if (!cpw) return null;
  return pw === cpw ? null : { passwordMismatch: true };
}

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    RouterLink,
    ButtonModule,
    InputTextModule,
    PasswordModule,
    CheckboxModule,
    MessageModule,
    CardModule,
    DividerModule,
  ],
  templateUrl: './register.component.html',
})
export class RegisterComponent {
  private readonly fb     = inject(FormBuilder);
  private readonly auth   = inject(AuthStore);
  private readonly router = inject(Router);
  private readonly route  = inject(ActivatedRoute);

  readonly loading    = signal(false);
  readonly error      = signal('');
  readonly inviteOnly = signal(false);

  readonly form = this.fb.group({
    email:           ['', [Validators.required, Validators.email, Validators.maxLength(255)]],
    username:        ['', [Validators.required, Validators.minLength(3), Validators.maxLength(30), usernameValidator]],
    password:        ['', [Validators.required, Validators.minLength(8), passwordValidator]],
    confirmPassword: ['', Validators.required],
    tosAccepted:     [false, Validators.requiredTrue],
    inviteCode:      ['', [Validators.maxLength(20)]],
  }, { validators: confirmPasswordValidator });

  constructor() {
    // Pre-fill invite code from ?invite= query param and show the field
    const code = this.route.snapshot.queryParamMap.get('invite');
    if (code) {
      this.form.patchValue({ inviteCode: code });
      this.inviteOnly.set(true);
    }
  }

  submit(): void {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true);
    this.error.set('');

    const { email, username, password, tosAccepted, inviteCode } = this.form.value;
    if (this.form.hasError('passwordMismatch')) {
      this.form.get('confirmPassword')!.setErrors({ passwordMismatch: true });
      this.loading.set(false);
      return;
    }
    const body: Parameters<typeof this.auth.register>[0] = {
      email: email!, username: username!, password: password!, tosAccepted: tosAccepted!,
    };
    if (inviteCode) body.inviteCode = inviteCode;

    this.auth.register(body).subscribe({
      next: () => { this.router.navigate(['/verify-email']); },
      error: (err: HttpErrorResponse) => {
        this.loading.set(false);
        const apiErr = err.error as ApiError;
        if (apiErr?.code === 'INVITE_REQUIRED' || apiErr?.code === 'INVITE_INVALID') {
          this.inviteOnly.set(true);
        }
        this.error.set(apiErr?.message ?? 'Registration failed. Please try again.');
      },
    });
  }

  fieldError(field: string): string {
    const ctrl = this.form.get(field);
    if (!ctrl?.touched || !ctrl.errors) return '';
    if (ctrl.errors['required']) return `${field.charAt(0).toUpperCase() + field.slice(1)} is required`;
    if (ctrl.errors['email']) return 'Enter a valid email address';
    if (ctrl.errors['minlength']) return `Minimum ${ctrl.errors['minlength'].requiredLength} characters`;
    if (ctrl.errors['maxlength']) return `Maximum ${ctrl.errors['maxlength'].requiredLength} characters`;
    if (ctrl.errors['password']) return ctrl.errors['password'];
    if (ctrl.errors['username']) return ctrl.errors['username'];
    return '';
  }
}

<div class="auth-page">
  <div class="auth-card" style="max-width:460px">
    <div class="auth-logo">
      <i class="pi pi-bolt logo-icon"></i>
      <span class="logo-text">Polyforge</span>
    </div>

    <p-card>
      <h2>Create account</h2>
      <p class="auth-subtitle">Start trading on autopilot</p>

      @if (error()) {
        <p-message severity="error" [text]="error()" styleClass="w-full mb-3" />
      }

      <form [formGroup]="form" (ngSubmit)="submit()">
        <div class="form-field">
          <label class="field-label" for="email">Email</label>
          <input pInputText id="email" type="email" formControlName="email"
                 placeholder="you@example.com" class="w-full" />
          @if (fieldError('email')) { <small class="field-error">{{ fieldError('email') }}</small> }
        </div>

        <div class="form-field">
          <label class="field-label" for="username">Username</label>
          <input pInputText id="username" type="text" formControlName="username"
                 placeholder="alice" class="w-full" />
          @if (fieldError('username')) { <small class="field-error">{{ fieldError('username') }}</small> }
        </div>

        <div class="form-field">
          <label class="field-label" for="password">Password</label>
          <p-password id="password" formControlName="password"
                      placeholder="At least 8 characters"
                      [toggleMask]="true"
                      styleClass="w-full" inputStyleClass="w-full">
            <ng-template pTemplate="footer">
              <ul style="padding-left:1rem;margin:0.5rem 0 0;font-size:0.8rem;line-height:1.8">
                <li>Minimum 8 characters</li>
                <li>One uppercase letter</li>
                <li>One lowercase letter</li>
                <li>One number</li>
              </ul>
            </ng-template>
          </p-password>
          @if (fieldError('password')) { <small class="field-error">{{ fieldError('password') }}</small> }
        </div>

        <div class="form-field">
          <label class="field-label" for="confirmPassword">Confirm password</label>
          <p-password id="confirmPassword" formControlName="confirmPassword"
                      placeholder="Repeat your password"
                      [toggleMask]="true"
                      [feedback]="false"
                      styleClass="w-full" inputStyleClass="w-full" />
          @if (form.get('confirmPassword')?.touched && (form.hasError('passwordMismatch') || form.get('confirmPassword')?.hasError('passwordMismatch'))) {
            <small class="field-error">Passwords do not match</small>
          }
        </div>

        @if (inviteOnly() || form.get('inviteCode')?.value) {
          <div class="form-field">
            <label class="field-label" for="inviteCode">Invite code</label>
            <input pInputText id="inviteCode" type="text" formControlName="inviteCode"
                   placeholder="POLY-XXXXXX" class="w-full" style="text-transform:uppercase"
                   (input)="form.get('inviteCode')!.setValue($any($event.target).value.toUpperCase(), {emitEvent:false})" />
            @if (fieldError('inviteCode')) { <small class="field-error">{{ fieldError('inviteCode') }}</small> }
          </div>
        }

        <div class="form-field" style="display:flex;align-items:flex-start;gap:0.5rem">
          <p-checkbox formControlName="tosAccepted" [binary]="true" inputId="tos" />
          <label for="tos" style="font-size:0.875rem;line-height:1.5;cursor:pointer">
            I agree to the <a href="/terms" target="_blank" style="color:var(--p-primary-400)">Terms of Service</a>
          </label>
        </div>
        @if (form.get('tosAccepted')?.touched && form.get('tosAccepted')?.invalid) {
          <small class="field-error">You must accept the Terms of Service</small>
        }

        <p-button type="submit" label="Create account" styleClass="w-full mt-2"
                  [loading]="loading()" [disabled]="loading()" />
      </form>

      <p-divider />

      <div class="auth-footer">
        Already have an account?&nbsp;<a [routerLink]="'/login'">Sign in</a>
      </div>
    </p-card>
  </div>
</div>

// apps/user-app/src/pages/auth/register.tsx
import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router';
import { Mail, Lock, User, KeyRound, AlertCircle } from 'lucide-react';
import { useAuthStore } from '@/stores/auth-store';

function validatePassword(v: string): string {
  if (!v) return '';
  if (!/[A-Z]/.test(v)) return 'Must contain at least one uppercase letter';
  if (!/[a-z]/.test(v)) return 'Must contain at least one lowercase letter';
  if (!/[0-9]/.test(v)) return 'Must contain at least one number';
  return '';
}

function validateUsername(v: string): string {
  if (!v) return '';
  if (!/^[a-zA-Z0-9_]+$/.test(v)) return 'Only letters, numbers, and underscores';
  if (/^_/.test(v) || /_$/.test(v)) return 'Cannot start or end with underscore';
  return '';
}

export function Component() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const register = useAuthStore((s) => s.register);

  const [email, setEmail] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [tosAccepted, setTosAccepted] = useState(false);
  const [inviteCode, setInviteCode] = useState(searchParams.get('invite') ?? '');
  const [showInvite, setShowInvite] = useState(!!searchParams.get('invite'));
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [touched, setTouched] = useState<Record<string, boolean>>({});

  function fieldError(field: string): string {
    if (!touched[field]) return '';
    switch (field) {
      case 'email':
        if (!email) return 'Email is required';
        if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return 'Enter a valid email address';
        if (email.length > 255) return 'Maximum 255 characters';
        return '';
      case 'username':
        if (!username) return 'Username is required';
        if (username.length < 3) return 'Minimum 3 characters';
        if (username.length > 30) return 'Maximum 30 characters';
        return validateUsername(username);
      case 'password':
        if (!password) return 'Password is required';
        if (password.length < 8) return 'Minimum 8 characters';
        return validatePassword(password);
      case 'confirmPassword':
        if (!confirmPassword) return 'Confirm your password';
        if (password !== confirmPassword) return 'Passwords do not match';
        return '';
      case 'tos':
        if (!tosAccepted) return 'You must accept the Terms of Service';
        return '';
      default:
        return '';
    }
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    const allTouched = { email: true, username: true, password: true, confirmPassword: true, tos: true };
    setTouched(allTouched);

    const hasErrors = ['email', 'username', 'password', 'confirmPassword', 'tos'].some((f) => {
      // Re-check with touched=true
      switch (f) {
        case 'email': return !email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || email.length > 255;
        case 'username': return !username || username.length < 3 || username.length > 30 || !!validateUsername(username);
        case 'password': return !password || password.length < 8 || !!validatePassword(password);
        case 'confirmPassword': return !confirmPassword || password !== confirmPassword;
        case 'tos': return !tosAccepted;
        default: return false;
      }
    });
    if (hasErrors) return;

    setLoading(true);
    setError('');

    try {
      const body: Parameters<typeof register>[0] = {
        email, username, password, tosAccepted,
      };
      if (inviteCode) body.inviteCode = inviteCode;
      await register(body);
      navigate('/verify-email');
    } catch (err: unknown) {
      setLoading(false);
      const apiErr = err as { code?: string; message?: string };
      if (apiErr?.code === 'INVITE_REQUIRED' || apiErr?.code === 'INVITE_INVALID') {
        setShowInvite(true);
      }
      setError(apiErr?.message ?? 'Registration failed. Please try again.');
    }
  }

  const inputClass = 'w-full pl-10 pr-4 py-2.5 bg-pf-base border border-pf-border rounded-pf text-pf-text placeholder:text-pf-text-muted/50 focus:outline-none focus:ring-2 focus:ring-pf-cyan-500/40 focus:border-pf-cyan-500 transition-colors';

  return (
    <div
      className="min-h-screen flex items-center justify-center p-4 py-8"
      style={{ background: 'radial-gradient(ellipse at 50% 0%, rgba(6,182,212,0.08) 0%, transparent 60%), var(--color-pf-base)' }}
    >
      <div className="w-full max-w-md">
        {/* Logo centered above card */}
        <div className="text-center mb-8">
          <div className="text-pf-cyan-500 inline-block">
            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path d="M12 2L20.66 7V17L12 22L3.34 17V7L12 2Z" stroke="currentColor" strokeWidth="1.2" fill="none" opacity="0.4"/>
              <path d="M13 5L7.5 13H11L10 19L16.5 11H13L13 5Z" fill="currentColor"/>
            </svg>
          </div>
          <h1 className="text-2xl font-semibold mt-4 bg-gradient-to-r from-pf-cyan-400 to-pf-cyan-300 bg-clip-text text-transparent">
            Create your account
          </h1>
          <p className="text-pf-text-muted text-sm mt-1">Start trading on autopilot</p>
        </div>

        {/* Card */}
        <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-8 shadow-pf-lg">

          {error && (
            <div className="flex items-center gap-2 bg-red-500/10 border border-red-500/20 text-red-400 rounded-pf px-4 py-3 mb-4 text-sm">
              <AlertCircle className="size-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Email */}
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-pf-text mb-1.5">Email</label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-pf-text-muted" />
                <input
                  id="email"
                  type="email"
                  autoComplete="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  onBlur={() => setTouched((t) => ({ ...t, email: true }))}
                  placeholder="you@example.com"
                  className={inputClass}
                />
              </div>
              {fieldError('email') && <p className="mt-1 text-xs text-red-400">{fieldError('email')}</p>}
            </div>

            {/* Username */}
            <div>
              <label htmlFor="username" className="block text-sm font-medium text-pf-text mb-1.5">Username</label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-pf-text-muted" />
                <input
                  id="username"
                  type="text"
                  autoComplete="username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  onBlur={() => setTouched((t) => ({ ...t, username: true }))}
                  placeholder="alice"
                  className={inputClass}
                />
              </div>
              {fieldError('username') && <p className="mt-1 text-xs text-red-400">{fieldError('username')}</p>}
            </div>

            {/* Password */}
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-pf-text mb-1.5">Password</label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-pf-text-muted" />
                <input
                  id="password"
                  type="password"
                  autoComplete="new-password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  onBlur={() => setTouched((t) => ({ ...t, password: true }))}
                  placeholder="At least 8 characters"
                  className={inputClass}
                />
              </div>
              {fieldError('password') && <p className="mt-1 text-xs text-red-400">{fieldError('password')}</p>}
              {touched.password && !fieldError('password') && password && (
                <ul className="mt-1.5 text-xs text-pf-text-muted space-y-0.5 list-disc list-inside">
                  <li>Minimum 8 characters</li>
                  <li>One uppercase letter</li>
                  <li>One lowercase letter</li>
                  <li>One number</li>
                </ul>
              )}
            </div>

            {/* Confirm Password */}
            <div>
              <label htmlFor="confirmPassword" className="block text-sm font-medium text-pf-text mb-1.5">Confirm password</label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-pf-text-muted" />
                <input
                  id="confirmPassword"
                  type="password"
                  autoComplete="new-password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  onBlur={() => setTouched((t) => ({ ...t, confirmPassword: true }))}
                  placeholder="Repeat your password"
                  className={inputClass}
                />
              </div>
              {fieldError('confirmPassword') && <p className="mt-1 text-xs text-red-400">{fieldError('confirmPassword')}</p>}
            </div>

            {/* Invite Code */}
            {(showInvite || inviteCode) && (
              <div>
                <label htmlFor="inviteCode" className="block text-sm font-medium text-pf-text mb-1.5">Invite code</label>
                <div className="relative">
                  <KeyRound className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-pf-text-muted" />
                  <input
                    id="inviteCode"
                    type="text"
                    value={inviteCode}
                    onChange={(e) => setInviteCode(e.target.value.toUpperCase())}
                    placeholder="POLY-XXXXXX"
                    className={`${inputClass} uppercase`}
                  />
                </div>
              </div>
            )}

            {/* TOS */}
            <div className="flex items-start gap-2.5">
              <input
                id="tos"
                type="checkbox"
                checked={tosAccepted}
                onChange={(e) => { setTosAccepted(e.target.checked); setTouched((t) => ({ ...t, tos: true })); }}
                className="mt-1 size-4 rounded border-pf-border bg-pf-base accent-pf-cyan-500"
              />
              <label htmlFor="tos" className="text-sm text-pf-text leading-relaxed cursor-pointer">
                I agree to the{' '}
                <a href="/terms" target="_blank" rel="noopener noreferrer" className="text-pf-cyan-500 hover:text-pf-cyan-400 transition-colors">
                  Terms of Service
                </a>
              </label>
            </div>
            {fieldError('tos') && <p className="text-xs text-red-400 -mt-2">{fieldError('tos')}</p>}

            <button
              type="submit"
              disabled={loading}
              className="w-full py-2.5 bg-pf-cyan-500 text-black font-semibold rounded-pf hover:bg-pf-cyan-400 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {loading ? 'Creating account...' : 'Create account'}
            </button>
          </form>

        </div>

        {/* Links below card */}
        <p className="text-center text-sm text-pf-text-muted mt-6">
          Already have an account?{' '}
          <Link to="/login" className="text-pf-cyan-400 hover:text-pf-cyan-300 transition-colors">
            Sign in
          </Link>
        </p>
      </div>
    </div>
  );
}
