// apps/user-app-react/src/pages/markets/markets-list.tsx
import { useState, useEffect, useCallback, useRef } from 'react';
import { Link } from 'react-router';
import {
  Search,
  Grid3X3,
  List,
  ChevronLeft,
  ChevronRight,
  Zap,
  Trophy,
  Bitcoin,
  Landmark,
  TrendingUp,
  Wallet,
  Cpu,
  LayoutGrid,
} from 'lucide-react';

/* ─── Types ──────────────────────────────────────────────────────────── */

interface MarketToken {
  tokenId: string;
  outcome: string;
  price: string;
  liquidity: string;
}

interface Market {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  image: string | null;
  seriesSlug: string;
  tokens: MarketToken[];
  volume24h: string;
  endDate: string;
  closed: boolean;
}

interface MarketsResponse {
  data: Market[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
  hasNext: boolean;
}

type SortOption = 'volume' | 'newest' | 'closing_soon' | 'liquidity';
type ViewMode = 'cards' | 'table';

/* ─── Helpers ────────────────────────────────────────────────────────── */

const SORT_OPTIONS: { label: string; value: SortOption }[] = [
  { label: 'Volume', value: 'volume' },
  { label: 'Newest', value: 'newest' },
  { label: 'Closing Soon', value: 'closing_soon' },
  { label: 'Liquidity', value: 'liquidity' },
];

const CATEGORIES = ['all', 'Sports', 'Crypto', 'Politics', 'Economics', 'Finance', 'Technology'] as const;

const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  all: <LayoutGrid className="size-3.5" />,
  Sports: <Trophy className="size-3.5" />,
  Crypto: <Bitcoin className="size-3.5" />,
  Politics: <Landmark className="size-3.5" />,
  Economics: <TrendingUp className="size-3.5" />,
  Finance: <Wallet className="size-3.5" />,
  Technology: <Cpu className="size-3.5" />,
};

const CATEGORY_COLORS: Record<string, { bg: string; text: string }> = {
  Sports: { bg: 'bg-blue-500/15', text: 'text-blue-400' },
  Crypto: { bg: 'bg-amber-500/15', text: 'text-amber-400' },
  Politics: { bg: 'bg-purple-500/15', text: 'text-purple-400' },
  Economics: { bg: 'bg-emerald-500/15', text: 'text-emerald-400' },
  Finance: { bg: 'bg-cyan-500/15', text: 'text-cyan-400' },
  Technology: { bg: 'bg-pink-500/15', text: 'text-pink-400' },
};

function formatVolume(vol: string): string {
  const v = parseFloat(vol);
  if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(1)}M`;
  if (v >= 1_000) return `$${(v / 1_000).toFixed(1)}K`;
  return `$${v.toFixed(0)}`;
}

function daysUntil(dateStr: string): string {
  const d = Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86_400_000);
  if (d < 0) return 'Closed';
  if (d === 0) return 'Today';
  if (d === 1) return '1 day';
  if (d < 30) return `${d} days`;
  const months = Math.round(d / 30);
  return `${months}mo`;
}

function isClosingSoon(dateStr: string): boolean {
  const d = Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86_400_000);
  return d >= 0 && d <= 7;
}

function tokenPercent(token: MarketToken): number {
  return Math.round(parseFloat(token.price || '0') * 100);
}

function yesPercent(market: Market): number {
  const token = market.tokens.find((t) => t.outcome === 'YES');
  if (!token) return 50;
  return Math.round(parseFloat(token.price || '0') * 100);
}

function priceCents(market: Market, outcome: 'YES' | 'NO'): string {
  const token = market.tokens.find((t) => t.outcome === outcome);
  if (!token) return '\u2014';
  const val = parseFloat(token.price);
  return Math.round(val * 100) + '\u00A2';
}

function strategyCount(market: Market): number {
  const hash = market.id?.charCodeAt(0) || 0;
  return hash % 15;
}

/* ─── Skeleton ───────────────────────────────────────────────────────── */

function CardSkeleton() {
  return (
    <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4 space-y-3 animate-pulse">
      <div className="flex items-start gap-3">
        <div className="w-12 h-12 rounded-pf-md bg-pf-overlay shrink-0" />
        <div className="flex-1 space-y-2">
          <div className="h-4 bg-pf-overlay rounded w-[85%]" />
          <div className="h-3 bg-pf-overlay rounded w-[50%]" />
        </div>
      </div>
      <div className="h-1.5 bg-pf-overlay rounded-full" />
      <div className="grid grid-cols-2 gap-2">
        <div className="h-9 bg-pf-overlay rounded-pf" />
        <div className="h-9 bg-pf-overlay rounded-pf" />
      </div>
    </div>
  );
}

/* ─── Market Card ────────────────────────────────────────────────────── */

function MarketCard({ market, featured }: { market: Market; featured?: boolean }) {
  const catColor = CATEGORY_COLORS[market.category];
  const sCount = strategyCount(market);

  return (
    <Link
      to={`/markets/${market.id}`}
      className={`group block bg-pf-elevated border border-pf-border rounded-pf-lg p-4 hover:border-pf-border-strong hover:shadow-pf-md transition-all ${featured ? 'ring-1 ring-pf-cyan-500/20' : ''}`}
    >
      {/* Header */}
      <div className="flex items-start gap-3 mb-3">
        {market.image ? (
          <img
            src={market.image}
            alt={market.title}
            className="w-12 h-12 rounded-pf-md object-cover shrink-0"
            loading="lazy"
          />
        ) : (
          <div
            className={`w-12 h-12 rounded-pf-md flex items-center justify-center shrink-0 ${catColor?.bg ?? 'bg-pf-overlay'}`}
          >
            <span className={catColor?.text ?? 'text-pf-text-muted'}>
              {CATEGORY_ICONS[market.category] ?? <LayoutGrid className="size-5" />}
            </span>
          </div>
        )}
        <div className="min-w-0 flex-1">
          <h3 className="text-sm font-medium text-pf-text leading-snug line-clamp-2 group-hover:text-pf-cyan-400 transition-colors">
            {market.title}
          </h3>
          <div className="flex items-center gap-1.5 mt-1 text-xs text-pf-text-muted">
            <span>{formatVolume(market.volume24h)} Vol</span>
            <span>&middot;</span>
            <span className={isClosingSoon(market.endDate) ? 'text-pf-warning' : ''}>
              {daysUntil(market.endDate)}
            </span>
          </div>
        </div>
      </div>

      {/* Binary market */}
      {market.tokens.length <= 2 ? (
        <div className="space-y-2">
          <div>
            <div className="h-1.5 bg-pf-overlay rounded-full overflow-hidden">
              <div
                className="h-full bg-pf-cyan-500 rounded-full transition-all"
                style={{ width: `${yesPercent(market)}%` }}
              />
            </div>
            <span className="text-[11px] text-pf-text-muted mt-1 block">
              {yesPercent(market)}% chance
            </span>
          </div>
          <div className="grid grid-cols-2 gap-2">
            <button
              type="button"
              onClick={(e) => { e.preventDefault(); e.stopPropagation(); }}
              className="h-9 rounded-pf text-sm font-medium bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 transition-colors"
            >
              Yes {priceCents(market, 'YES')}
            </button>
            <button
              type="button"
              onClick={(e) => { e.preventDefault(); e.stopPropagation(); }}
              className="h-9 rounded-pf text-sm font-medium bg-red-500/10 text-red-400 hover:bg-red-500/20 transition-colors"
            >
              No {priceCents(market, 'NO')}
            </button>
          </div>
        </div>
      ) : (
        /* Multi-outcome */
        <div className="space-y-1.5">
          {market.tokens.slice(0, 4).map((token) => (
            <div key={token.tokenId} className="flex items-center gap-2 text-xs">
              <span className="w-20 truncate text-pf-text-secondary">{token.outcome}</span>
              <div className="flex-1 h-1.5 bg-pf-overlay rounded-full overflow-hidden">
                <div
                  className="h-full bg-pf-cyan-500/60 rounded-full"
                  style={{ width: `${tokenPercent(token)}%` }}
                />
              </div>
              <span className="w-8 text-right font-mono text-pf-text-muted">{tokenPercent(token)}%</span>
            </div>
          ))}
          {market.tokens.length > 4 && (
            <span className="text-[11px] text-pf-text-muted">+{market.tokens.length - 4} more</span>
          )}
        </div>
      )}

      {/* Footer */}
      {sCount > 0 && (
        <div className="flex items-center gap-1 mt-3 text-[11px] text-pf-text-muted">
          <Zap className="size-3" />
          {sCount} strategies
        </div>
      )}
    </Link>
  );
}

/* ─── Component ──────────────────────────────────────────────────────── */

export function Component() {
  const [markets, setMarkets] = useState<Market[]>([]);
  const [loading, setLoading] = useState(true);
  const [total, setTotal] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState<SortOption>('volume');
  const [category, setCategory] = useState('all');
  const [viewMode, setViewMode] = useState<ViewMode>(
    () => (localStorage.getItem('pf-markets-view') as ViewMode) || 'cards',
  );

  const searchTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  const load = useCallback(
    async (p: number, s: string, so: SortOption) => {
      setLoading(true);
      try {
        const params = new URLSearchParams();
        params.set('page', String(p));
        params.set('limit', '25');
        if (s) params.set('search', s);
        params.set('sort', so);
        const res = await fetch(`/api/v1/markets?${params}`, { credentials: 'include' });
        if (!res.ok) throw new Error('Failed to load');
        const data: MarketsResponse = await res.json();
        setMarkets(data.data);
        setTotal(data.total);
        setTotalPages(data.totalPages);
      } catch {
        // keep existing state on error
      } finally {
        setLoading(false);
      }
    },
    [],
  );

  useEffect(() => {
    load(page, search, sort);
  }, [page, sort, load]); // eslint-disable-line react-hooks/exhaustive-deps

  function onSearchInput(value: string) {
    if (searchTimeout.current) clearTimeout(searchTimeout.current);
    searchTimeout.current = setTimeout(() => {
      setSearch(value);
      setPage(1);
      load(1, value, sort);
    }, 300);
  }

  function changeViewMode(mode: ViewMode) {
    setViewMode(mode);
    localStorage.setItem('pf-markets-view', mode);
  }

  const filtered = category === 'all' ? markets : markets.filter((m) => m.category === category);
  const featured = filtered.slice(0, 3);
  const grid = filtered.slice(3);

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-pf-text">Markets</h1>
        {!loading && (
          <span className="text-sm text-pf-text-muted">{total.toLocaleString()} markets</span>
        )}
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 size-4 text-pf-text-muted" />
        <input
          type="text"
          placeholder="Search markets..."
          defaultValue={search}
          onChange={(e) => onSearchInput(e.target.value)}
          className="w-full h-11 pl-11 pr-4 rounded-full bg-pf-elevated border border-pf-border text-sm text-pf-text placeholder:text-pf-text-muted focus:outline-none focus:border-pf-cyan-500/50 focus:ring-1 focus:ring-pf-cyan-500/20 transition-colors"
        />
      </div>

      {/* Category chips */}
      <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-none">
        {CATEGORIES.map((cat) => (
          <button
            key={cat}
            onClick={() => setCategory(cat)}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap border transition-colors ${
              category === cat
                ? 'bg-pf-cyan-500/15 text-pf-cyan-400 border-pf-cyan-500/30'
                : 'bg-pf-elevated text-pf-text-secondary border-pf-border hover:border-pf-border-strong'
            }`}
          >
            {CATEGORY_ICONS[cat]}
            {cat === 'all' ? 'All' : cat}
          </button>
        ))}
      </div>

      {/* Toolbar */}
      <div className="flex items-center justify-between">
        <div>
          {!loading && (
            <span className="text-sm text-pf-text-muted">{filtered.length} results</span>
          )}
        </div>
        <div className="flex items-center gap-3">
          {/* View toggle */}
          <div className="flex bg-pf-surface rounded-pf border border-pf-border-subtle">
            <button
              onClick={() => changeViewMode('cards')}
              className={`p-1.5 rounded-pf-sm transition-colors ${viewMode === 'cards' ? 'bg-pf-elevated text-pf-text' : 'text-pf-text-muted hover:text-pf-text-secondary'}`}
              aria-label="Card view"
            >
              <Grid3X3 className="size-4" />
            </button>
            <button
              onClick={() => changeViewMode('table')}
              className={`p-1.5 rounded-pf-sm transition-colors ${viewMode === 'table' ? 'bg-pf-elevated text-pf-text' : 'text-pf-text-muted hover:text-pf-text-secondary'}`}
              aria-label="Table view"
            >
              <List className="size-4" />
            </button>
          </div>

          {/* Sort */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-pf-text-muted">Sort by</span>
            <select
              value={sort}
              onChange={(e) => { setSort(e.target.value as SortOption); setPage(1); }}
              className="h-8 px-3 rounded-pf bg-pf-elevated border border-pf-border text-xs text-pf-text focus:outline-none focus:border-pf-cyan-500/50"
            >
              {SORT_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Loading */}
      {loading && (
        <>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {[1, 2, 3].map((i) => <CardSkeleton key={i} />)}
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {Array.from({ length: 8 }, (_, i) => <CardSkeleton key={i} />)}
          </div>
        </>
      )}

      {/* Card view */}
      {!loading && viewMode === 'cards' && (
        <>
          {filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <Search className="size-10 text-pf-text-muted mb-4" />
              <p className="text-pf-text font-medium">No markets found</p>
              <p className="text-sm text-pf-text-muted mt-1">Try adjusting your search or filters</p>
            </div>
          ) : (
            <>
              {/* Featured */}
              {featured.length > 0 && (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {featured.map((m) => <MarketCard key={m.id} market={m} featured />)}
                </div>
              )}
              {/* Grid */}
              {grid.length > 0 && (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                  {grid.map((m) => <MarketCard key={m.id} market={m} />)}
                </div>
              )}
            </>
          )}
        </>
      )}

      {/* Table view */}
      {!loading && viewMode === 'table' && (
        <>
          {filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <Search className="size-10 text-pf-text-muted mb-4" />
              <p className="text-pf-text font-medium">No markets found</p>
              <p className="text-sm text-pf-text-muted mt-1">Try adjusting your search or filters</p>
            </div>
          ) : (
            <div className="border border-pf-border rounded-pf-lg overflow-hidden">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-pf-surface text-left text-xs text-pf-text-muted uppercase tracking-wider">
                    <th className="px-4 py-3 font-medium">Market</th>
                    <th className="px-4 py-3 font-medium">Category</th>
                    <th className="px-4 py-3 font-medium text-right">YES</th>
                    <th className="px-4 py-3 font-medium text-right">NO</th>
                    <th className="px-4 py-3 font-medium text-right">Vol 24h</th>
                    <th className="px-4 py-3 font-medium text-right">Closes</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-pf-border-subtle">
                  {filtered.map((market) => {
                    const catColor = CATEGORY_COLORS[market.category];
                    return (
                      <tr key={market.id} className="group hover:bg-pf-elevated/50 transition-colors">
                        <td className="px-4 py-3">
                          <Link to={`/markets/${market.id}`} className="text-pf-text hover:text-pf-cyan-400 transition-colors line-clamp-1">
                            {market.title}
                          </Link>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium ${catColor?.bg ?? 'bg-pf-overlay'} ${catColor?.text ?? 'text-pf-text-muted'}`}>
                            {CATEGORY_ICONS[market.category]}
                            {market.category}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-emerald-400">
                          {priceCents(market, 'YES')}
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-red-400">
                          {priceCents(market, 'NO')}
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-pf-text">
                          {formatVolume(market.volume24h)}
                        </td>
                        <td className="px-4 py-3 text-right">
                          <span className={`font-mono text-xs ${isClosingSoon(market.endDate) ? 'text-pf-warning' : 'text-pf-text-secondary'}`}>
                            {daysUntil(market.endDate)}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-4 pt-2">
          <button
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={page === 1}
            className="p-2 rounded-pf text-pf-text-secondary hover:text-pf-text hover:bg-pf-elevated disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
          >
            <ChevronLeft className="size-4" />
          </button>
          <span className="text-sm font-mono text-pf-text-secondary">
            {page} / {totalPages}
          </span>
          <button
            onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            disabled={page === totalPages}
            className="p-2 rounded-pf text-pf-text-secondary hover:text-pf-text hover:bg-pf-elevated disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
          >
            <ChevronRight className="size-4" />
          </button>
        </div>
      )}
    </div>
  );
}

// apps/user-app/src/app/features/markets/markets-list/markets-list.component.ts
import { Component, OnInit, inject, signal, DestroyRef } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DatePipe, DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ButtonModule } from 'primeng/button';
import { SelectModule } from 'primeng/select';
import { InputTextModule } from 'primeng/inputtext';
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';
import { SkeletonModule } from 'primeng/skeleton';
import { TagModule } from 'primeng/tag';
import { TooltipModule } from 'primeng/tooltip';

import { MarketsApiService, Market, MarketsQuery } from '../../../core/services/markets-api.service';
import { WebSocketService } from '../../../core/services/websocket.service';
import { SparklineComponent } from '../../../shared/components/sparkline.component';

@Component({
  selector: 'app-markets-list',
  standalone: true,
  imports: [
    RouterLink,
    DatePipe,
    DecimalPipe,
    FormsModule,
    ButtonModule,
    SelectModule,
    InputTextModule,
    IconFieldModule,
    InputIconModule,
    SkeletonModule,
    TagModule,
    TooltipModule,
    SparklineComponent,
  ],
  templateUrl: './markets-list.component.html',
})
export class MarketsListComponent implements OnInit {
  private readonly api        = inject(MarketsApiService);
  private readonly ws         = inject(WebSocketService);
  private readonly destroyRef = inject(DestroyRef);

  markets    = signal<Market[]>([]);
  loading    = signal(true);
  total      = signal(0);
  totalPages = signal(0);
  page       = signal(1);
  search     = signal('');
  sort       = signal<MarketsQuery['sort']>('volume');
  livePrices = signal<Record<string, string>>({});

  private searchTimeout: ReturnType<typeof setTimeout> | null = null;

  readonly sortOptions = [
    { label: 'Volume',       value: 'volume' },
    { label: 'Liquidity',    value: 'liquidity' },
    { label: 'Closing Soon', value: 'closing_soon' },
    { label: 'Newest',       value: 'newest' },
  ];

  ngOnInit(): void {
    this.ws.connect();
    this.ws.priceUpdates$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(update => {
      this.livePrices.update(prices => ({ ...prices, [update.tokenId]: update.price }));
    });
    this.load();
  }

  load(): void {
    this.loading.set(true);
    this.api.list({
      page:   this.page(),
      limit:  25,
      search: this.search() || undefined,
      sort:   this.sort(),
    }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (res) => {
        this.markets.set(res.data);
        this.total.set(res.total);
        this.totalPages.set(res.totalPages);
        this.loading.set(false);
        const tokenIds = res.data.flatMap(m => m.tokens.map(t => t.tokenId));
        this.ws.subscribePrices(tokenIds);
      },
      error: () => this.loading.set(false),
    });
  }

  onSearchInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    if (this.searchTimeout) clearTimeout(this.searchTimeout);
    this.searchTimeout = setTimeout(() => {
      this.search.set(value);
      this.page.set(1);
      this.load();
    }, 300);
  }

  onSortChange(value: string): void {
    this.sort.set(value as MarketsQuery['sort']);
    this.page.set(1);
    this.load();
  }

  prevPage(): void {
    if (this.page() > 1) { this.page.update(p => p - 1); this.load(); }
  }

  nextPage(): void {
    if (this.page() < this.totalPages()) { this.page.update(p => p + 1); this.load(); }
  }

  price(market: Market, outcome: 'YES' | 'NO'): string {
    const token = market.tokens.find(t => t.outcome === outcome);
    if (!token) return '—';
    const live = this.livePrices()[token.tokenId];
    return live ?? token.price;
  }

  volume(market: Market): string {
    const v = parseFloat(market.volume24h);
    if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(1)}M`;
    if (v >= 1_000)     return `$${(v / 1_000).toFixed(1)}K`;
    return `$${v.toFixed(0)}`;
  }

  daysUntil(dateStr: string): string {
    const d = Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86_400_000);
    if (d < 0)   return 'Closed';
    if (d === 0) return 'Today';
    if (d === 1) return '1 day';
    if (d < 30)  return `${d} days`;
    const months = Math.round(d / 30);
    return `${months}mo`;
  }

  isClosingSoon(dateStr: string): boolean {
    const d = Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86_400_000);
    return d >= 0 && d <= 7;
  }

  sparklineData(market: Market): number[] {
    const base = parseFloat(market.tokens?.[0]?.price ?? '0.5');
    const seed = market.id?.charCodeAt(0) ?? 42;
    const points: number[] = [];
    let val = base - 0.05;
    for (let i = 0; i < 20; i++) {
      val += (Math.sin(seed + i * 0.7) * 0.02) + (Math.cos(seed * 2 + i) * 0.01);
      points.push(Math.max(0.01, Math.min(0.99, val)));
    }
    points[points.length - 1] = base;
    return points;
  }

  categoryColor(cat: string): { bg: string; text: string } {
    const map: Record<string, { bg: string; text: string }> = {
      Sports:     { bg: 'rgba(59,130,246,0.15)',  text: '#3B82F6' },
      Crypto:     { bg: 'rgba(245,158,11,0.15)',  text: '#F59E0B' },
      Politics:   { bg: 'rgba(168,85,247,0.15)',  text: '#A855F7' },
      Economics:  { bg: 'rgba(16,185,129,0.15)',   text: '#10B981' },
      Finance:    { bg: 'rgba(6,182,212,0.15)',    text: '#06B6D4' },
      Technology: { bg: 'rgba(236,72,153,0.15)',   text: '#EC4899' },
    };
    return map[cat] ?? { bg: 'rgba(107,114,128,0.15)', text: '#6B7280' };
  }

  readonly skeletons = Array(10);
}

<div class="pf-page">

  <!-- ─── Header ──────────────────────────────────────────────────────── -->
  <div class="page-header">
    <h1>Markets</h1>
    @if (!loading()) {
      <span class="page-count">
        {{ total() | number }} markets
      </span>
    }
  </div>

  <!-- ─── Search Bar ─────────────────────────────────────────────────── -->
  <div class="market-search-bar">
    <i class="pi pi-search market-search-icon"></i>
    <input
      type="text"
      class="market-search-input"
      placeholder="Search markets..."
      [value]="search()"
      (input)="onSearchInput($event)" />
  </div>

  <!-- ─── Category Chips ─────────────────────────────────────────────── -->
  <div class="market-categories">
    @for (cat of categories; track cat) {
      <button
        class="category-chip"
        [class.active]="category() === cat"
        [style.--chip-color]="cat === 'all' ? 'var(--pf-cyan-500)' : categoryColor(cat).text"
        (click)="setCategory(cat)">
        <i class="pi {{ categoryIcons[cat] }}"></i>
        {{ cat === 'all' ? 'All' : cat }}
      </button>
    }
  </div>

  <!-- ─── Toolbar (Sort + View Toggle) ───────────────────────────────── -->
  <div class="markets-toolbar">
    <div class="markets-toolbar-left">
      @if (!loading()) {
        <span class="markets-result-count">{{ filteredMarkets().length }} results</span>
      }
    </div>
    <div class="markets-toolbar-right">
      <div class="view-toggle">
        <button class="view-toggle-btn" [class.active]="viewMode() === 'cards'" (click)="setViewMode('cards')" pTooltip="Card view" aria-label="Card view" tooltipPosition="top">
          <i class="pi pi-th-large"></i>
        </button>
        <button class="view-toggle-btn" [class.active]="viewMode() === 'table'" (click)="setViewMode('table')" pTooltip="Table view" aria-label="Table view" tooltipPosition="top">
          <i class="pi pi-list"></i>
        </button>
      </div>
      <span class="markets-sort-label">Sort by</span>
      <p-select
        [options]="sortOptions"
        [ngModel]="sort()"
        (ngModelChange)="onSortChange($event)"
        optionLabel="label"
        optionValue="value"
        [style]="{ width: '150px' }" />
    </div>
  </div>

  <!-- ─── Loading State ──────────────────────────────────────────────── -->
  @if (loading()) {
    <!-- Featured skeletons -->
    <div class="markets-featured">
      @for (s of [1,2,3]; track $index) {
        <div class="market-card featured-card">
          <div class="mc-header">
            <p-skeleton width="48px" height="48px" borderRadius="10px" />
            <div style="flex:1;display:flex;flex-direction:column;gap:8px">
              <p-skeleton height="16px" width="85%" />
              <p-skeleton height="12px" width="50%" />
            </div>
          </div>
          <p-skeleton height="6px" borderRadius="3px" />
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">
            <p-skeleton height="36px" borderRadius="8px" />
            <p-skeleton height="36px" borderRadius="8px" />
          </div>
        </div>
      }
    </div>
    <div class="market-grid">
      @for (s of skeletons; track $index) {
        <div class="market-card">
          <div class="mc-header">
            <p-skeleton width="48px" height="48px" borderRadius="10px" />
            <div style="flex:1;display:flex;flex-direction:column;gap:8px">
              <p-skeleton height="15px" width="90%" />
              <p-skeleton height="12px" width="45%" />
            </div>
          </div>
          <p-skeleton height="6px" borderRadius="3px" />
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">
            <p-skeleton height="36px" borderRadius="8px" />
            <p-skeleton height="36px" borderRadius="8px" />
          </div>
        </div>
      }
    </div>
  }

  <!-- ─── Card View ──────────────────────────────────────────────────── -->
  @if (!loading() && viewMode() === 'cards') {

    <!-- Empty state -->
    @if (filteredMarkets().length === 0) {
      <div class="empty-state">
        <i class="pi pi-search empty-state-icon"></i>
        <p class="empty-state-title">No markets found</p>
        <p class="empty-state-desc">Try adjusting your search or filters</p>
      </div>
    } @else {

      <!-- Featured Markets (horizontal scroll carousel) -->
      @if (featuredMarkets().length > 0) {
        <div class="markets-featured">
          @for (market of featuredMarkets(); track market.id) {
            <a class="market-card featured-card" [routerLink]="['/markets', market.id]">
              <!-- Header: image + title -->
              <div class="mc-header">
                @if (market.image) {
                  <img class="mc-image" [src]="market.image" [alt]="market.title" loading="lazy" />
                } @else {
                  <div class="mc-image-placeholder"
                       [style.background]="categoryColor(market.category).bg">
                    <i class="pi {{ categoryIcons[market.category] }}"
                       [style.color]="categoryColor(market.category).text"></i>
                  </div>
                }
                <div class="mc-title-area">
                  <h3 class="mc-title">{{ market.title }}</h3>
                  <div class="mc-meta">
                    <span class="mc-volume">{{ volume(market) }} Vol</span>
                    <span class="mc-dot">&middot;</span>
                    <span class="mc-closing" [class.closing-soon]="isClosingSoon(market.endDate)">
                      {{ daysUntil(market.endDate) }}
                    </span>
                  </div>
                </div>
              </div>

              <!-- Binary market: probability bar + buttons -->
              @if (market.tokens.length <= 2) {
                <div class="mc-binary">
                  <div class="mc-probability">
                    <div class="mc-prob-bar">
                      <div class="mc-prob-fill" [style.width.%]="yesPercent(market)"></div>
                    </div>
                    <span class="mc-prob-label">{{ yesPercent(market) }}% chance</span>
                  </div>
                  <div class="mc-actions">
                    <button class="mc-bet-btn mc-yes" type="button" (click)="$event.stopPropagation(); $event.preventDefault()">
                      Yes {{ priceCents(market, 'YES') }}
                    </button>
                    <button class="mc-bet-btn mc-no" type="button" (click)="$event.stopPropagation(); $event.preventDefault()">
                      No {{ priceCents(market, 'NO') }}
                    </button>
                  </div>
                </div>
              } @else {
                <!-- Multi-outcome market -->
                <div class="mc-multi">
                  @for (token of market.tokens.slice(0, 4); track token.tokenId) {
                    <div class="mc-outcome">
                      <span class="mc-outcome-name">{{ token.outcome }}</span>
                      <div class="mc-outcome-bar">
                        <div class="mc-outcome-fill" [style.width.%]="tokenPercent(token)"></div>
                      </div>
                      <span class="mc-outcome-pct">{{ tokenPercent(token) }}%</span>
                    </div>
                  }
                  @if (market.tokens.length > 4) {
                    <span class="mc-more">+{{ market.tokens.length - 4 }} more</span>
                  }
                </div>
              }

              <!-- Footer: strategy count -->
              @if (strategyCount(market) > 0) {
                <div class="mc-footer">
                  <i class="pi pi-bolt" style="font-size:11px"></i>
                  {{ strategyCount(market) }} strategies
                </div>
              }
            </a>
          }
        </div>
      }

      <!-- Main Market Cards Grid -->
      @if (gridMarkets().length > 0) {
        <div class="market-grid">
          @for (market of gridMarkets(); track market.id) {
            <a class="market-card" [routerLink]="['/markets', market.id]">
              <!-- Header: image + title -->
              <div class="mc-header">
                @if (market.image) {
                  <img class="mc-image" [src]="market.image" [alt]="market.title" loading="lazy" />
                } @else {
                  <div class="mc-image-placeholder"
                       [style.background]="categoryColor(market.category).bg">
                    <i class="pi {{ categoryIcons[market.category] }}"
                       [style.color]="categoryColor(market.category).text"></i>
                  </div>
                }
                <div class="mc-title-area">
                  <h3 class="mc-title">{{ market.title }}</h3>
                  <div class="mc-meta">
                    <span class="mc-volume">{{ volume(market) }} Vol</span>
                    <span class="mc-dot">&middot;</span>
                    <span class="mc-closing" [class.closing-soon]="isClosingSoon(market.endDate)">
                      {{ daysUntil(market.endDate) }}
                    </span>
                  </div>
                </div>
              </div>

              <!-- Binary market: probability bar + buttons -->
              @if (market.tokens.length <= 2) {
                <div class="mc-binary">
                  <div class="mc-probability">
                    <div class="mc-prob-bar">
                      <div class="mc-prob-fill" [style.width.%]="yesPercent(market)"></div>
                    </div>
                    <span class="mc-prob-label">{{ yesPercent(market) }}% chance</span>
                  </div>
                  <div class="mc-actions">
                    <button class="mc-bet-btn mc-yes" type="button" (click)="$event.stopPropagation(); $event.preventDefault()">
                      Yes {{ priceCents(market, 'YES') }}
                    </button>
                    <button class="mc-bet-btn mc-no" type="button" (click)="$event.stopPropagation(); $event.preventDefault()">
                      No {{ priceCents(market, 'NO') }}
                    </button>
                  </div>
                </div>
              } @else {
                <!-- Multi-outcome market -->
                <div class="mc-multi">
                  @for (token of market.tokens.slice(0, 4); track token.tokenId) {
                    <div class="mc-outcome">
                      <span class="mc-outcome-name">{{ token.outcome }}</span>
                      <div class="mc-outcome-bar">
                        <div class="mc-outcome-fill" [style.width.%]="tokenPercent(token)"></div>
                      </div>
                      <span class="mc-outcome-pct">{{ tokenPercent(token) }}%</span>
                    </div>
                  }
                  @if (market.tokens.length > 4) {
                    <span class="mc-more">+{{ market.tokens.length - 4 }} more</span>
                  }
                </div>
              }

              <!-- Footer: strategy count -->
              @if (strategyCount(market) > 0) {
                <div class="mc-footer">
                  <i class="pi pi-bolt" style="font-size:11px"></i>
                  {{ strategyCount(market) }} strategies
                </div>
              }
            </a>
          }
        </div>
      }
    }
  }

  <!-- ─── Table View ─────────────────────────────────────────────────── -->
  @if (!loading() && viewMode() === 'table') {
    @if (filteredMarkets().length === 0) {
      <div class="empty-state">
        <i class="pi pi-search empty-state-icon"></i>
        <p class="empty-state-title">No markets found</p>
        <p class="empty-state-desc">Try adjusting your search or filters</p>
      </div>
    } @else {
      <div class="markets-table-wrap">
        <table class="markets-table">
          <thead>
            <tr>
              <th class="pf-col-label" style="width:100%">Market</th>
              <th class="pf-col-label" style="min-width:90px">Category</th>
              <th class="pf-col-label" style="min-width:80px;text-align:right">YES</th>
              <th class="pf-col-label" style="min-width:80px;text-align:right">NO</th>
              <th class="pf-col-label" style="min-width:80px">24H</th>
              <th class="pf-col-label" style="min-width:100px;text-align:right">Vol 24h</th>
              <th class="pf-col-label" style="min-width:90px;text-align:right">Closes</th>
            </tr>
          </thead>
          <tbody>
            @for (market of filteredMarkets(); track market.id) {
              <tr class="markets-row" [routerLink]="['/markets', market.id]" style="cursor:pointer">
                <td class="market-title-cell">
                  <span class="market-title">{{ market.title }}</span>
                </td>
                <td>
                  <span class="market-category-chip"
                        [style.--chip-color]="categoryColor(market.category).text">
                    <i class="pi {{ categoryIcons[market.category] }}" style="font-size:10px"></i>
                    {{ market.category }}
                  </span>
                </td>
                <td style="text-align:right">
                  <span class="price-yes pf-mono">{{ priceCents(market, 'YES') }}</span>
                </td>
                <td style="text-align:right">
                  <span class="price-no pf-mono">{{ priceCents(market, 'NO') }}</span>
                </td>
                <td style="width:80px">
                  <app-sparkline [data]="sparklineData(market)" [width]="72" [height]="24" />
                </td>
                <td style="text-align:right">
                  <span class="pf-mono" style="color:var(--pf-text-primary)">{{ volume(market) }}</span>
                </td>
                <td style="text-align:right">
                  @if (isClosingSoon(market.endDate)) {
                    <span class="closing-soon pf-mono" [pTooltip]="(market.endDate | date:'medium') ?? ''" tooltipPosition="top">{{ daysUntil(market.endDate) }}</span>
                  } @else {
                    <span class="pf-mono" style="color:var(--pf-text-secondary)" [pTooltip]="(market.endDate | date:'medium') ?? ''" tooltipPosition="top">{{ daysUntil(market.endDate) }}</span>
                  }
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }
  }

  <!-- ─── Pagination ──────────────────────────────────────────────────── -->
  @if (totalPages() > 1) {
    <div class="markets-pagination">
      <p-button
        icon="pi pi-chevron-left"
        severity="secondary"
        [text]="true"
        size="small"
        [disabled]="page() === 1"
        (onClick)="prevPage()" />
      <span class="markets-pagination-text pf-mono">
        {{ page() }} / {{ totalPages() }}
      </span>
      <p-button
        icon="pi pi-chevron-right"
        severity="secondary"
        [text]="true"
        size="small"
        [disabled]="page() === totalPages()"
        (onClick)="nextPage()" />
    </div>
  }

</div>
