// apps/user-app/src/app/features/strategies/strategy-detail/strategy-detail.component.ts
import { Component, OnInit, OnDestroy, inject, signal, DestroyRef } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DatePipe, LowerCasePipe } from '@angular/common';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ButtonModule } from 'primeng/button';
import { SkeletonModule } from 'primeng/skeleton';
import { ToastModule } from 'primeng/toast';
import { TooltipModule } from 'primeng/tooltip';
import { MessageService } from 'primeng/api';

import { StrategiesApiService, Strategy, StrategyStatus } from '../../../core/services/strategies-api.service';
import { WebSocketService, StrategyEvent } from '../../../core/services/websocket.service';

interface LiveLogEntry {
  time: Date;
  type: string;
  message: string;
  severity: 'info' | 'success' | 'warning' | 'error';
}

@Component({
  selector: 'app-strategy-detail',
  standalone: true,
  imports: [RouterLink, DatePipe, LowerCasePipe, ButtonModule, SkeletonModule, ToastModule, TooltipModule],
  providers: [MessageService],
  templateUrl: './strategy-detail.component.html',
})
export class StrategyDetailComponent implements OnInit, OnDestroy {
  private readonly route      = inject(ActivatedRoute);
  private readonly api        = inject(StrategiesApiService);
  private readonly ws         = inject(WebSocketService);
  private readonly toast      = inject(MessageService);
  private readonly destroyRef = inject(DestroyRef);

  strategy      = signal<Strategy | null>(null);
  loading       = signal(true);
  notFound      = signal(false);
  loadError     = signal<string | null>(null);
  actionLoading = signal(false);
  liveLog       = signal<LiveLogEntry[]>([]);

  private strategyId = '';

  ngOnInit(): void {
    this.strategyId = this.route.snapshot.paramMap.get('id')!;
    this.ws.connect();

    this.api.get(this.strategyId).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  s  => { this.strategy.set(s); this.loading.set(false); },
      error: err => {
        this.loading.set(false);
        if (err?.status === 404) {
          this.notFound.set(true);
        } else if (err?.status === 403) {
          this.loadError.set('You do not have permission to view this strategy.');
        } else {
          this.loadError.set('Failed to load strategy. Please try again.');
        }
      },
    });

    this.ws.subscribeStrategy(this.strategyId);

    this.ws.strategyEvents$.pipe(
      takeUntilDestroyed(this.destroyRef),
    ).subscribe(event => {
      if (event.strategyId !== this.strategyId) return;
      this.handleStrategyEvent(event);
    });
  }

  private handleStrategyEvent(event: StrategyEvent): void {
    const entry = this.toLogEntry(event);
    this.liveLog.update(log => [entry, ...log].slice(0, 100));

    const statusMap: Partial<Record<string, StrategyStatus>> = {
      STRATEGY_STARTED: 'RUNNING',
      STRATEGY_STOPPED: 'IDLE',
      STRATEGY_PAUSED:  'PAUSED',
      STRATEGY_RESUMED: 'RUNNING',
      STRATEGY_ERROR:   'ERROR',
    };
    const newStatus = statusMap[event.type];
    if (newStatus) {
      this.strategy.update(s => s ? { ...s, status: newStatus } : s);
    }
  }

  private toLogEntry(event: StrategyEvent): LiveLogEntry {
    const severityMap: Record<string, LiveLogEntry['severity']> = {
      STRATEGY_STARTED: 'success',
      STRATEGY_STOPPED: 'info',
      STRATEGY_PAUSED:  'warning',
      STRATEGY_RESUMED: 'success',
      STRATEGY_ERROR:   'error',
    };
    const messageMap: Record<string, string> = {
      STRATEGY_STARTED: 'Strategy started',
      STRATEGY_STOPPED: `Strategy stopped${event.reason ? ` · ${event.reason}` : ''}`,
      STRATEGY_PAUSED:  `Strategy paused${event.reason ? ` · ${event.reason}` : ''}`,
      STRATEGY_RESUMED: 'Strategy resumed',
      STRATEGY_ERROR:   `Error in ${event.blockType ?? 'block'}: ${event.error ?? 'Unknown error'}`,
    };
    return {
      time:     new Date(),
      type:     event.type,
      message:  messageMap[event.type] ?? event.type,
      severity: severityMap[event.type] ?? 'info',
    };
  }

  start(mode: 'live' | 'paper'): void {
    const s = this.strategy();
    if (!s) return;
    this.actionLoading.set(true);
    this.api.start(s.id, mode).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  res => { this.strategy.update(st => st ? { ...st, status: res.status } : st); this.actionLoading.set(false); },
      error: err => {
        this.actionLoading.set(false);
        this.toast.add({ severity: 'error', summary: 'Start failed', detail: err?.error?.message ?? 'Unknown error', life: 4000 });
      },
    });
  }

  stop(): void {
    const s = this.strategy();
    if (!s) return;
    this.actionLoading.set(true);
    this.api.stop(s.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  res => { this.strategy.update(st => st ? { ...st, status: res.status } : st); this.actionLoading.set(false); },
      error: ()  => this.actionLoading.set(false),
    });
  }

  pause(): void {
    const s = this.strategy();
    if (!s) return;
    this.actionLoading.set(true);
    this.api.pause(s.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  res => { this.strategy.update(st => st ? { ...st, status: res.status } : st); this.actionLoading.set(false); },
      error: ()  => this.actionLoading.set(false),
    });
  }

  resume(): void {
    const s = this.strategy();
    if (!s) return;
    this.actionLoading.set(true);
    this.api.resume(s.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next:  res => { this.strategy.update(st => st ? { ...st, status: res.status } : st); this.actionLoading.set(false); },
      error: ()  => this.actionLoading.set(false),
    });
  }

  isActive(status: StrategyStatus): boolean { return status === 'RUNNING' || status === 'PAPER'; }
  isPaused(status: StrategyStatus): boolean { return status === 'PAUSED'; }
  isIdle(status: StrategyStatus):   boolean { return status === 'IDLE' || status === 'ERROR'; }

  blockLabel(type: string): string {
    return type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }

  execLabel(s: Strategy): string {
    if (s.execMode === 'TICK')  return `Tick · ${s.tickMs}ms`;
    if (s.execMode === 'EVENT') return 'Event';
    return `Hybrid · ${s.tickMs}ms`;
  }

  logColor(severity: LiveLogEntry['severity']): string {
    const map = { success: 'var(--pf-success)', info: 'var(--pf-cyan-500)', warning: 'var(--pf-warning)', error: 'var(--pf-danger)' };
    return map[severity];
  }

  ngOnDestroy(): void {
    this.ws.unsubscribeStrategy(this.strategyId);
  }
}

<p-toast position="top-right" />

<div class="pf-page">

  <!-- Back -->
  <div style="margin-bottom:16px">
    <a routerLink="/strategies" style="font-size:13px;color:var(--pf-text-secondary);text-decoration:none;display:inline-flex;align-items:center;gap:6px">
      <i class="pi pi-arrow-left" style="font-size:12px"></i> Strategies
    </a>
  </div>

  @if (loading()) {
    <p-skeleton height="28px" width="40%" styleClass="mb-3" />
    <p-skeleton height="14px" width="60%" />
  } @else if (strategy(); as s) {

    <!-- ─── Header ─────────────────────────────────────────────────────── -->
    <div class="detail-header">
      <div>
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:6px">
          <h1 style="font-size:22px;font-weight:600;margin:0">{{ s.name }}</h1>
          <span class="status-badge {{ s.status | lowercase }}">
            <span class="status-dot"></span>{{ s.status }}
          </span>
        </div>
        @if (s.description) {
          <p style="font-size:14px;color:var(--pf-text-secondary);margin:0">{{ s.description }}</p>
        }
      </div>

      <!-- Actions -->
      <div style="display:flex;gap:8px;flex-shrink:0;align-items:flex-start">
        @if (isIdle(s.status)) {
          <p-button label="Start Live"  icon="pi pi-bolt"      [loading]="actionLoading()" (onClick)="start('live')" />
          <p-button label="Start Paper" icon="pi pi-file"      severity="secondary" [loading]="actionLoading()" (onClick)="start('paper')" />
        }
        @if (isActive(s.status)) {
          <p-button label="Pause" icon="pi pi-pause"           severity="secondary" [loading]="actionLoading()" (onClick)="pause()" />
          <p-button label="Stop"  icon="pi pi-stop-circle"     severity="danger"    [text]="true" [loading]="actionLoading()" (onClick)="stop()" />
        }
        @if (isPaused(s.status)) {
          <p-button label="Resume" icon="pi pi-play"           [loading]="actionLoading()" (onClick)="resume()" />
          <p-button label="Stop"   icon="pi pi-stop-circle"    severity="danger"    [text]="true" [loading]="actionLoading()" (onClick)="stop()" />
        }
        <p-button icon="pi pi-pencil" severity="secondary" pTooltip="Edit" [routerLink]="['/strategies', s.id, 'edit']" />
      </div>
    </div>

    <!-- ─── Meta chips ──────────────────────────────────────────────────── -->
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:24px">
      <span class="meta-chip">{{ execLabel(s) }}</span>
      <span class="meta-chip">v{{ s.version }}</span>
      <span class="meta-chip">{{ s.visibility | lowercase }}</span>
      <span class="meta-chip">{{ s.safety.length + s.triggers.length + s.conditions.length + s.actions.length }} blocks</span>
      @for (tag of s.tags; track tag) {
        <span class="meta-chip tag-chip">{{ tag }}</span>
      }
      <span class="meta-chip" style="margin-left:auto;color:var(--pf-text-muted)">
        Updated {{ s.updatedAt | date:'MMM d, y' }}
      </span>
    </div>

    <!-- ─── Body grid ───────────────────────────────────────────────────── -->
    <div class="detail-grid">

      <!-- Blocks summary -->
      <div class="detail-blocks-panel">

        @if (s.safety.length > 0) {
          <div class="blocks-section">
            <div class="blocks-section-title">Safety</div>
            @for (b of s.safety; track $index) {
              <div class="block-chip safety">
                <i class="pi pi-shield" style="font-size:12px"></i>
                {{ blockLabel(b.type) }}
              </div>
            }
          </div>
        }

        @if (s.triggers.length > 0) {
          <div class="blocks-section">
            <div class="blocks-section-title">Triggers</div>
            @for (b of s.triggers; track $index) {
              <div class="block-chip trigger">
                <i class="pi pi-bolt" style="font-size:12px"></i>
                {{ blockLabel(b.type) }}
              </div>
            }
          </div>
        }

        @if (s.conditions.length > 0) {
          <div class="blocks-section">
            <div class="blocks-section-title">Conditions</div>
            @for (b of s.conditions; track $index) {
              <div class="block-chip condition">
                <i class="pi pi-filter" style="font-size:12px"></i>
                {{ blockLabel(b.type) }}
              </div>
            }
          </div>
        }

        @if (s.actions.length > 0) {
          <div class="blocks-section">
            <div class="blocks-section-title">Actions</div>
            @for (b of s.actions; track $index) {
              <div class="block-chip action">
                <i class="pi pi-play-circle" style="font-size:12px"></i>
                {{ blockLabel(b.type) }}
              </div>
            }
          </div>
        }

        @if (s.safety.length + s.triggers.length + s.conditions.length + s.actions.length === 0) {
          <div class="pf-empty-state" style="padding:24px">
            <p class="pf-empty-desc">No blocks configured.</p>
            <p-button label="Edit Strategy" icon="pi pi-pencil" size="small" severity="secondary" [routerLink]="['/strategies', s.id, 'edit']" />
          </div>
        }

      </div>

      <!-- Live log -->
      <div class="detail-log-panel">
        <div class="panel-header">
          <span class="panel-title">Live Events</span>
          @if (isActive(s.status)) {
            <span style="display:flex;align-items:center;gap:6px;font-size:12px;color:var(--pf-cyan-500)">
              <span class="status-dot" style="animation:pf-pulse 2s ease-in-out infinite;background:var(--pf-cyan-500);box-shadow:0 0 6px rgba(6,182,212,0.8)"></span>
              Live
            </span>
          }
        </div>

        <div class="log-body">
          @if (liveLog().length === 0) {
            <div style="padding:24px;text-align:center;color:var(--pf-text-muted);font-size:13px">
              @if (isActive(s.status)) {
                Waiting for events…
              } @else {
                Start the strategy to see live events.
              }
            </div>
          }
          @for (entry of liveLog(); track entry.time) {
            <div class="log-entry">
              <span class="log-time pf-mono">{{ entry.time | date:'HH:mm:ss' }}</span>
              <span class="log-dot" [style.background]="logColor(entry.severity)"></span>
              <span class="log-msg" [style.color]="logColor(entry.severity)">{{ entry.message }}</span>
            </div>
          }
        </div>
      </div>

    </div>

  } @else if (notFound()) {
    <div class="pf-empty-state">
      <i class="pi pi-exclamation-circle pf-empty-icon"></i>
      <p class="pf-empty-title">Strategy not found</p>
      <p class="pf-empty-desc">This strategy may have been deleted or the link is invalid.</p>
      <p-button label="Back to Strategies" severity="secondary" routerLink="/strategies" />
    </div>
  } @else if (loadError()) {
    <div class="pf-empty-state">
      <i class="pi pi-exclamation-triangle pf-empty-icon"></i>
      <p class="pf-empty-title">{{ loadError() }}</p>
      <p-button label="Back to Strategies" severity="secondary" routerLink="/strategies" />
    </div>
  }

</div>

// apps/user-app-react/src/pages/strategies/strategy-detail.tsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router';
import {
  ArrowLeft,
  Play,
  Pause,
  Square,
  Pencil,
  Zap,
  Shield,
  Filter,
  PlayCircle,
  FileText,
} from 'lucide-react';

/* ─── Types ──────────────────────────────────────────────────────────── */

type StrategyStatus = 'IDLE' | 'RUNNING' | 'PAUSED' | 'ERROR' | 'PAPER' | 'ARCHIVED';
type ExecMode = 'TICK' | 'EVENT' | 'HYBRID';

interface BlockConfig {
  type: string;
  config: Record<string, string | number>;
}

interface Strategy {
  id: string;
  name: string;
  description: string;
  visibility: string;
  execMode: ExecMode;
  tickMs: number;
  triggers: BlockConfig[];
  conditions: BlockConfig[];
  actions: BlockConfig[];
  safety: BlockConfig[];
  status: StrategyStatus;
  version: number;
  template: boolean;
  forkedFromId: string | null;
  forkCount: number;
  likeCount: number;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  totalPnl?: number;
}

interface LiveLogEntry {
  time: Date;
  type: string;
  message: string;
  severity: 'info' | 'success' | 'warning' | 'error';
}

/* ─── Helpers ────────────────────────────────────────────────────────── */

const STATUS_STYLES: Record<StrategyStatus, { dot: string; bg: string; text: string }> = {
  RUNNING:  { dot: 'bg-emerald-400', bg: 'bg-emerald-500/10', text: 'text-emerald-400' },
  PAPER:    { dot: 'bg-cyan-400',    bg: 'bg-cyan-500/10',    text: 'text-cyan-400' },
  PAUSED:   { dot: 'bg-amber-400',   bg: 'bg-amber-500/10',   text: 'text-amber-400' },
  IDLE:     { dot: 'bg-gray-400',    bg: 'bg-gray-500/10',    text: 'text-gray-400' },
  ERROR:    { dot: 'bg-red-400',     bg: 'bg-red-500/10',     text: 'text-red-400' },
  ARCHIVED: { dot: 'bg-gray-500',    bg: 'bg-gray-500/10',    text: 'text-gray-500' },
};

const LOG_COLORS: Record<LiveLogEntry['severity'], string> = {
  success: 'text-emerald-400',
  info: 'text-pf-cyan-400',
  warning: 'text-amber-400',
  error: 'text-red-400',
};

const LOG_DOT_COLORS: Record<LiveLogEntry['severity'], string> = {
  success: 'bg-emerald-400',
  info: 'bg-pf-cyan-400',
  warning: 'bg-amber-400',
  error: 'bg-red-400',
};

function blockLabel(type: string): string {
  return type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function execLabel(s: Strategy): string {
  if (s.execMode === 'TICK') return `Tick \u00B7 ${s.tickMs}ms`;
  if (s.execMode === 'EVENT') return 'Event';
  return `Hybrid \u00B7 ${s.tickMs}ms`;
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function formatPnl(value: number): string {
  const sign = value >= 0 ? '+' : '-';
  return `${sign}$${Math.abs(value).toFixed(2)}`;
}

function formatTime(d: Date): string {
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
}

function isActive(status: StrategyStatus) { return status === 'RUNNING' || status === 'PAPER'; }
function isPaused(status: StrategyStatus) { return status === 'PAUSED'; }
function isIdle(status: StrategyStatus) { return status === 'IDLE' || status === 'ERROR'; }

/* ─── Section icons ──────────────────────────────────────────────────── */

const SECTION_ICONS: Record<string, React.ReactNode> = {
  safety: <Shield className="size-3" />,
  trigger: <Zap className="size-3" />,
  condition: <Filter className="size-3" />,
  action: <PlayCircle className="size-3" />,
};

const SECTION_STYLES: Record<string, string> = {
  safety: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  trigger: 'bg-pf-cyan-500/10 text-pf-cyan-400 border-pf-cyan-500/20',
  condition: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  action: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
};

/* ─── Component ──────────────────────────────────────────────────────── */

export function Component() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [strategy, setStrategy] = useState<Strategy | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [actionLoading, setActionLoading] = useState(false);
  const [liveLog] = useState<LiveLogEntry[]>([]);

  useEffect(() => {
    if (!id) return;
    setLoading(true);
    fetch(`/api/v1/strategies/${id}`, { credentials: 'include' })
      .then((r) => {
        if (r.status === 404) { setNotFound(true); setLoading(false); return null; }
        if (r.status === 403) { setLoadError('You do not have permission to view this strategy.'); setLoading(false); return null; }
        if (!r.ok) { setLoadError('Failed to load strategy. Please try again.'); setLoading(false); return null; }
        return r.json();
      })
      .then((s: Strategy | null) => {
        if (s) { setStrategy(s); setLoading(false); }
      })
      .catch(() => { setLoadError('Failed to load strategy. Please try again.'); setLoading(false); });
  }, [id]);

  async function doAction(action: 'start' | 'stop' | 'pause' | 'resume', body?: object) {
    if (!strategy) return;
    setActionLoading(true);
    try {
      const res = await fetch(`/api/v1/strategies/${strategy.id}/${action}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify(body ?? {}),
      });
      if (res.ok) {
        const data = await res.json();
        setStrategy((prev) => prev ? { ...prev, status: data.status } : prev);
      }
    } finally {
      setActionLoading(false);
    }
  }

  const status = strategy?.status ?? 'IDLE';
  const statusStyle = STATUS_STYLES[status] ?? STATUS_STYLES.IDLE;
  const totalBlocks = strategy
    ? strategy.safety.length + strategy.triggers.length + strategy.conditions.length + strategy.actions.length
    : 0;
  const pnl = strategy?.totalPnl ?? null;

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      {/* Back */}
      <Link
        to="/strategies"
        className="inline-flex items-center gap-1.5 text-sm text-pf-text-secondary hover:text-pf-text transition-colors"
      >
        <ArrowLeft className="size-3.5" /> Strategies
      </Link>

      {/* Loading */}
      {loading && (
        <div className="animate-pulse space-y-4">
          <div className="h-7 bg-pf-overlay rounded w-[40%]" />
          <div className="h-4 bg-pf-overlay rounded w-[60%]" />
        </div>
      )}

      {/* Not found */}
      {!loading && notFound && (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <p className="text-pf-text font-medium text-lg">Strategy not found</p>
          <p className="text-sm text-pf-text-muted mt-1">This strategy may have been deleted or the link is invalid.</p>
          <button
            onClick={() => navigate('/strategies')}
            className="mt-4 px-4 py-2 rounded-pf bg-pf-elevated border border-pf-border text-sm text-pf-text hover:border-pf-border-strong transition-colors"
          >
            Back to Strategies
          </button>
        </div>
      )}

      {/* Error */}
      {!loading && loadError && (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <p className="text-pf-text font-medium">{loadError}</p>
          <button
            onClick={() => navigate('/strategies')}
            className="mt-4 px-4 py-2 rounded-pf bg-pf-elevated border border-pf-border text-sm text-pf-text hover:border-pf-border-strong transition-colors"
          >
            Back to Strategies
          </button>
        </div>
      )}

      {/* Strategy detail */}
      {!loading && strategy && (
        <>
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
            <div>
              <div className="flex items-center gap-3 mb-1.5">
                <h1 className="text-xl font-semibold text-pf-text">{strategy.name}</h1>
                <span className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium ${statusStyle.bg} ${statusStyle.text}`}>
                  <span className={`w-1.5 h-1.5 rounded-full ${statusStyle.dot} ${isActive(status) ? 'animate-pulse' : ''}`} />
                  {status}
                </span>
              </div>
              {strategy.description && (
                <p className="text-sm text-pf-text-secondary">{strategy.description}</p>
              )}
            </div>

            {/* Actions */}
            <div className="flex items-center gap-2 shrink-0">
              {isIdle(status) && (
                <>
                  <button
                    onClick={() => doAction('start', { mode: 'live' })}
                    disabled={actionLoading}
                    className="flex items-center gap-2 px-3 py-2 rounded-pf bg-pf-cyan-500 text-white text-sm font-medium hover:bg-pf-cyan-600 disabled:opacity-40 transition-colors"
                  >
                    <Zap className="size-3.5" /> Start Live
                  </button>
                  <button
                    onClick={() => doAction('start', { mode: 'paper' })}
                    disabled={actionLoading}
                    className="flex items-center gap-2 px-3 py-2 rounded-pf bg-pf-elevated border border-pf-border text-sm text-pf-text-secondary hover:border-pf-border-strong disabled:opacity-40 transition-colors"
                  >
                    <FileText className="size-3.5" /> Start Paper
                  </button>
                </>
              )}
              {isActive(status) && (
                <>
                  <button
                    onClick={() => doAction('pause')}
                    disabled={actionLoading}
                    className="flex items-center gap-2 px-3 py-2 rounded-pf bg-pf-elevated border border-pf-border text-sm text-pf-text-secondary hover:border-pf-border-strong disabled:opacity-40 transition-colors"
                  >
                    <Pause className="size-3.5" /> Pause
                  </button>
                  <button
                    onClick={() => doAction('stop')}
                    disabled={actionLoading}
                    className="flex items-center gap-2 px-3 py-2 rounded-pf text-red-400 hover:bg-red-500/10 disabled:opacity-40 transition-colors text-sm"
                  >
                    <Square className="size-3.5" /> Stop
                  </button>
                </>
              )}
              {isPaused(status) && (
                <>
                  <button
                    onClick={() => doAction('resume')}
                    disabled={actionLoading}
                    className="flex items-center gap-2 px-3 py-2 rounded-pf bg-pf-cyan-500 text-white text-sm font-medium hover:bg-pf-cyan-600 disabled:opacity-40 transition-colors"
                  >
                    <Play className="size-3.5" /> Resume
                  </button>
                  <button
                    onClick={() => doAction('stop')}
                    disabled={actionLoading}
                    className="flex items-center gap-2 px-3 py-2 rounded-pf text-red-400 hover:bg-red-500/10 disabled:opacity-40 transition-colors text-sm"
                  >
                    <Square className="size-3.5" /> Stop
                  </button>
                </>
              )}
              <Link
                to={`/strategies/${strategy.id}/edit`}
                className="p-2 rounded-pf bg-pf-elevated border border-pf-border text-pf-text-secondary hover:border-pf-border-strong transition-colors"
                title="Edit"
              >
                <Pencil className="size-4" />
              </Link>
            </div>
          </div>

          {/* Meta chips */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="px-2.5 py-1 rounded-full bg-pf-overlay text-pf-text-secondary text-xs font-medium">
              {execLabel(strategy)}
            </span>
            <span className="px-2.5 py-1 rounded-full bg-pf-overlay text-pf-text-secondary text-xs font-medium">
              v{strategy.version}
            </span>
            <span className="px-2.5 py-1 rounded-full bg-pf-overlay text-pf-text-secondary text-xs font-medium">
              {strategy.visibility.toLowerCase()}
            </span>
            <span className="px-2.5 py-1 rounded-full bg-pf-overlay text-pf-text-secondary text-xs font-medium">
              {totalBlocks} blocks
            </span>
            {strategy.tags.map((tag) => (
              <span key={tag} className="px-2.5 py-1 rounded-full bg-pf-cyan-500/10 text-pf-cyan-400 text-xs font-medium">
                {tag}
              </span>
            ))}
            <span className="px-2.5 py-1 rounded-full text-pf-text-muted text-xs ml-auto">
              Updated {formatDate(strategy.updatedAt)}
            </span>
          </div>

          {/* P&L */}
          {pnl !== null && (
            <div className="bg-pf-elevated border border-pf-border rounded-pf-lg p-4">
              <span className="text-xs text-pf-text-muted block mb-1">Total P&L</span>
              <span className={`font-mono text-2xl font-semibold ${pnl >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                {formatPnl(pnl)}
              </span>
            </div>
          )}

          {/* Body grid */}
          <div className="grid grid-cols-1 lg:grid-cols-5 gap-4">
            {/* Blocks summary */}
            <div className="lg:col-span-3 bg-pf-elevated border border-pf-border rounded-pf-lg p-5 space-y-5">
              {(
                [
                  { key: 'safety', title: 'Safety', blocks: strategy.safety },
                  { key: 'trigger', title: 'Triggers', blocks: strategy.triggers },
                  { key: 'condition', title: 'Conditions', blocks: strategy.conditions },
                  { key: 'action', title: 'Actions', blocks: strategy.actions },
                ] as const
              )
                .filter(({ blocks }) => blocks.length > 0)
                .map(({ key, title, blocks }) => (
                  <div key={key}>
                    <h4 className="text-xs font-medium text-pf-text-muted uppercase tracking-wider mb-2">
                      {title}
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {blocks.map((b, i) => (
                        <span
                          key={i}
                          className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-pf-sm border text-xs font-medium ${SECTION_STYLES[key]}`}
                        >
                          {SECTION_ICONS[key]}
                          {blockLabel(b.type)}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}

              {totalBlocks === 0 && (
                <div className="flex flex-col items-center py-8 text-center">
                  <p className="text-sm text-pf-text-muted mb-3">No blocks configured.</p>
                  <Link
                    to={`/strategies/${strategy.id}/edit`}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-pf bg-pf-surface border border-pf-border text-xs text-pf-text-secondary hover:border-pf-border-strong transition-colors"
                  >
                    <Pencil className="size-3" /> Edit Strategy
                  </Link>
                </div>
              )}
            </div>

            {/* Live events */}
            <div className="lg:col-span-2 bg-pf-elevated border border-pf-border rounded-pf-lg overflow-hidden">
              <div className="flex items-center justify-between px-4 py-3 border-b border-pf-border-subtle">
                <span className="text-sm font-medium text-pf-text">Live Events</span>
                {isActive(status) && (
                  <span className="flex items-center gap-1.5 text-xs text-pf-cyan-400">
                    <span className="w-1.5 h-1.5 rounded-full bg-pf-cyan-400 animate-pulse" />
                    Live
                  </span>
                )}
              </div>

              <div className="p-4 max-h-80 overflow-y-auto">
                {liveLog.length === 0 ? (
                  <div className="py-8 text-center text-sm text-pf-text-muted">
                    {isActive(status) ? 'Waiting for events\u2026' : 'Start the strategy to see live events.'}
                  </div>
                ) : (
                  <div className="space-y-1.5">
                    {liveLog.map((entry, i) => (
                      <div key={i} className="flex items-start gap-2 text-xs">
                        <span className="font-mono text-pf-text-muted shrink-0 w-16">
                          {formatTime(entry.time)}
                        </span>
                        <span className={`w-1.5 h-1.5 rounded-full mt-1.5 shrink-0 ${LOG_DOT_COLORS[entry.severity]}`} />
                        <span className={LOG_COLORS[entry.severity]}>{entry.message}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
