// apps/user-app/src/pages/legal/privacy.tsx
import { Link } from 'react-router';
import { ArrowLeft, Zap } from 'lucide-react';

const LAST_UPDATED = 'January 15, 2025';

export function Component() {
  return (
    <div className="min-h-screen bg-pf-base">
      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <Link to="/" className="flex items-center gap-2 text-sm text-pf-text-muted hover:text-pf-text transition-colors">
            <ArrowLeft className="size-4" /> Back
          </Link>
          <div className="flex items-center gap-2 text-pf-text">
            <Zap className="size-4 text-pf-cyan-400" />
            <span className="font-semibold">Polyforge</span>
          </div>
        </div>

        <h1 className="text-2xl font-semibold text-pf-text mb-2">Privacy Policy</h1>
        <p className="text-sm text-pf-text-muted mb-10">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-8 text-sm text-pf-text-secondary leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">1. Overview</h2>
            <p>Polyforge ("we", "our") is committed to protecting your privacy. This Privacy Policy explains what information we collect, how we use it, and your rights regarding that information when you use our Platform.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">2. Information We Collect</h2>
            <h3 className="text-base font-medium text-pf-text mt-4 mb-2">2.1 Account Information</h3>
            <p>When you register, we collect your email address, username, and hashed password. You may optionally provide a display name and avatar.</p>
            <h3 className="text-base font-medium text-pf-text mt-4 mb-2">2.2 Usage Data</h3>
            <p>We automatically collect information about how you interact with the Platform, including pages visited, features used, API calls made, and error events. This data is collected via server-side logs and does not include third-party analytics trackers.</p>
            <h3 className="text-base font-medium text-pf-text mt-4 mb-2">2.3 Trading Activity</h3>
            <p>We store the orders, positions, strategy configurations, and backtest results associated with your account in order to provide the service.</p>
            <h3 className="text-base font-medium text-pf-text mt-4 mb-2">2.4 Communications</h3>
            <p>When you contact us by email or through support channels, we retain those communications to assist you and improve our service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">3. How We Use Your Information</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>To create and maintain your account;</li>
              <li>To execute and record trading activity on your behalf;</li>
              <li>To send transactional emails (email verification, password reset, trade confirmations);</li>
              <li>To detect and prevent fraud, abuse, and security incidents;</li>
              <li>To improve the Platform based on aggregated usage patterns;</li>
              <li>To comply with legal obligations.</li>
            </ul>
            <p className="mt-3">We do not sell your personal data to third parties. We do not use your data for targeted advertising.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">4. Legal Bases for Processing (GDPR)</h2>
            <p>For users in the European Economic Area, we process your data on the following legal bases: performance of a contract (providing the service you signed up for), legitimate interests (security and fraud prevention), compliance with legal obligations, and consent where explicitly requested.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">5. Data Retention</h2>
            <p>Account and trading data is retained for the lifetime of your account and for up to 7 years after account deletion to satisfy legal and audit obligations. Logs are retained for 90 days. You may request earlier deletion of personal data subject to legal constraints by contacting us.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">6. Data Sharing</h2>
            <p className="mb-2">We share your data only with:</p>
            <ul className="list-disc list-inside space-y-1">
              <li><strong className="text-pf-text">Infrastructure providers</strong> -- cloud hosting, database, and email delivery vendors operating under data processing agreements;</li>
              <li><strong className="text-pf-text">Legal authorities</strong> -- when required by law, court order, or to protect the rights and safety of users or the public.</li>
            </ul>
            <p className="mt-3">Publicly shared strategies display your username and display name. Strategy content is visible to all logged-in users when you set visibility to "public".</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">7. Security</h2>
            <p>We use industry-standard security measures including TLS encryption in transit, bcrypt password hashing, JWT-based authentication with short-lived tokens, and role-based access controls. No security measure is perfect; please enable two-factor authentication on your account.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">8. Cookies and Local Storage</h2>
            <p>We use browser local storage to persist your authentication token and UI preferences. We do not use third-party tracking cookies. No data is shared with advertising networks.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">9. Your Rights</h2>
            <p className="mb-2">Depending on your jurisdiction, you may have the right to:</p>
            <ul className="list-disc list-inside space-y-1">
              <li>Access the personal data we hold about you;</li>
              <li>Correct inaccurate data;</li>
              <li>Request deletion of your personal data ("right to be forgotten");</li>
              <li>Object to or restrict processing;</li>
              <li>Data portability (receive a machine-readable copy of your data);</li>
              <li>Withdraw consent at any time, without affecting lawfulness of prior processing.</li>
            </ul>
            <p className="mt-3">To exercise these rights, email <a href="mailto:privacy@polyforge.app" className="text-pf-cyan-400 hover:underline">privacy@polyforge.app</a>. We will respond within 30 days.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">10. Children's Privacy</h2>
            <p>The Platform is not directed to individuals under 18 years of age. We do not knowingly collect personal data from children. If you believe a child has created an account, please contact us immediately.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">11. Changes to This Policy</h2>
            <p>We may update this Privacy Policy periodically. Material changes will be communicated to registered users by email at least 14 days before taking effect. Continued use after that date constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-pf-text mb-3">12. Contact</h2>
            <p>For privacy-related questions or requests, contact: <a href="mailto:privacy@polyforge.app" className="text-pf-cyan-400 hover:underline">privacy@polyforge.app</a>.</p>
          </section>
        </div>

        {/* Footer */}
        <div className="flex items-center gap-3 mt-12 pt-6 border-t border-pf-border-subtle text-sm text-pf-text-muted">
          <Link to="/terms" className="hover:text-pf-text transition-colors">Terms of Service</Link>
          <span>&middot;</span>
          <Link to="/login" className="hover:text-pf-text transition-colors">Sign in</Link>
          <span>&middot;</span>
          <Link to="/register" className="hover:text-pf-text transition-colors">Register</Link>
        </div>
      </div>
    </div>
  );
}

// apps/user-app/src/app/features/legal/privacy/privacy.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-privacy',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './privacy.component.html',
})
export class PrivacyComponent {
  readonly lastUpdated = 'March 17, 2026';
}

<div class="legal-page">
  <div class="legal-container">

    <div class="legal-header">
      <a routerLink="/" class="legal-back">
        <i class="pi pi-arrow-left"></i> Back
      </a>
      <div class="legal-logo">
        <i class="pi pi-bolt"></i>
        <span>Polyforge</span>
      </div>
    </div>

    <h1 class="legal-title">Privacy Policy</h1>
    <p class="legal-meta">Last updated: {{ lastUpdated }}</p>

    <div class="legal-body">

      <section>
        <h2>1. Overview</h2>
        <p>
          Polyforge ("we", "our") is committed to protecting your privacy. This Privacy Policy explains
          what information we collect, how we use it, and your rights regarding that information when
          you use our Platform.
        </p>
      </section>

      <section>
        <h2>2. Information We Collect</h2>
        <h3>2.1 Account Information</h3>
        <p>
          When you register, we collect your email address, username, and hashed password. You may
          optionally provide a display name and avatar.
        </p>

        <h3>2.2 Usage Data</h3>
        <p>
          We automatically collect information about how you interact with the Platform, including
          pages visited, features used, API calls made, and error events. This data is collected
          via server-side logs and does not include third-party analytics trackers.
        </p>

        <h3>2.3 Trading Activity</h3>
        <p>
          We store the orders, positions, strategy configurations, and backtest results associated
          with your account in order to provide the service.
        </p>

        <h3>2.4 Communications</h3>
        <p>
          When you contact us by email or through support channels, we retain those communications
          to assist you and improve our service.
        </p>
      </section>

      <section>
        <h2>3. How We Use Your Information</h2>
        <ul>
          <li>To create and maintain your account;</li>
          <li>To execute and record trading activity on your behalf;</li>
          <li>To send transactional emails (email verification, password reset, trade confirmations);</li>
          <li>To detect and prevent fraud, abuse, and security incidents;</li>
          <li>To improve the Platform based on aggregated usage patterns;</li>
          <li>To comply with legal obligations.</li>
        </ul>
        <p>
          We do not sell your personal data to third parties. We do not use your data for targeted
          advertising.
        </p>
      </section>

      <section>
        <h2>4. Legal Bases for Processing (GDPR)</h2>
        <p>
          For users in the European Economic Area, we process your data on the following legal bases:
          performance of a contract (providing the service you signed up for), legitimate interests
          (security and fraud prevention), compliance with legal obligations, and consent where
          explicitly requested.
        </p>
      </section>

      <section>
        <h2>5. Data Retention</h2>
        <p>
          Account and trading data is retained for the lifetime of your account and for up to 7 years
          after account deletion to satisfy legal and audit obligations. Logs are retained for 90 days.
          You may request earlier deletion of personal data subject to legal constraints by contacting
          us.
        </p>
      </section>

      <section>
        <h2>6. Data Sharing</h2>
        <p>
          We share your data only with:
        </p>
        <ul>
          <li>
            <strong>Infrastructure providers</strong> — cloud hosting, database, and email delivery
            vendors operating under data processing agreements;
          </li>
          <li>
            <strong>Legal authorities</strong> — when required by law, court order, or to protect the
            rights and safety of users or the public.
          </li>
        </ul>
        <p>
          Publicly shared strategies display your username and display name. Strategy content is
          visible to all logged-in users when you set visibility to "public".
        </p>
      </section>

      <section>
        <h2>7. Security</h2>
        <p>
          We use industry-standard security measures including TLS encryption in transit, bcrypt
          password hashing, JWT-based authentication with short-lived tokens, and role-based access
          controls. No security measure is perfect; please enable two-factor authentication on your
          account.
        </p>
      </section>

      <section>
        <h2>8. Cookies and Local Storage</h2>
        <p>
          We use browser local storage to persist your authentication token and UI preferences. We
          do not use third-party tracking cookies. No data is shared with advertising networks.
        </p>
      </section>

      <section>
        <h2>9. Your Rights</h2>
        <p>Depending on your jurisdiction, you may have the right to:</p>
        <ul>
          <li>Access the personal data we hold about you;</li>
          <li>Correct inaccurate data;</li>
          <li>Request deletion of your personal data ("right to be forgotten");</li>
          <li>Object to or restrict processing;</li>
          <li>Data portability (receive a machine-readable copy of your data);</li>
          <li>Withdraw consent at any time, without affecting lawfulness of prior processing.</li>
        </ul>
        <p>
          To exercise these rights, email <a href="mailto:privacy@polyforge.app">privacy&#64;polyforge.app</a>.
          We will respond within 30 days.
        </p>
      </section>

      <section>
        <h2>10. Children's Privacy</h2>
        <p>
          The Platform is not directed to individuals under 18 years of age. We do not knowingly
          collect personal data from children. If you believe a child has created an account, please
          contact us immediately.
        </p>
      </section>

      <section>
        <h2>11. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy periodically. Material changes will be communicated to
          registered users by email at least 14 days before taking effect. Continued use after that
          date constitutes acceptance.
        </p>
      </section>

      <section>
        <h2>12. Contact</h2>
        <p>
          For privacy-related questions or requests, contact:
          <a href="mailto:privacy@polyforge.app">privacy&#64;polyforge.app</a>.
        </p>
      </section>

    </div>

    <div class="legal-footer">
      <a routerLink="/terms">Terms of Service</a>
      <span class="legal-footer-sep">·</span>
      <a routerLink="/login">Sign in</a>
      <span class="legal-footer-sep">·</span>
      <a routerLink="/register">Register</a>
    </div>

  </div>
</div>
